### ISSUE TITLE
In the Cards Documentation the available shadow depths are unclear

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1000]
In the [Cards Documentation](http://www.getmdl.io/components/index.html#cards-section) is the following reference to mdl-shadow--*:
![image](https://cloud.githubusercontent.com/assets/197231/8645136/fe00fdb6-2987-11e5-805a-9fc577d1c228.png)

In the first column it insinuates that shadows from 2dp to 8dp are available, but in the CSS the available shadows are 2, 3, 4, 6, 8, 16. Is there a way that the documentation could be updated so its clear exactly what shadow depths are available?

It also mentions "assigns available shadow depths (1-5)." Are shadow depths 1-5 still mentioned in the current Material Design spec? They [were in the old spec](https://web.archive.org/web/20140627054059/http://www.google.com/design/spec/layout/layout-principles.html) but there doesn't seem to be any reference to them in the new spec.

**Comment by dgash** [comment]
Yes, the text in the staged doc (http://www.getmdl.io/components/index.html#cards-section) is indeed incorrect. This appears to be because the doc was staged from the README.md in the repo's **master** branch. However, the README.md in the repo's **documentation** branch (in which I work) is correct. Apparently, the doc branch was not merged into the master before staging the README. I suggest that this merge should be done to get the master branch up to date.

Related caveat: Various READMEs in the master branch have been edited by others, so they also don't match my versions in the doc branch. Those changes may need to be redone post-merge.

**Comment by SeanBannister** [comment]
This was fixed by #1148
