### ISSUE TITLE
Make components fluid by default

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1016]
Many of the component such as cards and data tables have hard-coded widths. This is confusing developers as to how to best adjust them. Ref #820 and also some [issues on SO](https://stackoverflow.com/questions/31360070/material-design-lite-grid-with-tables).

Since we are recommending using the grid or setting your own custom widths anyways. Perhaps we should make sure all (possible) components in the future don't have hard widths set. Instead just let them fill all the space they can and developers can then use the grid or custom widths to constrain them instead of making them bigger than provided.

Certainly can't land in 1.x lifecycle, but next major seems like a good place to handle as much as we can here.

cc @sgomes for thoughts since you built the Data Table with a hard width. Maybe there was a reason for it.

**Comment by innerpeace0** [comment]
@Garbee, I've been having related similar thoughts but didn't want to write a new issue about it, so here seems like the place to add it. 

The official wordpress themes, such as twentyfourteen, are automatically responsive. The place this is most obvious is viewing a page with a tablet. View a page horizontally and then flip it vertically, and, voila, it just realigns. Web authors (I purposely didn't use the term web developers here) using these themes don't even need to think about it. It just happens by default.

If there were a way to make some mdl templates just as easily responsive by default, so that web authors who weren't really developers could easily use mdl templates that worked anywhere out of the box, that would be a fantastic enhancement.

**Comment by Garbee** [comment]
@innerpeace0 Nothing is stopping that with MDL now. You simply need to apply the grid properly. Which you need to do anyways since you almost never want 100% width cards for instance on a desktop.

This change is simply putting it more on the developer to put the components together to get the design they want over just dropping things in and magic happening.

Cards for instance, will never have their own breakpoints to change widths. Too much weight and too variable between projects/developers. Using the grid gives you the inherit breakpoints of the grid system for free.

I don't think MDL needs to build things so the lowest-common-denominator can use it. Developers need to understand their tools and apply them properly. Aiming a framework to non-developers is a bit of an oxymoron imo. People shouldn't use things they don't understand, they should get help from people that do.

**Comment by kybarg** [comment]
+1

**Comment by LCallaghan84** [comment]
Well you are putting some people at a disadvantage because its not easy to understand the so called "documentation" and "examples" that you have provided for MDL

the components need to be resized and fit into that column depending on the grid that is set

for example 
desktop grid would be 
column size 8 (for the content) and column 4 (for the side bar and widgets)

for tablet/mobile, the grid would resize
for the content area, the size of the column size would be 12
and the sidebar would go below the content column or in the drawer below the menu)

I tried this with MDL and it did not work, but with Materialize it did, because they explained how their components and grid system works.

So before you start blaming the users for not knowing how to use the MDL framework, perhaps you should start fixing the documentation and explain it more clearly.

**Comment by surma** [comment]
@LCallaghan84 While I do agree that we could definitely be doing a better job at documenting the grid, I don’t feel like “it didn’t work” is constructive feedback nor do I have the impression that we are “blaming the users for not knowing how to use the MDL framework”. 

The example you are giving shows that we are obviously failing to communicate how the grid works, even though the [documentation](http://www.getmdl.io/components/index.html#layout-section/grid) says

> A grid has 12 columns in the desktop screen size, 8 in the tablet size, and 4 in the phone size

So far, we figured we are targeting developers who would also have no problem reading the code of your templates, which are responsive and use the grid extensively. They give a good, complementary guide in addition to the text-based documentation on the components page. 

In any case, you have been heard and improving the components pages including the components’ documentation is definitely something we want to tackle.

**Comment by ramijarrar** [comment]
Are there still plans for this in the next major release (2.x)?

**Comment by Garbee** [comment]
Yup, already working on it.

**Comment by ramijarrar** [comment]
:+1:

**Comment by sgomes** [comment]
Closing issue, as 2.x development has moved to [Material Components for the web](https://github.com/material-components/material-components-web).
