### ISSUE TITLE
More touch support (swipe tabs, touch drawer)

### ISSUE THREAD

**Issue by RichardLindhout** [google/material-design-lite#1023]
I am very likely to switch to this framework for making my new websites.

It looks like a very nice framework to me, only in http://materializecss.com/ they have a touch friendly navigation drawer.

It would be cool if there was more touch support like swiping tabs and and a drawer touch to make it more like a native app. 

EDIT: Added SlideNav code used by materializecss for making the drawer touch friendly.
https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js

Needs convert to pure javascript..

**Comment by surma** [comment]
We are not a framework ^^

Can you elaborate what you mean by “touch friendly navigation drawer”? Do you mean that you can slide-in the drawer?

**Comment by RichardLindhout** [comment]
Haha, yeah right (some kind of front-end framework) :+1: 

And that you indeed can slide the drawer!

Also slide tabs like this library http://www.idangero.us/swiper/#.Vae2xZ7tlBc

**Comment by surma** [comment]
This is probably desirable in the long run but we’ll have to do some research on how to do this in a cross-browser compatible way.

**Comment by RichardLindhout** [comment]
Thanks dude, would be cool. Can you please adress this issue https://github.com/google/material-design-lite/issues/1072 to the Chrome team?

**Comment by Garbee** [comment]
@RichardLindhout Nothing the Chrome team can really do about #1072. And let's keep the discussion about issues within the issues themselves and not cross-talk between them. This digresses conversation and becomes confusing.

**Comment by mercmobily** [comment]
In the meantime, would it make sense/would it work to use paper-drawer-panel to obtain a panel that is more touch-friendly so to speak? (See: it pulls out when you slide it out, it goes back in when you slide it back in, etc.)
Just asking...

**Comment by Garbee** [comment]
We can't include web components. We need to rebuild anything in raw JS, which is part of the problem. Raw JS events don't have gesture support afaik. They are pure touch events that we'd then need to calculate  a gesture from.

**Comment by mercmobily** [comment]
Oh no I know... I meant if somebody *needed* to have the sliding effect, then they *could* obtain it by including web components and paper-drawer-panel. I didn't mean it as "you should do this using web components" -- sorry for the misunderstanding!

**Comment by traviskaufman** [comment]
Closing this as we will not be making major changes to v1.x since we are actively working on v2.

WRT touch in v2, it will most likely be handled on a case-by-case basis per component. That being said, as @surma mentioned due to the nature of MDL targeting the vanilla web platform and not being a framework, we'd probably be wary of building or depending on a gesture recognition library that wasn't part of the web platform.

That being said, our v2 components will be architected in a much more flexible way (see our [experimental/v2-architecture-poc branch](https://github.com/google/material-design-lite/tree/experimental/v2-architecture-poc)), which should allow you to easily use a gesture library such as [hammerJS](http://hammerjs.github.io/) to drive a component using gestures.

**Comment by mu3** [comment]
Can you approximately tell when to expect v2?

**Comment by Garbee** [comment]
We currently aren't giving any exact details on V2, much less a timeline. If you want take a peek around the `master` branch, we just merged the proof-of-concept things into there. However, it is still very early and under heavy flux.
