### ISSUE TITLE
problem with dynamic content loading

### ISSUE THREAD

**Issue by muten84** [google/material-design-lite#1035]
if i try to load an html section containing MDL components trough a XHR request and then attach it to the DOM (with innerHtml property)  the resuting page is not working as expected. If i statically write the html code in the initial html page loaded by the browser the same html section with the same MDL components works as well.... any ideas about this "bug"?

**Comment by Garbee** [comment]
Support questions should be asked on StackOverflow.

**Comment by innerpeace0** [comment]
@Garbee, I was planning on doing exactly what @muten84 just described with MDL and have it work. Are you saying that his question is a support question because the documentation already covers this fully?

**Comment by Garbee** [comment]
Getting started covers what to do with dynamically added elements. At least one method for it. We are still working on the story for in-site docs on how to handle this aspect of development. However, that doesn't change the fact that it is supported and is not a "bug" of any kind. 

Support questions are best asked on SO so more developers can see and answer the question as well as find related problems. Once something is then found to not be possible or be outright broken (or other cases, I'm not saying these are the only reasons), then an issue should be filed in this tracker since there is a core problem.

We can't support many developers asking the same questions over and over. Whether it is documented or not. There are some gaps in the documentation that is being worked on to get addressed, but it isn't as easy as just throwing another page up and making it have words. This flow allows developers to get the most help and the core team to address real problems with the code provided.

**Comment by innerpeace0** [comment]
I never quite knew where those lines were. Thanks for that great clarification.

Glad to know that MDL will do what it's supposed to with dynamically loaded content, too.

I'm really enjoying watching the team behind this and the community of devs work together to refine MDL. I've never seen a project address so many things so quickly. Great job to you, the team, and all the participants.

**Comment by Garbee** [comment]
I'm sorry, it is a pretty fine line that can be hard to tell at times. But, trying to keep a tracker for an instantly eye-catching project is difficult. This seems to be the best way to handle it.

I'd rather we close support questions and move developers where support is provided best. That way they get the help and others can find it. Then the issues here are things directly actionable by contributors to help the project for everyone.

**Comment by muten84** [comment]
Thanks for  the quick reply. I'll report my issue in stackoverflow as suggested. However the fact you ensure this is not a bug is an answer for me and a great starting point for discussion purpose.... if dynamic content management with MDL is  not immediate having documentation would be great :). This project is really great. Thanks a lot.
