### ISSUE TITLE
Could you host a build that doesn't use tags in selectors?

### ISSUE THREAD

**Issue by nickretallack** [google/material-design-lite#1037]
I want to introduce material design components to an existing website.  I was hoping to reference a CDN-hosted version of it.

Fortunately, most of the selectors use classes starting with mdl-, so it is easy to use them only where I want them.

Unfortunately, there are also a lot of selectors that directly style tags.  These selectors are messing up existing functionality in my site.

For example, why is this in there?

```css
ul,ol {
    font-size:14px;
    line-height:24px
}
```

**Comment by Garbee** [comment]
This is a part of [typography](https://github.com/google/material-design-lite/blob/master/src/typography/_typography.scss#L104-106).  We decided to do this so developers can easily have basic typography of MD setup without any effort. Where otherwise, you need to explicitly add typography classes to every element.

This is a bit of an uncommon use-case overall. Most developers won't pull certain components out, they will use MDL as a whole so that is what we provide via CDN. In this case, it is best you add MDL into your build flow and pull in only the components you need. This will mean however, that they may need some work to adhere to Material Design typography if that is desired.

Action here: Add a variable to state in a build that you want typography but not these direct selectors.

**Comment by nickretallack** [comment]
That may be a dealbreaker.

Anyway, I still think it would be useful to host a version that does not style any tags directly, for folks who would like to use this as an alternative to Polymer Web Components.

**Comment by nickretallack** [comment]
Besides, <ul> is often used for making semantic markup.  Applying a typography style to it seems absurd.

**Comment by Garbee** [comment]
>  making semantic markup.

First semantic should be defined properly and given context. :smile: Such a statement is very vague and highly debatable depending on viewpoint.

ULs are touched in this context since they should be used for *listing* text. If you are doing something else with them, yes, you may need to override the typographic style.

A PR has been made with a flag to help address this problem, let's see where that goes.

**Comment by nickretallack** [comment]
Using `<ul>` for things other than text is actually very common on the web.  Check out [navs in bootstrap](http://getbootstrap.com/components/#nav).

**Comment by Garbee** [comment]
Yea, I know they are often used for menus. Quite un-semantic now that `<nav>` exists and can be used with direct anchors children to get the same result and be semantic in terms of HTML and humans reading. (And tossing a unordered list into a nav does not somehow double the semantics.)

This is the sematnicness pit that has been created. It all depends on viewpoints of what is right and wrong in most cases.

**Comment by nickretallack** [comment]
In this case, all I care about is that this library play nicely with existing markup.  A lot of existing markup uses `<ul>` and this library is breaking it.  I am probably not the only person who will complain about this.

**Comment by Garbee** [comment]
I'm not the one who decides what goes onto the CDN. However, your case is niche. I don't think we should be hosting things that overtly don't implement MD as fully as possible.

These kinds of cases are best dealt with via custom builds since it should be an explicit developer action showing they understand MD may not be fully applied.

A patch is requested that makes it trivial to undo this styling in custom builds. It is up to the other team members to decide if it is something that should be done and then if they want to support it via the CDN.

**Comment by Garbee** [comment]
PR has been accepted into master. So starting now if you clone directly or with the 1.0.1 patch (assuming we get sources into packages as planned) you can use the `$target-elements-directly` variable (setting it to false) to remove this behavior.

Triggering this should be an absolute developer action. It mis-aligns things from Material Design, which is what we intend to be adhered to using MDL. Therefore, we won't be hosting permutations on the CDN at this time.

**Comment by nickretallack** [comment]
I thought of something that would be better than splitting it into files.  What if you just asked users to add a class to the `<html>` element if they want to opt in to bare selectors?

**Comment by Garbee** [comment]
We did that. Specificity problems. It ended up making the core super hacky.
Then modifying if desired became a pain.

**Comment by nickretallack** [comment]
I just noticed you're using `<ul>` in the [example code for menus](http://www.getmdl.io/components/index.html#menus-section).

**Comment by Garbee** [comment]
@nickretallack And with our classes, it works fine. Not sure what bringing the examples up brings to the discussion. Do you mind elaborating on the purpose of pointing it out?
