### ISSUE TITLE
Waterfall header hides menus / tooltips etc.

### ISSUE THREAD

**Issue by dflorey** [google/material-design-lite#1086]
When using a waterfall header the overflow is set to hidden which cuts off all tooltips / dropdown menus etc. in the header.

**Comment by waldekcher** [comment]
Can you be more specific? I Have no problem with waterfall header & menu at all

**Comment by dflorey** [comment]
See tooltip on the edit button:

http://codepen.io/anon/pen/BNPePm

**Comment by surma** [comment]
The overflow topic in the layout component is somewhat delicate. My proposal: Move the tooltip outside of the header: http://codepen.io/anon/pen/PqBvXO

**Comment by dflorey** [comment]
You are the man! Would be worth to add this workaround to the docs.

**Comment by surma** [comment]
Glad it worked. I’ll see if I can find an appropriate place to document this, maybe a component demo. Closing this for now :)

**Comment by CrandellWS** [comment]
@surma :+1:  Thanks my thought is generally to suggest it is put on the bottom of the page just before the closing body tag. If only because this suggestion will prevent questions about why it does not show... Not sure how to put it but as far as where to put it, I think :

https://github.com/google/material-design-lite/blob/master/src/menu/README.md
