### ISSUE TITLE
autofocus attribute doesn't work

### ISSUE THREAD

**Issue by jycr** [google/material-design-lite#1125]
autofocus native HTML5 attribute doesn't work with material-design-lite

**Comment by Garbee** [comment]
This is probably manifesting due to the JS upgrade. Making it work would be fairly complicated, since we would need to check the DOM and compute hidden states of other things that may have auto-focus and do logic for whether to focus or not on *each* upgrade occurrence.

Overall, sounds like something we should just deal with not having for the sake of performance and reliability.

**Comment by jorgefuertes** [comment]
Any workarounds? Thanks.

**Comment by jorgefuertes** [comment]
I cannot set the focus neither with jQuery focus(). It appears like if its an small problem but is actually a big one, you cannot do basic from management.

**Comment by samccone** [comment]
I think this would be a good thing to investigate adding and measure the actual perf cost

**Comment by Garbee** [comment]
We need to add a `checkFocusState` method to make sure the focused class gets added. It would need to get called after you do any other JS based focusing (since they don't fire focus events afaik.) That will help solve the manual focus (which is off-topic for this thread btw.)

As far as autofocus, I'm not sure how we'd support handling that since autofocus doesn't trigger a focus event. We'd need some global JS that always runs on page load to check for the attribute and handle focus updating manually. Something we shouldn't be doing.

**Comment by samccone** [comment]
hypothetically if an element has focus and it is upgraded it should keep focus right?

So given that assumption, it should be doable to "refocus" an element post upgrade maybe... :goat:

**Comment by Garbee** [comment]
Ah yea, autofocus should trigger before we start upgrading. So we can check the focus state in the init method. Good thinking there.

**Comment by samccone** [comment]
:bow:

**Comment by jorgefuertes** [comment]
Great!

**Comment by macpham** [comment]
Hi, if this is not supported automatically -- is there a preferred way to manually autofocus after an element has been upgraded?

And I'm not talking about just textfields but all the user input elements: `input`, `buttons`, `select` etc.
