### ISSUE TITLE
Drawer Navigation on Text-Only template not working

### ISSUE THREAD

**Issue by smogil-squadup** [google/material-design-lite#1177]
I took a screengrab here: http://recordit.co/SMbAulMcQe

The tabs links to IDs work in the regular desktop version, but do not work from the drawer. This is pulled directly from the template, with no code changes at all. Can someone please help me? Thanks! 

-sam

**Comment by surma** [comment]
Yes, that’s bug #835 and has been fixed in #876. You are working on an old version of the templates, although that can happen as the downloadable ZIP will only get updated once we release 1.0.1.

If you take a look at [the live version](http://www.getmdl.io/templates/text-only/index.html), you’ll see that we fix'd it there.

For now, you can grab the [fix'd template from master](https://github.com/google/material-design-lite/blob/6c6f1346b0cfb2f23b541afb7ac8c81c7e4bfa7c/templates/text-only/index.html).

**Comment by smogil-squadup** [comment]
Excellent, thanks. I tried searching for this before but couldn't find anything. Appreciate the assistance.
