### ISSUE TITLE
Simple way to define custom primary and accent color

### ISSUE THREAD

**Issue by rdesimone** [google/material-design-lite#1207]
It would be nice to have a simple way to define custom primary and accent colors to adapt to corporate colors. Something similar (also less sophisticated) like the Angular Material themingProvider.

https://material.angularjs.org/latest/#/Theming/03_configuring_a_theme

Thanks!

**Comment by Gheoan** [comment]
This is possible using the [customize](http://www.getmdl.io/customize/index.html) function or using the SASS version by changing a variable https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L85 .

**Comment by Garbee** [comment]
Sass is the way to handle this. It is the same way we generate the static color combinations.

**Comment by rdesimone** [comment]
@Garbee thanks, as far as I understand Sass requires to fork and to build the project (it is not the end of the world). The very nice thing about material design lite is the simplicity to use. IMO there should be a way to set custom colors without building the project - AM solved this nicely. Think about it again and if you agree, keep this issue open as a feature request for a future version. Thanks again!

**Comment by Garbee** [comment]
This is a very specific decision. Sass is how you build your own copy using only the components you need and doing further configuration. With version 1.0.1 the Scss sources are now provided right in the npm and bower packages as well.

Simply because another MD implementation does things another way doesn't mean it is the right way to handle things. Angular is a full front-end JS framework that can handle that type of configuration. MDL is not a framework, therefore it makes no sense to handle that kind of configuration on the frontend with any means.
