### ISSUE TITLE
Table selectable - and now?

### ISSUE THREAD

**Issue by hannespreishuber** [google/material-design-lite#1240]
I didn't get the story how to get the selected items in a table- Need advice in doc.

**Comment by Garbee** [comment]
Use JS to query up the table rows, loop over them and check the checkbox state. We are investigating ways to help make knowing the checkboxes target easier (  #1170 ) and other ways of knowing when a check has occurred ( #1210 ).

Beyond this, we are probably not going to handle documenting directly how to get this information since it falls more into general support since there are numerous different ways to do it. Each one has its own pros and cons for given situations, so developers need to understand and implement what is best.
