### ISSUE TITLE
Release branch?

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1248]
Just a quick question, but what's the reason of the release branch?

It seems we could keep only the master branch with a `dist` folder for these minified files. On npm, you'll publish only the files you want by specifying a `.npmignore`. And I think you can do the same with bower.

**Comment by surma** [comment]
We opted for a separate release so that master is source only. We started out having `dist` on master, but the folder was hardly ever up to date with the corresponding `src` and caused a lot of confusion. Also we have multiple things being built (core lib, website and CDN files) and not all of them make sense to commit.

**Comment by tleunen** [comment]
Thanks for the explanation!
