### ISSUE TITLE
Thoroughly review and fix layout docs

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#1310]
There have been several instances of layout documentation being incorrect (e.g. #1294 and #1289).

**Comment by addyosmani** [comment]
It might also be worth cross-checking against https://github.com/google/material-design-lite/commit/313ccfda3d868f689f82e83c17d5447d4b27f27e for anything we didn't have a chance to bring in back in June, though for the most part I imagine part of the issue is changes to the layout system haven't been accompanied with docs updates. We can enforce that better.

**Comment by sgomes** [comment]
Will do, some things may have got lost in that migration.

As for enforcement, I strongly agree. Let's keep an eye out for documentation when merging patches while the 1.1 feature window is open.
