### ISSUE TITLE
[Feature Request] add launch-screens

### ISSUE THREAD

**Issue by spyhole** [google/material-design-lite#1323]
The launch screen is a user’s first experience of your application.

Because launching your app while displaying a blank canvas increases its perceived loading time, consider using a placeholder UI or a branded launch screen.

A placeholder UI is the most seamless launch transition—appropriate for both app launches and in-app activity transitions.

Branded launch screens provide momentary brand exposure, freeing the UI to focus on content.

http://www.google.com/design/spec/patterns/launch-screens.html#launch-screens-placeholder-ui

**Comment by darkyen** [comment]
+1 Its really easy to do though, but still.

**Comment by rohanthacker** [comment]
I'm curious to know how would this be implement using vanilla  javascript.
 
As mentioned above this is a common for applications and this would be a whole lot better to implement with a framework, putting it out of the scope of this project right?  

For example : 
The usability of the component would be a whole lot more if implemented under https://github.com/mike-north/ember-material-lite taking advanted of the frameworks loading substates 

P.S : I don't want to stamp or in anyway hinder the growth and progress of this project. Just trying to understand the boundaries of lite.

**Comment by sgomes** [comment]
This isn't really something that MDL can help with, since it runs against the goal of the launch screen itself: providing some form of UI that loads faster than the rest of the content.

Launch screen content should part of the HTML being loaded, as markup and inline styles. The other options is to use native platform support, such as [splash screens in Chrome 47](https://developers.google.com/web/updates/2015/10/splashscreen?hl=en). Either way, this is not something that MDL can help with, I'm afraid :-/
