### ISSUE TITLE
Box-shadows fade out causes a small deviation from spec

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1338]
Due to the way that box-shadow works there's a small fade out on the corners of the header (and I presume other components may suffer from this). I don't believe there's an elegant way to fix this, and any fix might be more trouble than its worth for such a small deviation from the spec. But thought it was important to document here in case a simple fix is found.

![image](https://cloud.githubusercontent.com/assets/197231/9154698/f5178774-3ee0-11e5-9130-1276adbb2786.png)

**Comment by surma** [comment]
>  I don't believe there's an elegant way to fix this

I’m afraid that is the case. @sgomes any CSS magic you know of?

**Comment by sgomes** [comment]
We could presumably create a different shadow definition with no x offset for elements that are `width: 100%`. I'll see if I can cook something up. Thanks, @SeanBannister!

**Comment by sgomes** [comment]
Right, I misunderstood the issue; there is no x offset anyway, this is just due to the fade.

I don't think a fix will be easy; it would probably revolve around using an `after` block which would be clipped to its parent.

We can try to avoid this running into this issue in an eventual 2.x, but it's sadly out of scope for now :-/
