### ISSUE TITLE
Layout downgrade

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1340]
The Layout component doesn't have a downgrade function to remove the dom elements and events...

**Comment by surma** [comment]
We are aware (see #317). I’m not sure when we will commit to that effort, though. I’m leaving this issue open as a reminder for us. Thanks for opening :)

**Comment by tleunen** [comment]
I think this is causing me some issues in another project so I'll try to help on this :)

**Comment by Garbee** [comment]
> I'm using 1.0.4. MaterialLayout is still not being removed from createdComponents_ when calling downgradeElements. This is quite critical since a layout usually occupies quite some memory in the _content property. - @reinholdk in issue #1134 

FTR, unless someone implements downgrading for Layout in 1.1 it probably won't ever happen when calling `downgradeElements()`. We need to create a whole new method to just remove something from the created components array. However, this will still have leaks since event listeners and such won't be unbound.

Layout is a very complex downgrade to handle. It is also an edge-case to be downgraded (since we are targeting more static sites at the moment) which is why implementing its downgrade method is a very low priority.

**Comment by reinholdk** [comment]
I see. I could rework the application to use a single instance of MaterialLayout instead of destroying/recreating it.

**Comment by hr-117** [comment]
I like to put some attention to this issue. 
In my understanding  there are some reason changes to downgradeElements. 
It does not depend on component downgradeMethod  any more.  But would not even call this if it is present. 
This seams to be reasonable for all current components but not for MaterialLayout.
The above mentioned  work around  -use a single instance of MaterialLayout-  is not easy to archive in our project.

**Comment by Garbee** [comment]
Downgrading even on layout should work now. We simply forgot to close the bug here.

However, do remember completely destroying and rebuilding the Layout is not supported and may cause UX problems.

**Comment by hr-117** [comment]
Thx for your response. 
But I'm still a little bit confused. (Downgrading should work, but destroying is not supported?)
According my (perhaps not complete  tests) rebuild the layout dos work fine. The only reason for leaking memory are the above mentioned  (event) listeners. This will prevent GC the "old DOM".   
In 1.1.2 this listener are: 
addListener for MediaQueryList
and window.addEventListener for 'pageshow' and 'resize'.
The initial issue was:
> The Layout component doesn't have a downgrade function to remove the dom elements and events...

So this is closed not because the initial issue is fixed but because it is not and will not be supported? 

But any way if deleting the element with  MaterialLayout is not support, perhaps this should be mentioned in documentation.

Only to put this on record: 
MDL is a really great library, it does what it should and work with lot different  approaches to build an UX.

**Comment by Garbee** [comment]
MDL is geared towards *stateless sites* with 1.x. Destroying the entire layout is not something that was thought about during the initial build of the layout component. It may bind event listeners outside of the component itself which would be the source of the problem. I personally don't know since I haven't checked the code to be sure.

With 2.x we are looking into removing that barrier and making things far more expansive in different contexts. However, 1.x has an extremely complicated layout system and we can't feasibly go back and make sure this building process is supported. Since that could in turn create backwards compatibility issues if not thought out thoroughly as to what other code may exist in the wild.
