### ISSUE TITLE
Autocheck checkboxes when the row has been clicked. 

### ISSUE THREAD

**Issue by mustafa-x** [google/material-design-lite#1388]
This is more of a behavioural suggestion perhaps, that if there is a checkbox on a row, that any part of that row could be clickable to check and uncheck the checkbox. Im not sure if this being a standard feature out of the box would be desired but having that as a optional class could be handy for designers who are not great at JS.

Thinking aloud, this configurable option could perhaps offer the ability to trigger other functions. For example if the checkbox / button has a destructive action (a delete button). Clicking it could trigger a message / modal etc.

The table I am thinking of is here : http://www.getmdl.io/components/index.html#tables-section

**Comment by Garbee** [comment]
This isn't going to mesh well with other functions. You could say, have "click to edit" functionality within the table  (also defined in Material Design.)

Probably best functionality is left as-is. Checkboxes are a clear action to select the row. Handling clicks  anywhere by default could lead to confusion and mis-selections. You are free to implement full-row selection if you want using custom code.

**Comment by mustafa-x** [comment]
Fair enough the only slight concern/question I would have here is then there is a rollover state on the row (background colour changes) which can indicate to the user that this is clickable / interactive. Unless the usecase for having the background colour to change is to be able to read a specific row, i.e highlighting it.

**Comment by Garbee** [comment]
The hover effect isn't clearly defined as to why it exists. However, there could be multiple reasons to click within a row (such as in-line editing functionality.) Making sure those are handled properly while still doing a row check  can be troublesome (since within developers custom code they would need to stop bubbling which *could* be problematic on its own.)

I'd say the hover highlight is more for legibility and providing focus to the person reading the content.

**Comment by mustafa-x** [comment]
That makes perfect sense.

**Comment by Garbee** [comment]
We are deprecating any JS for data tables that we maintain. Fulfilling this is up to user-land implementations to support.
