### ISSUE TITLE
angular material vs material design lite

### ISSUE THREAD

**Issue by ysfjwd** [google/material-design-lite#1390]
while having a ***material-design-lite*** project for static sites/older browser makes perfectly sense, the naming conventions for css is a little different i.e.  i.e. ***angular material*** uses ```md-card``` while material design lite ```mdl-card``` with a slightly different css structure. 

I am more intrigued in the difference in naming convention, as the scss for the two projects could have been merged, making us hoarders a little easier to consume these awesome libraries. Coming from angular material, its not just simple consume, there is a learning curve involved. 

Just curious in knowing about the design decisions taken for different approaches as per scss is concerned.

**Comment by surma** [comment]
Hey @ysfjwd, I can’t quite tell from your question, but Angular Material is completely unrelated to MDL and AM is not by Google. We did not consider any other MD implementation before starting MDL because we wanted to start fresh and not carry any technical debt so we can try and stay lightweight (the “L” in MDL). I’m not saying we achieved that 100%, but that was the reasoning.

There’s always a learning curve when adopting a new library/toolkit/framework, and the larger it is and the more it tries to do, the steeper that curve will be. [As I said in another comment](https://github.com/google/material-design-lite/issues/1175#issuecomment-123865305), we are purposely limiting ourselves to static content to flatten the curve at least a little. But you will still have to learn.

Even though I have never used Angular Material extensively, I fear the underlying technologies would have gotten us into deep trouble if we had tried to keep the CSS naming equivalent or similar.

**Comment by ysfjwd** [comment]
@surma thanks for the reasoning and not carrying technical debt.

however your remark that AM is not Google was a :open_mouth: moment for me. Angular is by google, AM is hosted at https://material.angularjs.org/ <-- a subdomain of angular implies that work done on AM is being done by core team at AngularJS or atelast some collaboration is there. Not really pointing any fingers or being rude (though i have a tendency of rubbing people the wrong way), but apologies in advance if you are offended.

Anyways, the reasoning that keeping the project removes the technical debt from other project makes perfect sense.

**Comment by surma** [comment]
Haha, no, no offense taken at all. The question was totally valid, so no worries here. This might also be helpful to others in the future :)

**Comment by surma** [comment]
@ysfjwd I stand corrected! AM *is* supported by Google. So you were right. However, the original justification still applies :) Sorry about the confusion!

**Comment by ysfjwd** [comment]
:smile:

**Comment by dimirc** [comment]
> however your remark that AM is not Google was a :open_mouth: moment for me. 

:+1:
