### ISSUE TITLE
Card Supporting text has the wrong width

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1396]
The card supporting text has a width of 90%. But it should take the full width.
<img width="1073" alt="screen shot 2015-08-14 at 7 28 29 pm" src="https://cloud.githubusercontent.com/assets/1972567/9286102/658b106a-42bb-11e5-9b0c-694941e8219a.png">
spec:
<img width="807" alt="screen shot 2015-08-14 at 7 29 59 pm" src="https://cloud.githubusercontent.com/assets/1972567/9286106/6c263ea4-42bb-11e5-95f6-db95b0ec8634.png">

**Comment by vinay20045** [comment]
@Garbee I'm using mdl in one of my projects and have fixed this and tested it on Desktop as well as mobile. Since this is my first commit, if you can please look at it once [on my fork](https://github.com/vinay20045/material-design-lite/commit/9b84c438cf71099fd27443e98f6e622882214125), and see if it's ok, I will submit a proper pull request.

**Comment by Garbee** [comment]
The change is right, but I currently consider changing the width a BC break since the 90% could be expected by developers in their projects (especially if they have automated visual test suites.) Right now we aren't focusing on V2 things since we still have V1.1 to get out plus patches to that.

cc @sgomes @addyosmani @surma - Any thoughts on whether we should consider width changing a BC break in this case? If we want to go ahead and do it in 1.1 then we can accept a PR for this in master now.

**Comment by sgomes** [comment]
@Garbee: Probably best to play it safe and keep it out of 1.1, since it may break styling for some people. Let's leave the issue open to keep track of this, though.

Thanks for the find, @tleunen!

**Comment by leemason** [comment]
i too came across this, and unfortunatley just removing the 90% width isnt a full fix. The `box-sizing` property of the div also needs to be set to `border-box`.

**Comment by sgomes** [comment]
Fixed in `master`. Since this is a potentially breaking change, it won't appear in the 1.1 branch, but 2.0 will have the fix.
