### ISSUE TITLE
Template - Blog - bg.jpg Background image is over 1 MB

### ISSUE THREAD

**Issue by ckashby** [google/material-design-lite#1403]
MDL 1.0.2 
All Browsers and phones.

The Blog template is described as...

"A mobile focused responsive template"

However the bg.jpg background image is over 1 MB in size.
The jpg also seems to be 2880 x 2252

i suggest you make it both smaller in size and much smaller in file size.

Lovin MDL

**Comment by Garbee** [comment]
The templates are just good examples of what can be done. They shouldn't be taken and used verbatim. Developers need to optimize their sites based on their performance goals.

Closing since the templates are examples of builds and we shouldn't need to focus internally on making them as optimized as possible.

**Comment by surma** [comment]
@ckashby As Garbee said, we can’t allocate the time to make optimizations of demos/templates when we have actual bugs to work on. At least not with a high priority. However, I feel like we should be leading with a good example in terms of mobile and this an oversight spelling the opposite. 

So Imma snatch this issue and give the background image a `srcset` or something :wink:
