### ISSUE TITLE
Tooltips are clipped on card boundaries

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/material-design-lite#1407]
If tooltips overflow the edge of a card, they are truncated. I think it would be better for them to overhang the card, if they are otherwise visible.

![screen shot 2015-08-17 at 14 01 41](https://cloud.githubusercontent.com/assets/51244/9305398/0c498bb4-44e9-11e5-9314-1d7608abd7ac.png)

**Comment by addyosmani** [comment]
Imo, overhanging would make better sense here. We should probably get UX input on the correct behaviour just to be sure though. To the best of my knowledge this isn't well defined in the spec atm.

**Comment by Garbee** [comment]
I think this probably has to do with the overflow hidden applied to cards.

Overall, I'd personally like to see if we couldn't get tooltips to detect boundaries and re-position accordingly so they fit within the boundary. Overflowing the card for tooltips would seem odd when nothing else would do that.

**Comment by tleunen** [comment]
Yes it's because of the overflow hidden. But I think we should keep this behavior.
But I would not re-position the tooltip in this context. Instead I'd make it appear on top of the card.
Some other elements like the DropDown menu would also need to be displayed like that. So the tooltip won't be the only element in this situation ;)

**Comment by jabbett** [comment]
Any recommended CSS hack in the meantime?

**Comment by KristerV** [comment]
```
.mdl-card {
    overflow: visible;
    z-index: auto;
}
```
Seems to do the trick just fine. Not sure why the card needs it's z-index reset. may cause problems later, we'll see.

In my case it's the menu and the menu expands through the bottom - can't be fixed with autopositioning. The menu just doesn't fit in my card.
![screenshot_2015-10-13_16-24-44](https://cloud.githubusercontent.com/assets/2750622/10455920/efe60c76-71c6-11e5-8fab-f050a379b9b8.png)

**Comment by sgomes** [comment]
Keeping this behaviour, for backwards compatibility. Setting a `overflow: visible` override should be an easy fix.
