### ISSUE TITLE
Vertical down menu only partially visible with waterfall header

### ISSUE THREAD

**Issue by jalajc** [google/material-design-lite#1444]
I am incorporating vertical menu (right-down) with a waterfall based header.

Menu is only partially visible (till the header row, not visible on content area).
I am attaching codepen for review: http://codepen.io/anon/pen/pJXbOg

Also, one strange thing I noticed: when height of window size is too low... the menu appears. (try dragging the view frame on codepen up and down to see this strange behavior).

Thanks,

**Comment by Garbee** [comment]
This is because of the hidden overflow rule against the layout header. I recall it being brought up before but am having trouble locating the old bug.

> Also, one strange thing I noticed:

Please keep issues restricted to a single issue, that helps keep things more actionable. However since we are here, I am unable to replicate this issue. Please file a new issue just for this with its own reproduction steps and example if it is still a problem.

**Comment by jalajc** [comment]
Hi Garbee, Thanks for the update.

Sorry for being not so clear. That strange thing reported is NOT a
different issue. Its just add to behavior of menu which has problem.

The *partially *visible menu in waterfall header appears *completely* when
web page window height is small enough (technically, less than menu height).

**Comment by Garbee** [comment]
This is an issue with the header overflow being set to none. You need to manually override in 1.x since we can't change it due to BC concerns. In V2, overflow is removed here so menus should work just fine.
