### ISSUE TITLE
unwanted secon scroll bar over img (on chrome v44)

### ISSUE THREAD

**Issue by dengere** [google/material-design-lite#1458]
IE 10 ok but chrome v:44 display unwanted second scroll bar when mouse over. 
for reprsent issue;
 left any img (it should be more than with 900px) on your "blog entry sample" page and over mouse when mouse over image chrome show two scroll bar. and page move left side. 
or you can see what happend on my blog page. it is ghost implementation by me. based on your blog template.
http://www.nuriyilmaz.net 

go any blog post page and over any image..
thanks.

**Comment by surma** [comment]
Hey @dengere,

I looked at your linked page with Chrome 44 and don’t have any scrollbars. Neither on the landing page nor on the page of an individual blog posts. Hovering doesn’t trigger a scrollbar either.

What OS are you using? Are you on the newest version of MDL (1.0.4)?

**Comment by Bound3R** [comment]
@dengere I only found this:

![image](https://cloud.githubusercontent.com/assets/5579520/9443538/304116b4-4a47-11e5-87c3-f02fd79d295b.png)

respect that happens I think that not has to do with the Chrome version, maybe js functionality or render (since it only happens to me when I try to scroll very fast).

**Comment by dengere** [comment]
hi @surma  @Bound3R 21 inch monitor has no issue. notebook 13.8 inch has issue. 
i removed all of my personel js and css and represent same issue on 13.8 inch monitor.

operating system windows 8.0, and lates version mdl.

**Comment by sgomes** [comment]
Any chance you could get us a codepen that isolates the issue, @dengere?

**Comment by Bound3R** [comment]
yeah @dengere you can isolate it in Codepen, which I found was a bug quite rare, but the render . while you have a problem with two scroll, the only thing I can think is maybe the Fixed header but I do not see you use it .

**Comment by dengere** [comment]
hello go to page http://www.getmdl.io/templates/index.html
while you over any image second scroll display also.. do 
!
[untitled](https://cloud.githubusercontent.com/assets/5771761/9599770/34e3d112-509f-11e5-919e-d6e7b42e44f3.png)
you need codepen isolation already?

**Comment by Garbee** [comment]
Unable to replicate with Chrome Version 46.0.2490.6 dev (64-bit). Could be an issue in the engine already fixed.

**Comment by dengere** [comment]
@Garbee yes! :+1:
updated my chrome to version: 44.0.2403.157 m  (32 bit) and no issue.

**Comment by chris-verclytte** [comment]
I had the same problem here and found by analyzing the page profile that it was due to an "over" function inside Chrome engine. 
This function checks if a "data-pin-nopin" attribute is present on img element then a quick fix is to put a data-pin-nopin="any-value" attribute on the img element. It will avoid Chrome to execute this over function on the image. 

My environment: latest Chrome version (at the moment 51.0.2704.103), windows, 17.3" screen and material design library.

I think this is more a problem with Chrome itself so I am going to publish an issue on Chrome tracker.

**Comment by myyellowshoe** [comment]
Experienced this same issue with Version 60.0.3112.113 (Official Build) (64-bit).
data-pin-nopin="any-value" does fix the issue though. Thanks @chris-verclytte
