### ISSUE TITLE
button useless class

### ISSUE THREAD

**Issue by Bound3R** [google/material-design-lite#1469]
Hi, I was working on buttons and found the class modifier `mdl-button--colored`, but I see functionality as does the similarly as the class `mdl-button--primary`.

eg:
http://codepen.io/Bound3R/pen/QbeJjZ

**Comment by sgomes** [comment]
They have slightly different semantics; `mdl-button--colored` picks the right colour based on the type of button: it will pick the primary colour for a flat or raised button, and the accent colour for a FAB, for example.

`mdl-button--primary` will always pick the primary colour, though; that's how you could for example get a FAB with the primary instead of the accent.

Hope this helps!

**Comment by surma** [comment]
Is this something we want to clarify in the docs? I can see how easily you could get confused by these.

**Comment by sgomes** [comment]
Not quite sure how we can make it much clearer without a lengthy explanation, but I'll take a stab at it.

**Comment by Bound3R** [comment]
sorry for the inconvenience, I now understand, and if you think appropriate to review the documentation of the buttons can be confusing.

**Comment by sgomes** [comment]
No worries, added :)
