### ISSUE TITLE
Different version of material.css on mdl.io and /master ?

### ISSUE THREAD

**Issue by ManasN** [google/material-design-lite#1473]
Well, here is the thing :
Left one is from master(after building the project from current master.) and right one is downloaded from (https://storage.googleapis.com/code.getmdl.io/1.0.4/material.css )
![image](https://cloud.githubusercontent.com/assets/9447030/9491902/72866932-4c10-11e5-9cf5-24329459b537.png)

Which one is latest and which one is preferred? I've put like 2 or 3 hours on the offset thing.

Also, both versions are same. 1.0.4 as per the doc headers .

**Comment by addyosmani** [comment]
The version of MDL in master is our work-in-progress for 1.1 per our [release notes](https://github.com/google/material-design-lite/releases/tag/v1.0.3) and we expect it to be a little further ahead :) 

This involves a slightly larger set of changes than were found in the 1.0.4 release.  1.0.4's release can be found in the release branch if you need a branch for tracking. Otherwise updates to the 1.0.x line are being made in the [mdl-1.0](https://github.com/google/material-design-lite/tree/mdl-1.0) branch.

**Comment by ManasN** [comment]
Addy! :) Glad you replied ! I've been watching your youtube videos and various talks a lots since last year and you were the guy to convince me to switch to this modern side of front-end web development. Kudos :)) Great framework !
