### ISSUE TITLE
Conflicts with external JS/CSS files

### ISSUE THREAD

**Issue by activatedgeek** [google/material-design-lite#1513]
I have the following includes setup given in order(will be stripping down dependencies later):
```html
<link href="/assets/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="/assets/vendor/material-design-lite/material.min.css" rel="stylesheet">
```

```html
<script src="/assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/assets/vendor/material-design-lite/material.min.js"></script>
```

This is giving errors in the behavior of MDL  Text Field component.

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/3909933/9576989/cddbfd22-4ffa-11e5-8deb-bb91302782af.gif)

Two issues can be observed here:
* The focus underline seems shifted.
* On losing focus, the floating text label disappears but in the documentation it stays on input. (Solved)

The first issue seems to be due to the `Bootstrap` CSS file. I am unable to figure out the second. Can somebody help me work around this?

**UPDATE**: Issue 2 solved by some manual intervention.

**Comment by surma** [comment]
@activatedgeek Could you do us a favor and whip up a codepen that reproduces the issue?

**Comment by activatedgeek** [comment]
@surma Hey, check the reproducible code [here](http://codepen.io/activatedgeek/pen/JYjREN)

**Comment by surma** [comment]
@activatedgeek Yup, this is definitely due to bootstraps styling. 

They apply a `margin-bottom: 5px` to `<label>`, which is where the offset is coming from. These are issues you have to resolve with manual styles, nothing we can do about that. 

If you need help with that, please head over to StackOverflow and use the `material-design-lite` tag. The GH issue tracker is for bugs in MDL only.

**Comment by activatedgeek** [comment]
Thanks! :+1:
