### ISSUE TITLE
Progress component SVG deprecation warning - Chrome

### ISSUE THREAD

**Issue by puranjayjain** [google/material-design-lite#1516]
SVG's SMIL animations (`<animate>`, `<set>`, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

**Comment by hebbet** [comment]
can you provide an example where that happens?

**Comment by Garbee** [comment]
When using progress most likely.

We know of the deprecation warning and as I recall there is no alternative to what we are doing with pure CSS animations.

Further, deprecation will take a *very* long time to be rolled out and then removed. No real worry about SVG animations being used right now.

cc @surma and @sgomes to see what they want to do with this issue.

**Comment by surma** [comment]
Thanks for the warning, @puranjayjain :)
The current progressbar only uses SMIL in blink properly anyways, since most other browsers handle masks differently or not at all.

Realistically, though, I don’t see any work being done on this before v2 and that will probably be a proper rewrite anyways. I’d vote for closing this.

**Comment by Garbee** [comment]
Closing on up based on previous comment.

Thanks!
