### ISSUE TITLE
Templates, ANDROID.COM MDL SKIN Index.html file

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#1605]
`<script src="../../material.min.js"></script>` could be removed from line 327 and `<script src="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.min.js"></script>` placed in the `<head>`.

Also, line 30 `<link rel="stylesheet" href="$$hosted_libs_prefix$$/$$version$$/material.min.css">` replaced with `<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.css">`

**Comment by surma** [comment]
Hey @rhroyston.

Both of the things you are mentioning are intentional:

* Having the `<script>` tag at the end of the `<body>` is to not block the parser (because it would stop until the JS has been executed) and also to ensure that the entire DOM has been parsed so that the upgrade routine works.
* All the templates use `$$hosted_libs_prefix$$/$$version$$` so you can automatically inject your local MDL build to test for regressions.
