### ISSUE TITLE
Redraw range line on value change

### ISSUE THREAD

**Issue by DennisSnijder** [google/material-design-lite#1608]
when i try to set a range value with jQuery the line in the range slider doesnt redraw.

**Comment by Garbee** [comment]
You need to call `MaterialSlider.change(value)` against the slider node instead of changing the input value directly.

**Comment by Garbee** [comment]
Also for future reference, please use StackOverflow for support. Using the `material-design-lite` and any other applicable tags to get the best support in implementing MDL in projects.

**Comment by sgomes** [comment]
For a little extra clarification, this happens because programmatic changes to HTML elements don't trigger events, and therefore the component is unaware that its value changed.

Because of this, we provide an API for elements, which is accessed the way @Garbee described. See https://jsfiddle.net/Lzdez4s2/1/ for a similar situation.

**Comment by DennisSnijder** [comment]
wow thanks for the great and quick response!
