### ISSUE TITLE
MDL single line text fields route the client to url?# on enter key

### ISSUE THREAD

**Issue by noah2828** [google/material-design-lite#1628]
This happens when ever you hit the enter key in a single line text field and causes the browser to load that URL. If ?# is already at the end of the URL the text field works as it should and does not reload the page.

An example of the problem can be seen [in the MDL text fields example](http://www.getmdl.io/components/index.html#textfields-section) where hiting enter reloads the page back out of the text fields example route. This error make using MDL text fields in logins require the work around of adding ?# to the end of the effected routes.

**Comment by surma** [comment]
The reload on enter only happens because the textfields are in a `<form>`. It is standard browser behavior to send a form on enter if there’s only one textfield. You can either change the `<form>`’s action or cancel the sending via a simple JavaScript. In any case, this is not a MDL bug. We are merely styling an input field.

However, I do agree that the demo should probably do one of the things that I just mentioned, i.e. not sending the form on enter because it doesn’t make any sense in that context.

**Comment by noah2828** [comment]
ok thanks.
Is there a way to prevent the action that is cleaner than 

var URL = document.URL;
document.getElementById("id").action = URL;

**Comment by surma** [comment]
Well, you don’t need to put the textfield in a form, if that is an option.

Or you could add `onsubmit="return false"` to the form like [here](https://codepen.io/surma/pen/gawKGL).
