### ISSUE TITLE
When scrolling away the header, the page body should not jump around 

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#1658]
From @pbakaus 

"Right now, when loading a page such as https://material-dot-web-central.appspot.com/web/tools/setup/workspace/setup-buildtools, the page does a jump when you scroll down and it's very irritating. Let's solve this without jumpy jump jump."

This is in respect to the header in Web Fundamentals if you scroll down slowly, when the subheading collapses the body moves up.

I don't know what the desired behaviour would be for this. It might be solved in 2.0 if we introduce less magic in terms of structure of the page.

**Comment by surma** [comment]
The waterfall header is usually animated. Not sure how that got lost. It would make it sufficiently un-jumpy, I guess.

**Comment by gauntface** [comment]
It could be that I'm doing something wrong on WF.

**Comment by gauntface** [comment]
More feedback on this: 
"Scrolling the page, the header quickly jumps to its smaller fixed position. It doesn't feel right and isn't the MD spec. Instead, the bar should ease/transition to it's final state.

Something like:
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/index.html"

**Comment by surma** [comment]
Valid point. I’ll leave this open for the layout rework

**Comment by felipe-calvo** [comment]
I can't load the initial webpage that showed the problem: 
https://material-dot-web-central.appspot.com/web/tools/setup/workspace/setup-buildtools

So I want to ask if the problem can be seen in this template page http://www.getmdl.io/templates/android-dot-com/index.html
If you load the page and quickly scroll down, at some point the page will jump to the top.
It's the unique template with this behaviour -I suspect- because is the unique template demo with a drawer,

I believe I'm currently experimenting the same problem in a website I'm working in (I'd like to submit it for the showcase, though), and exploring over some sites submited for showcase I can exactly see the issue in the following threads:
@ealsur https://github.com/google/material-design-lite/issues/1389#issue-100816129
@daretodave https://github.com/google/material-design-lite/issues/1389#issue-100816129
@czenisek https://github.com/google/material-design-lite/issues/1860#issuecomment-155252083

Not sure, I'm not an expert developer, but seems that the "jump" happens when the elements in the DOM are "upgraded".

I'd be glad to provide more details or feedback if neccesary. Thanks!

**Comment by Garbee** [comment]
It does happen when upgrade occurs, because that is when logic is done moving nodes around and creating new containers and such.

There is nothing that can be done about this until the 2.x refactor of Layout since it fundamentally changes how the component operates. It is one of the many in a long list of known 1.x Layout problems.

**Comment by johnam** [comment]
Are there any suggested solutions to the 'jumping to the top' issue / is there a timeline for 2.x release?

Currently I'm obscuring the page on load and showing a spinner and revealing the page upon 'mdl-componentupgraded' to prevent users from scrolling before the layout is upgraded. This makes it seem to the user that the page is taking much longer to load than it really does - not user friendly.

**Comment by Garbee** [comment]
No timeline on V2 and no recommended solutions to hotfix 1.x with.

**Comment by Garbee** [comment]
We are working on a complete V2 rewrite currently. Closing this issue out since Layout is being broken down and simplified in this effort so this issue should naturally get solved.
