### ISSUE TITLE
Roboto is not the font of body

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1692]
Hi,

I wonder if it's a bug or not but Roboto is not the font of the body. Helvetica is the font of the body.

**Comment by addyosmani** [comment]
This was intentional. For web performance reasons, we don't use rely on the Roboto Web Font for body text as you ideally want users to be able to see and read that content without experiencing delays or FOUT. We do offer classes that let you opt-in to using Roboto as the body font, but by default suggest folks don't do this unless absolutely necessary.
