### ISSUE TITLE
Hire the Materializecss Team

### ISSUE THREAD

**Issue by rebelvc** [google/material-design-lite#1698]
For several projects, my developer ask to use https://github.com/Dogfalo/materialize because it has more components. The materialize team seem to also be doing good work. The maintainers are young lads who are asking for donation. Why not just pay them? 

"A house divided cannot stand" - Abraham Lincoln

**Comment by addyosmani** [comment]
MDL is an open-source project so..no budget :) While we totally acknowledge that there are other Material component projects out there (and I'm sure some are awesome), we have slightly different goals. Everything we do is closely aligned and reviewed with the Material Design team, we ship components when a spec is sufficiently fleshed out rather than (in our opinion) immature and we're trying to stay lean where possible over shipping too many pieces. We're always more than happy to have community contributions from any other group of open-sourcers though.
