### ISSUE TITLE
Changes icon mdl-layout__drawer

### ISSUE THREAD

**Issue by coderjomblo** [google/material-design-lite#1816]
Hello, I learn about this framework without internet connection so the icons not display. But, I want to change the icons with materialdesignicons. So how I can change the icons mdl-layout__drawer with mdi mdi-list. Thank you.

**Comment by Garbee** [comment]
This is not supported currently. If you want to change the icon it is up to you to find your own way of doing so. StackOverflow is the best place for implementation help.

In V2 we are looking to heavily reduce the amount of automatically generated markup, so it should be possible much more easily when that comes around. Until then, we don't support changing the icon since anything else isn't following the specification.
