### ISSUE TITLE
Hamburger menu icon

### ISSUE THREAD

**Issue by RocketUnlimited** [google/material-design-lite#1859]
Icon won't show up with latest Samsung Galaxy S6 stock browser.

Stock browser:
http://imgur.com/iJAdRNp

Chrome:
http://imgur.com/h68GU4i

**Comment by mitchelkuijpers** [comment]
This also seems to happen on the Galaxy S6

**Comment by Garbee** [comment]
iirc this is due to our use of ligatures.

We should try updating the template code to not use `menu` for the content but the codepoint `e5d2` value.

Assigning to @surma to peek at it more. They have done most of the work in Layout iirc and should have access to plenty of devices to test the fix against.

**Comment by surma** [comment]
Will look at this once I am back in London :)

**Comment by MarcosGalaviz** [comment]
Thans I am going to be waiting for this, thanks for your help, very nice work.
