### ISSUE TITLE
Tab indicator doesn't follow MD guidance

### ISSUE THREAD

**Issue by virtyaluk** [google/material-design-lite#1880]
I noticed that once you click on a tab to activate it, the indicator "jumps" to active tab, not "slides".
The guidance ["says"](https://www.google.com/design/spec/components/tabs.html#tabs-specs) that indicator must slide its way to the active tab.
![165d18afa4179800221ee82bd9643d67](https://cloud.githubusercontent.com/assets/795984/11138954/e212e3c6-89d1-11e5-84f8-ba393e01cf2d.gif)
Probably main reason of that behavior is that MDL uses `:after` pseudo-element on each tab to represent indicator while using `:after` on the main tab element may help to reach the right result.

**Comment by Garbee** [comment]
#1834 is open to try and address this. However, the spec does not state "must" in any form from what we can tell. It in fact specifically says:

> Note: Implementations of this component may vary by platform.

About the animation. Closing this issue out since we don't seem to be in direct violation of any requirements, but simply an encouragement. If the other PR succeeds, then we will have a tab animation work like the spec states for Android. Otherwise, we will just have a variant which is perfectly acceptable by the spec.
