### ISSUE TITLE
Drawer Obfuscator Isn't in Sync with Drawer

### ISSUE THREAD

**Issue by johnsonium** [google/material-design-lite#1883]
I built an application against MDL 1.0.5 with a drawer containing three anchors, each that shows a div while hiding others via an onclick event. In the same handler I also remove the 'is-visible' class of the drawer to hide it. It worked fine in 1.0.5. When you click on any link the appropriate div is displayed, the drawer hides, and the obfuscator is hidden as well.

When I switched to 1.0.6 the behavior changed. When you click on the hamburger menu, the drawer appears and the obfuscator also appears but when you click on a link the drawer is hidden but the obfuscator remains. If you click on the hamburger again, the drawer appears but now the obfuscator disappears. It cycles this way with each click, sometimes achieving the proper state but most of the time remaining out of sync.

I created a simple example here: http://jsbin.com/tajedahexi/edit?html,output

Reproduction Steps:

1. Click on the hamburger menu
2. Click on any of the three links in the drawer
3. Observe the drawer disappearing but the obfuscator remaining
4. Click on the menu again
5. Observe the menu appearing but the obfuscator disappearing

**Comment by Garbee** [comment]
This seems like an issue with some custom code not functioning properly. Please ask on StackOverflow using the `material-design-lite` tag along with any other appropriate tags. This tracker is for problems specific to code provided by MDL. Once you are creating custom logic changing what we do, we are unable to properly support it.

**Comment by johnsonium** [comment]
It's not custom code. I'm simply removing the 'is-visible' class from the drawer. Did you not look at my example? If this is not correct what is the proper way to close the drawer or do you only support closing the drawer by clicking outside of it? If so, that seems severely limiting.

**Comment by Garbee** [comment]
Currently there is no public method for toggling the drawer state. I did check the code, and what is in the "JavaScript" section is clearly code not provided by MDL. You can check the [layout source](https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L164) to see exactly what is required for toggling the drawer state. We are unable to handle things the way you are expecting since that would require observers.

We could introduce a public method for toggling the drawer state, however I am worried about the implications that may have with people building things not to MD specification. Assigning to @surma to take a look at that since he did the current Layout component. If he agrees that a public method should be made, then we can add this to 1.1.

**Comment by Garbee** [comment]
Just asked Surma in person, no specific reason by the spec this method is private. I'll do the update when I'm back home on my primary machine for making the method public.

**Comment by hcsdrose** [comment]
@johnsonium Here is a fix for the issue. Just change hideDrawer() to toggle_drawer().

function toggle_drawer() {
	var drawer = document.getElementsByClassName('mdl-layout__drawer')[0];
	var drawer_obfuscator = document.getElementsByClassName('mdl-layout__obfuscator')[0];
	drawer.classList.toggle("is-visible");
	drawer_obfuscator.classList.toggle("is-visible");
}

**Comment by johnsonium** [comment]
Thanks for the workaround. I had already implemented something similar to allow me to move to MDL 1.06. I was more interested in supported way of closing the drawer. It appears that they are adding that to version 1.1.
