### ISSUE TITLE
Spinner - can't delete entirely.

### ISSUE THREAD

**Issue by aPoCoMiLogin** [google/material-design-lite#1919]
Is there any purpose that I can't downgrade spinner? Even if I remove all bound events (eg jquery.remove), there is still some reference to that elements, which is keeping all the spinners in memory, marked as detached.

Here is gist: https://gist.github.com/aPoCoMiLogin/138f5c2cb77423b20781

and here are screenshot from chrome developer tools:

![zrzut ekranu z 2015-11-28 11 06 54](https://cloud.githubusercontent.com/assets/493369/11451279/6f29d4aa-95c0-11e5-80df-35b787e0ecc4.png)

tested on chrome 46.0.2490.86 (64-bit) (ubuntu).

**Comment by Garbee** [comment]
No reason, just haven't gotten around to building the downgrade method yet. I'm working on some deep mods to the component handler which should make this not relevant. Whether that will land in 1.1 is still unknown since I hit a logic snag. Marking this for 1.1 since either the CH changes get merged or we need a downgrade method here if it doesn't.

**Comment by samccone** [comment]
odd.. I thought would have taken care of this https://github.com/google/material-design-lite/pull/1805

**Comment by Garbee** [comment]
@samccone It was never merged. Because, we *shouldn't* do empty downgrades. Since the meaning is you could then re-upgrade it without side-effects. The downgrade should kill any dynamically created nodes and remove event listeners. All  that downgrade would have done was allowed the removal of the internal reference, which is good only when deleting a component outright.

**Comment by Garbee** [comment]
Fixed by #2009
