### ISSUE TITLE
mdl-layout__obfuscator in v1.0.6

### ISSUE THREAD

**Issue by ndaidong** [google/material-design-lite#1921]
Hi there,

In v1.0.6, the side bar (mdl-layout__drawer) no longer work for me as expected. Issue seems to relate to ""mdl-layout__obfuscator" element.

Please take a look:

https://youtu.be/VxltTTJIOpk

Regards,
Dong

**Comment by surma** [comment]
Thanks for the video with your issue, @ndaidong. I *think* we encountered that issue and fixed it in master for 1.1. @sgomes Can you confirm?

**Comment by sgomes** [comment]
Thanks for the video, @ndaidong! @surma There aren't any bugs that we've fixed for 1.1, no. As far as I know, there are no known bugs with the drawer in 1.0.6.

This is likely happening because there were some minor changes to how the drawer works in 1.0.6, to work around some iOS bugs. In order to implement the fixes, we had to change both the JS and the CSS, so if you use the 1.0.6 CSS with the 1.0.5 JS, it won't work correctly.

Looking at the video, you only seem to be changing the CSS file, so I assume that's what's happening. Please try using the 1.0.6 JS with the 1.0.6 CSS and it should work correctly, but if not let me know and I'll look further into this!

**Comment by ndaidong** [comment]
Thank you @surma and @sgomes 

You guessed correctly, Sérgio. My issue relates to JS version. I've updated to  v1.0.6 both JS and CSS then it works for me now.
