### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by samih-dev** [google/material-design-lite#1998]
Hi all,
I'm using the following js version stored in google CDN:
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>

I read in the docs that the components will degrade gracefully for B-Grad(IE9) browsers, this is correct in the MDL site only, not in my testing using the text field component:
1. The label isn't hidden/moved when start typing
2. Creating a dynamic component raise an exception that could be shown in the browser console.

You can download and test from here: 
http://plnkr.co/edit/DoV0OtslDGQsNpuvYPFy?p=preview

Thanks!

**Comment by surma** [comment]
In IE9 your site will remain functional but with heavily distorted visuals, hence B grade. This is one of the artifacts. 

We are going to drop IE9 and IE10 support for v2 (seeing that [IE10 support ends in 31 days](http://meowni.ca/is-ie10-dead/)), so I will close this as a “won’t fix”. Sorry for the inconvenience.

**Comment by gmp26** [comment]
Just a note. We are now almost in 2019, and large sections of the National Health Service in the UK are still running IE9 on Windows 7. So no Material Design for them which is a shame.

As technologists we often overestimate how interested our users are in staying up to date.

**Comment by Garbee** [comment]
> As technologists we often overestimate how interested our users are in staying up to date.

This was a data driven decision. The cost of maintaining an A level experience in IE9 compared to how many global users are still on it wasn't really there. Yes, of course in some contexts you may be alternatively impacted based on the subset of that data you're targeting that something else makes sense. In that case, you need to use your data and make the best choice of tools to target it.

Simply because in some cases legacy browsers are the norm instead of the niche doesn't mean every other project around needs to also support them fully. Maintainers need to make the best decisions for their projects based on their goals. And developers assessing the various projects needs to chose the best one based on their needs and data.

If we could have everything we desired, then any project could easily support even browsers from the Netscape Navigator days and run perfectly fine while running equally as well in a modern browser. The platform evolves over time and legacy support can get complicated. So things eventually do need to be cut simply to keep projects and applications reasonably maintainable.
