### ISSUE TITLE
Latest MaterialLayout has some glitches 

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#2006]
1) toggleDrawer firstLink should not point just to "a" it should go to a.mdl-navigation__link
https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#l262
Reason: If you have a link in you title then it puts the focus on this link an not on the navigation

2) You have two drawToggleHander functions https://goo.gl/1rR6RR
Is this really something you want?

3) If the Drawer is open you put the focus on the Drawer-Button which is OK but now you can toggle the Drawer with ESC - this is a bit unusual... https://goo.gl/in1i4y + https://goo.gl/3F7ebH

**Comment by Garbee** [comment]
1) Targeting any first anchor found is fine, even if title. It is the first targetable anchor, so that seems perfectly valid. Any a11y reason in particular this shouldn't be the case?

2) Already fixed by @sgomes thankfully. I messed up the merge a bit.

3) The `esc` toggle only triggers when done to the drawer. So it should only close since in no other case would the drawer have focus. Any testcase where this isn't the case?

**Comment by Garbee** [comment]
ping.

If there is no clear cases here where problems exist we should close the issue up.
