### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by boubouhkarim** [google/material-design-lite#2022]
for text fields with html5 pattern validation, mld behave weirdly,
if an input is required it will show the error message automatically even before the user focus on the input.
in normal case the error message should appear if the user left the input blank after losing the focus.

**Comment by Garbee** [comment]
No, this is proper by HTML5. We are using the built in validation methods that function this way.

There is no intermediate state (yet) in browsers to work from. So we decided to deal with what HTML5 provides even if it goes against a part of the MD spec for simplicity over recreating validation handling and more sophisticated dirty-state checking ourselves.

**Comment by SonofNun15** [comment]
I'm assuming nothing has changed here since the behavior appears consistent nearly 4 years later... 

MDL is a great library, but it makes me sad that all of the validation errors are displayed before the user has even interacted with these fields. Would prefer if the errors were not displayed until the fields were touched. Anyone know if the HTML5 specification has changed?

**Comment by Garbee** [comment]
There is still no intermittent state specified and implemented. It has been kicked around as an idea though.

MDL is also no longer maintained. Check out Material Components for Web over at https://material.io for the project that MDL evolved into.
