### ISSUE TITLE
text-color-primary-inverse is documented but not defined

### ISSUE THREAD

**Issue by oddui** [google/material-design-lite#2082]
`$text-color-primary-inverse` and `$text-color-secondary-inverse` are [documented](https://github.com/google/material-design-lite/blob/62af49cd6538d2072fb6508472d7716157f7e514/src/_variables.scss#L115) but seem not defined.

**Comment by Garbee** [comment]
Looking over a blame real quick, it looks like those docs are from when the code as even over in Web Starter Kit. Simply got lost in an update along the line.

Just ignore the comments, they don't mean anything. Already fixed in the 2.0 mockup I'm working on which has a good likelyhood of being the new base. Not major enough to warrant fixing in 1.1 since it is just comments and no functionality is affected.
