### ISSUE TITLE
Investigate trimming down build size

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#300]
Today, we are ~155KB for minified CSS (~25KB gzipped) and could trim down. I'll investigate as it looks like we could have some wins if we re-examined how we're architecting our Sass.

**Comment by Garbee** [comment]
With V2 we are dropping the individual color and background color classes by default. This should save quite a bit of space on its own. As far as version one is concerned, things are set in stone at this point.

Let's re-address build size when V2 is getting closer to ready and see what we can do there since it will have a whole new setup on its own.

**Comment by sgomes** [comment]
@Garbee I don't think that dropping color classes in V2 has been decided yet. I for one would like to leave them in, as they make a designer's job much easier.

As you mention, though, there are some decisions we can make to bring down build size in V2 if we have to.
