### ISSUE TITLE
Review bower.json

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#329]
Update `bower.json` in root to reflect new deployment setup.

I would do it myself, but I don't use or know bower in any fashion.

**Comment by TrySound** [comment]
- dist folder shoudn't be ignored
- bower main should contain non-minified files.

**Comment by Garbee** [comment]
> dist folder shouldn't be ignored

For `.gitignore` it should be ignored, we are not tracking it in the primary repo. I don't see it being ignored in the bower.json file, so that shouldn't be a problem?

Maybe if we aren't tracking the output then the bower setup doesn't make any sense and we should just remove the file entirely?

**Comment by TrySound** [comment]
@Garbee Why not just add built files? I use bower for my builders. main-bower-files checks all main fields and returns all paths.

**Comment by Garbee** [comment]
Having the output files in the primary repo causes confusion for PRs which leads to more work need to maintain the project. We decided to not do that to keep the process for submitting a PR as straightforward as possible.

tbh I don't use bower at all, so I don't know how the tool works. Maybe we would need to create another branch/repo to handle the bower side of things that keeps track of the generated files.

**Comment by addyosmani** [comment]
We do have built files available for bower. 

`bower install material-design-lite`

![](http://i.imgur.com/wJPJTk3.png)

**Comment by addyosmani** [comment]
The way this setup works is using subtrees. When we cut a new release, we have scripts generate the build artifacts that are checked into a `release` branch and tagged. So, the 1.0.0 tag of MDL is used for Bower and npm - this contains built versions of the JS and CSS.

There's no reason to have to build anything unless you're looking to customise the source further.

**Comment by TrySound** [comment]
@addyosmani Thanks! But it still should contain non-minified files.

**Comment by addyosmani** [comment]
It does :) `material.js` and `material.css`. Are you asking why the full source isn't there?

**Comment by Garbee** [comment]
He means the main array in the [bower file](https://github.com/google/material-design-lite/blob/master/bower.json#L9) should be non-minified if I understand correctly.

**Comment by TrySound** [comment]
@Garbee Yes, I'm about it. Thanks!

**Comment by callumlocke** [comment]
@TrySound is correct: https://github.com/bower/bower.json-spec#main "Do not include minified files."

**Comment by johnny-bit** [comment]
Also, the bower spec says not only that files should not be minified, but that main files should be source files, and not pre-build ones.

**Comment by callumlocke** [comment]
That's weird, I didn't know that. If that was widely followed it would make Bower useless to people who want just to throw in a `<script>` or `<link>` tag without having to know about about the specific build requirements of each component.

**Comment by johnny-bit** [comment]
Before making it clear in specs, it was suggested to use main section for
all needed files and figure them out for wiredep. It was OK practice IMO,
but package creators were left to interpret that whatever they like.

Look how problem got resolved after maybe 3 years of discussion:
https://github.com/bower/bower/issues/935
https://github.com/bower/bower.json-spec/pull/43
https://github.com/bower/bower.json-spec/issues/47

Now this is not perfect, far from it, but it does IMO more good in the long
run. For example we have material-design-lite ;) If I wished to use this
with sass, gulp and wiredep then I'd get no scss. Why? because not only
files required to build css are not in main (where they can be forced in
with overrides) but they are outright ignored (stripped from package).
Now spec says something more like: have main point to whatever's needed to
build Your package and (somewhere in the future it will be well deined)
have dist files in files section. Generally whole main/files issue in bower
is problematic due to way of resolving but it should be stated years ago
that bower packages should NOT ignore sources. What way using overrides one
could get whatever needed from package :)

2015-07-10 19:52 GMT+02:00 Callum Locke <notifications@github.com>:

> That's weird, I didn't know that. If that was widely followed it would
> make Bower useless to people who want just to throw in a <script> or
> <link> tag without having to know about about the specific build
> requirements of each component.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/329#issuecomment-120477539>
> .
>



-- 
Pozdrawiam,
Hubert Kowalski

**Comment by surma** [comment]
I’m closing this I think we have found a good compromise and most people seem happy about the current state. If not, please ping :)
