### ISSUE TITLE
Material design Google components

### ISSUE THREAD

**Issue by AndreLGava** [google/material-design-lite#3525]
I was taking  a look into the https://www.google.com/design/spec/material-design/introduction.html and I found a lot of components there isn't in the framework yet, can someone explain me if they will be built? And when?

Thanks, it's already a success

**Comment by Garbee** [comment]
Component requests should be [appropriately labeled](https://github.com/google/material-design-lite/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+%22%5BComponent+Request%5D%22) in the title if people use the submission form in the README. Otherwise, they get tagged as feature request and you need to go digging a bit.

We are not aiming to provide 100% coverage of the specification. But instead bring developers the upper like 80% or so of what they will need to build most applications that come their way. This way developers have a solid foundation but are still open to build custom bits where needed. In turn, the provided components (because we are **not a framework**) stay minimal and lite. So people who don't need everything aren't weighed down by the excess stuff.

**Comment by mariusbutuc** [comment]
@AndreLGava and if it so happens that a given component that you are looking for falls into the remaining 20%, the guys here seem to be very helpful and welcoming of PRs.

**Comment by AndreLGava** [comment]
Yes, I see, im very thankfull about your work, all of you are great colaborating on this project, I just love to use as soon as possible all the components that are in the documentation, that would be really awesome, and I know that it will take a long time, we need to develop and test to many browsers. My doubt actually was arround if all the components in the documentation will be build or some not?

**Comment by Garbee** [comment]
> My doubt actually was arround if all the components in the documentation will be build, won't them?

As stated before, this is **not** the project's current goal. That will cause a bunch of bloat for the majority of projects using our components.

**Comment by AndreLGava** [comment]
thank you @Garbee , now I understood. I understand that it can't be so heavy, i just would love to get all of that
