### ISSUE TITLE
Scrollbars, scrollbars everywhere

### ISSUE THREAD

**Issue by ilyes4j** [google/material-design-lite#3609]
I don't know if this is a known issue, or if it is an issue in the first place. I have checked all open issues and didn't find anything on the subject.

When using mdl components (buttons, Cards, Loaders, Sliders...) directly inside a page, there is always unnecessary scroll-bars (horizontal and vertical) added to the embedding page. But when the said components are placed inside mdl layouts, they are displayed correctly without any unnecessary scroll-bars. For example, in the demo site http://getmdl.io/, all component samples (except for layouts) have scroll-bars at the page level.

Are mdl component meant  to be used inside mdl layouts only ?

**Comment by surma** [comment]
Can you give us a little info about your setup (OS version, browser version) and maybe give us a screenshot? The samples all look fine to me. But we know that we have a problem with scrollbars here and there.

**Comment by ilyes4j** [comment]
Thank you for your quick answer. I'm sorry, here is my setup : 
* OS : Windows 7
* Browsers tested : Chrome 47 (also IE 11 and Firefox 24)

# Test case 1
I opened http://getmdl.io/components/index.html#buttons-section and then clicked the first pen which I saved [here](http://codepen.io/ilyes4j/pen/YwEXBd?editors=110). Below is a screenshot of the resulting behaviour

![scrollbar_2](https://cloud.githubusercontent.com/assets/862308/12390723/e23c1e0e-bde2-11e5-939c-cd3d4da3ef29.png)

# Test case 2
I created another [pen](http://codepen.io/ilyes4j/pen/JGOdZp) which only contains a heading tag and the result is shown in the screenshot below

![scrollbar](https://cloud.githubusercontent.com/assets/862308/12390554/53f21488-bde1-11e5-9629-2e3671ca3a0b.png)

**Comment by Garbee** [comment]
Scollbars in the first button codepen are produced from the padding on the body added to the codepen. Remove the padding in the CSS of the codepen, boom, scollbars go away.

The more interesting example is the second one... still trying to track that one down.

**Comment by Garbee** [comment]
And just got the second one. Based on the top margin of the h1 element pushing the body down.

All-in-all, nothing we can really do about these two specific scenarios in my opinion. We would need a real-world example of where this is causing issues to have something actionable. The setups here are not in alignment with any MD spec guidance, so not something we targeted for usage in 1.x.

**Comment by ilyes4j** [comment]
@Garbee thank you for your explanation.

For the first example, yes, it is easy to achieve the same result without the side-effects. But, it is a bit confusing, as one might think that it is not supposed to look like that since the example is doing it that way.

As for the second example,to be honest, I can't think of serious real-world problem where this is problematic. But, if someone wants to put headings in a page where the content does not overflow, it might look a little untidy to see unnecessary scroll-bars. I'm gonna check the MD spec to see how it is supposed to be done.

**Comment by Garbee** [comment]
The components are not meant to be dropped into a blank page and just used directly. They should be implemented within some kind of layout system to view a page.

You're saying that examples without any layout are wonky. yes, this is true. However, they are effective  to demonstrate the components looks. That is what matters there. They then get applied within other page components to be used properly. Which, if all is done well would mean that this scrollbar issue is never seen. Since the components would scope the size properly.

This is kind-of like another issue that was brought up a few weeks ago. Where putting two switches onto a page directly and then clicking in **just** the right place would trigger the wrong switch. Due to the ripple container. While a technical problem yes, it entirely goes against the specifications recommendations that touch targets be 48px by 48px big minimum. That can't be enforced at the component switch level, since the switches should go within other components with their own space sizing.

This get fairly complicated  as to what should be applied where with MD. Unless there is clear guidance within the specification as to how things are done, we try to be as minimal as we can. Which then allows the maximum amount of interoperability between components as easily as can be done.

**Comment by ilyes4j** [comment]
It is fair to assume that there are some rules to stick to when dealing with components and that these components would work fine as long as their application meets the MD guidance.

Thank you for these explanations.
