### ISSUE TITLE
bower.json "main" add  "src/material-design-lite.scss"

### ISSUE THREAD

**Issue by dkebler** [google/material-design-lite#3611]
any objection to adding src/material-design-lite.scss to the "main" key in the bower.json file?

Currently must use a bower override in order to use MDL scss source in my build.

**Comment by surma** [comment]
I am not sure what the semantic meaning of the `main` field is, but `material.js` feels just as main to me as the CSS.

**Comment by Garbee** [comment]
I don't think we should worry about this right now. We should re-assess the package.json data with 2.x.

Also, ideally we would only include the raw sources over the compiled files if it is something we are really putting support  behind. Sass is currently more of a means-to-an-end that then got twisted into some wonky level of support.

**Comment by dkebler** [comment]
So you are saying that eventually MDL will not use/provide access to the sass source?  Good to know because in which case I'll opt out of using MDL.

**Comment by surma** [comment]
The SASS sources will still be in the repo, just not in the files provided via bower.

**Comment by Garbee** [comment]
Whatever we use for a preprocessing setup, the raw files will still be provided in the NPM package (bower, no idea on that one.) I'm simply saying we should not add them to the package information without having an actual level of support internally for using the source files. Right now, the sass pipeline isn't great and quite a bit of it needs to be refactored or removed. (Like a bunch of the typography mixins.)

Until we put a focus onto supporting preprocessors, it shouldn't be a main thing. Provided for those that know how to use it, otherwise stick to the compiled files.
