### ISSUE TITLE
Modals and html <select>

### ISSUE THREAD

**Issue by StanlieK** [google/material-design-lite#3730]
Can you add this two things please? Yours "framework" is super beautifl and I thanks for them, but these two things I want. Have You something like todos of this project where is these things? Thank you

**Comment by Garbee** [comment]
1) It isn't a  "framework" but a set of components built to MD specifications.

2) Please search existing issues first. There are already existing issues for these and even a PR about to land for one. If you find an issue you want to keep up with. There is a "subscribe" button in the right sidebar you can use to get updates on a specific issue.

Thanks for supporting the project. Things run smoother with fewer issues to manage and when the least amount of email is being thrown around.

Closing this out since existing issues already exist for the requested components.
