### ISSUE TITLE
MDL does not play nice with JS

### ISSUE THREAD

**Issue by Unforgiven-wanda** [google/material-design-lite#4048]
Hello,
Apparently, MDL consistently "destroys" (for lack of a better word) anything written in Javascript, making it impossible to work comfortably -or at all, with any plugin, be it vanilla js or JQuery. So far I've had issues with Waypoints - the pure JS and JQuery version, OnScreenJS, Gridster and Freewall and some others. It took me hours to figure out that the responsible was not poor coding on my part, but material.js. I cannot, for the life of me, figure out how or why it behaves this way, and I'd be eternally grateful if someone could shine some light on this very particular issue.

FYI, this isn't my first rodeo with a front-end framework. I fully understand that some libraries do not behave the expected way, but in this case, this is really pushing it a little, I think.

**Comment by surma** [comment]
Waypoint and OnScreenJS are mostly likely having problems because our layout component does not scroll on body but on the `.mdl-layout__content` element. This is our bad and will get fixed in v2. Search the issue tracker for more information :)

I don’t see any reason why you’d have problems with Gridster or Freewall, though. Unless you provide code examples, it’s pretty hard to give you any advice here.

In any case, the GitHub issue tracker is for bugs and feature requests only. If you want to integrate MDL with other libraries, please head over to StackOverflow and use the `material-design-lite` tag.

**Comment by Unforgiven-wanda** [comment]
If I may ask, what use does material.js serve here? I've tried reading through it, it's pretty technical, and long. Just the key points will be fine.

**Comment by surma** [comment]
material.js itself is probably a bit hard to grok :D It’s really just the concatenation of the JavaScript of each component. You can go to [the `src` directory`](https://github.com/google/material-design-lite/tree/master/src) and look at the code of each component to get a better understanding. Mostly, it’s manipulation of classes and the DOM tree and setting up the event handlers.
