### ISSUE TITLE
Migrating to Typescript in MDL 2.x

### ISSUE THREAD

**Issue by KorsaR-ZN** [google/material-design-lite#4060]
Can migrating on Typescript in MDL 2.x?

**Comment by Garbee** [comment]
What kind of a benefit does the project gain from making the source Typescript over pure JS?

**Comment by sgomes** [comment]
Sorry @KorsaR-ZN, we're going to stick with vanilla JS for the time being, and we'll be taking advantage of ES6 features through a compatibility layer like Babel.

We do have optional Closure compiler support in our JS, so that gives us many of the static checking benefits, while making it easier for a new contributor to get up and started working on MDL without having to learn a new typing system.
