### ISSUE TITLE
Layout tabs slide indicators do not display

### ISSUE THREAD

**Issue by stianflage** [google/material-design-lite#4061]
The tabs slide indicators appear (transparent) on screen sizes over 1024px (when not needed) and are set to `display:none` on screen sizes under 1024 (when they are most likely to be needed).

Material Design Spec: https://www.google.com/design/spec/components/tabs.html#tabs-usage

Codepen: http://codepen.io/stianflage/pen/qbyawy
(I set the just override the button color to white so it's visible)

**Comment by Garbee** [comment]
FYI, just updated from "Pagination" to say "slide indicators". These are pagination tools, makes people searching for that stuff not see this which isn't relevant.

**Comment by hermagrini** [comment]
Please correct me if I'm wrong, but I think that the current behavior is following what the MD Spec proposes: 

[For Mobile tabs](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsZ0RaTDMwMnRmTDg/components_tabs_usage_mobile5.png), the intended behavior is that when the tabs do not fit within the screen, then the overflow is scrollable by swiping to the sides of the tab bar, showing just an small part of the first overflown item to indicate the user that there's more content within the tab bar, since this is the type of interaction that the user is familiar with on Mobile.

[But on Desktop](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsRUM1elg3VDRxdTg/components_tabs_usage_desktop5.png), the MD Spec suggest to have the slide indicators (in the spec referred as "pagination") to show that there are more elements, since paginated content with indicators is more familiar to the user on Desktop.

Then whether 1024px should be considered as the breakpoint between Desktop and Mobile is arguable, the [MD Spec on Breakpoints](https://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-breakpoints) lists a large tablet on landscape within the 1024px breakpoint, and then adds a side-note saying that Desktop breakpoints are 16dp below the listed values, starting from 1024px; but considering this, I would say that the current behavior for the tabs indicators is correct.

**Comment by sgomes** [comment]
Looking at this in more detail, it looks like @hermagrini is correct; this is the correct behaviour and there has been no regression.

The only reason that the slide indicators are appearing when they shouldn't in your codepen, @stianflage , is because of your override. If you remove it, buttons should appear and disappear as needed, according to the spec.

**Comment by macx** [comment]
The problem with the current implementation is: If you have a lot of tabs or tabs with long names, users on desktop has to know, that there are more tabs to select. But because the button color [is set to transparent](https://github.com/google/material-design-lite/blob/d05739693d92a3e981cec6a02cf064d4064f1328/src/layout/_layout.scss#L551), it will never appear for desktop users (viewport above 1024px). And for the most of users who are not able to scroll horizontally with their mouse, the tabs are useless.

See [Demo](http://codepen.io/macx/pen/jWQvMK)

**Comment by hermagrini** [comment]
Ok, so I took a look at @macx codepen and here is the actual issue:

When loading the page on a viewport with width < 1024px, and then resizing it to a longer width, the indicators appear correctly as per the MDS.

But when loading the page on a viewport which can show all the tabs without the indicator (width > 1550px in the case of [this codepen](http://codepen.io/macx/pen/jWQvMK) and then resizing it to a lower width, then the arrows do not show properly.

Apparently the "is-active" class is not being added to the parent element of the icon (which has the class mdl-layout__tab-bar-button mdl-layout__tab-bar-right-button)

**Comment by hermagrini** [comment]
Added steps to reproduce to previous comment :)

**Comment by sgomes** [comment]
Ah, that makes it much clearer, thanks @hermagrini! That's definitely a bug we should look into; reopening.

**Comment by macx** [comment]
:+1:
