### ISSUE TITLE
Hamburger menu should maybe be a button for better a11y

### ISSUE THREAD

**Issue by robdodson** [google/material-design-lite#4065]
It looks like the hamburger menu is currently a div with tabindex=0 which means it will always display a focus ring, even when folks click on it with a mouse. This leads me to suspect that many developers are just hitting it with `outline: 0` which is :sob: for a11y.

If you use a native button element the browser will differentiate between mouse and keyboard focus and only apply the focus ring on keyboard interactions. a11y wins!

**Comment by Garbee** [comment]
Already brought up via another PR on the accessibility of the layout.

Sadly, we are SemVer bound. Since this is something we generate for users, it can't be fixed. If anyone is targeting `div.mdl-layout__drawer-button` either through JS or CSS to get the button (or relying on it being a div in any way) their stuff would break.

Known problem, will be addressed in the 2.x refactor when developers will be free to chose the element on their own and we will recommend button by default. Until 2.x, SemVer means we are stuck with a div. :frowning:

**Comment by robdodson** [comment]
Can you point me to to the PR? If it doesn't exist already it may be good to write a little explainer in the wiki about a11y pointers. I'm imagining there are a lot of folks setting outline: 0 on their apps right now and that is a bummer

**Comment by Garbee** [comment]
PR #1887 was the thread where this came up.

Looking at our stats in GH, the wiki is not even on the list of top pages which bottoms out at about 500 unique visitors for a given page. I don't think adding more wiki content is going to really be beneficial.

1.x is basically at EOL now. We are working on at least one patch to it, possibly more if the need arises. 2.x is our main focus now, so I think we should just solve it naturally there as has always been the plan.

**Comment by robdodson** [comment]
Cool do you know if the Google Accessibility team will be doing a review of MDL 2? @addyosmani
