### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JoaquimFernando** [google/material-design-lite#4132]
We are a company. We have some questions about the Material Design Lite.
As a company can we do everything indicated below without any cost and without any kind of restriction?

1) Download the files "material.min.css" and "material.min.js" from the site "getmdl.io", and use these files
2) Include the <link> to "https://fonts.googleapis.com/icon?family=Material+Icons"
3) Include the <link> to "http://fonts.googleapis.com/css?family=Roboto:300,400,500,700"
4) Change everything we want in the file "material.min.css" (change colors, fonts, margins etc.)

**Comment by sgomes** [comment]
Hi @JoaquimFernando. MDL is released under the Apache license 2.0, which you can find in full at http://www.apache.org/licenses/LICENSE-2.0 and [in the LICENSE file on our code](https://github.com/google/material-design-lite/blob/master/LICENSE)

The Apache license is a free software license, but it does comes with some requirements, which you must follow in order to legally use the software. I am not a lawyer, so I'm sadly not able to break things down for you :( You can find some attempts at explaining the license online, though, maybe those can help.

The Roboto font is under the same license: https://www.google.com/fonts/specimen/Roboto

The Material Icons are [under a different license](https://github.com/google/material-design-icons/blob/master/LICENSE), which is summarised in the repository as:
> We have made these icons available for you to incorporate them into your products under the Creative Common Attribution 4.0 International License (CC-BY 4.0). Feel free to remix and re-share these icons and documentation in your products. We'd love attribution in your app's about screen, but it's not required. The only thing we ask is that you not re-sell the icons themselves.

So all in all, you should be able to use all of these freely, as long as you follow the requirements in the licenses. Hope this helps!

**Comment by JoaquimFernando** [comment]
I remind you that we are a company

1) Hi sgomes. I need an official response and not a simple comment from someone. sgomes are you an official member of Material Design Lite?

2) Can we download the files "material.min.css" and "material.min.js" from the site "getmdl.io", and use these files in our company without any cost and without any kind of restriction?

3) Our company can change everything we want in the file "material.min.css" (change colors, fonts, margins etc.) without any cost and without any kind of restriction?

**Comment by Garbee** [comment]
All the restrictions and requirements to use MDL are outlined in the licenses that @sgomes has referenced. We are not lawyers and cannot comment on your specific case of usage. That  is where your company will need to demo out what you are asking, then contact a lawyer of your own to assess whether it adheres to the licenses of the project and projects we depend upon.

We appreciate your attempts to stay on the right side of the licensing. However, it is a complicated area and it is difficult for us to comment on any given situation without seeing the code in question.

**Comment by JoaquimFernando** [comment]
Hi. Our company wants to use the "Material Design Lite" only to develop websites. We need to change the color of buttons, text etc.

**Comment by sgomes** [comment]
Again, sorry to emphasise this, but we are not lawyers, just the developers of MDL, so we can't provide legal advice.

It is my understanding, however, that both the Apache License 2.0 and the Creative Common Attribution 4.0 International License (CC-BY 4.0) allow for commercial use, and also allow for modification. They both come with restrictions, though, in what you can and cannot do, in areas such as providing credit or informing end users that parts of your work include licensed code.

I would recommend reading the licenses thoroughly, looking for TL;DR breakdowns of the licenses online, and going from there. These licenses are very well known in the community and used widely by both businesses and individuals, so you should have no trouble finding out more about what you need to do to stay compliant.

If after all of that you still have questions, your best bet really is legal advice.

Hope this helps!
