### ISSUE TITLE
List icon misaligns when href is given

### ISSUE THREAD

**Issue by shmshd12** [google/material-design-lite#4166]
```
      <li class="mdl-list__item" style="background-color:#ff2">
			<span class="mdl-list__item-primary-content">
			<a class="navi-link" href="#">
			<i class="material-icons mdl-list__item-icon">person</i>
			Bryan Cranston</a>
			</span>
		</li>
```
giving href to the list icon in navigation drawer misaligns icon and the text.
see below image for reference. In the image i only gave href to the 1st list and others are just  texts.
mdl v1.1.1
http://i.imgur.com/Z7848ul.png

**Comment by sgomes** [comment]
@shmshd12 It's a bit hard to tell where the problem is coming from with just the screenshot, but it looks to me that the problem is the `navi-link` class you're applying, which seems to be your own code. You'll need to make sure that the font and alignment settings for that don't shift things around.

Here's an example that, albeit ugly, works fine: https://codepen.io/anon/pen/ONMpBN

**Comment by shmshd12** [comment]
mdl v1.1.3 fixed this issue.
