### ISSUE TITLE
Cannot overwrite size of <object> when using chromium

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [google/material-design-lite#4201]
I am trying to embed a flash element in a mdl page. I want the flash element to be 1024px by 576px, so I do this:

```
<object type="application/x-shockwave-flash " data="Kulami.swf" style="max-width:100%;width:1024px;height:576px">
[...]
</object>
```

This works for firefox! But on chromium the flash element is tiny (but only when using mdl).
The example can bee seen here: http://kulami.woodengames.org

**Comment by Zodiase** [comment]
I can tell you that in Firefox that flash is still tiny.

![image](https://cloud.githubusercontent.com/assets/1815174/13751566/c4f87974-e9d8-11e5-9983-28aab2c9d248.png)

**Comment by Zodiase** [comment]
It's been years since the last time I used flash in a webpage so I don't recall how I used to size the elements, but according to this page http://www.aleosoft.com/flashtutorial_autofit.html and a bit of fiddling myself, you do need to assign sizes to **both** the `object` element **and** the `embed` element. After doing so, I get this:

![image](https://cloud.githubusercontent.com/assets/1815174/13751714/66fad7c6-e9d9-11e5-8131-870b7e06242d.png)

Which still looks wrong, but I guess that's a problem within your flash file.

Nothing so far looks related to MDL though.

**Comment by sgomes** [comment]
This may be due to one of our resets. Check the sources in https://github.com/google/material-design-lite/tree/master/src/resets and compare against what you see when you inspect the DOM. Then just override the offending property.

Hope this helps!

**Comment by Zodiase** [comment]
@sgomes I don't think his issue has anything to do with MDL or any reset. The problem he described still persists even when I removed all MDL css files in the inspector. Just saying.
