### ISSUE TITLE
css Not working

### ISSUE THREAD

**Issue by varaprashanth** [google/material-design-lite#4206]
Hi
We are working on a project which is done in asp.net c# we are using toogles from getmdl.io and it is placed in update panel it is working fine during page load but after partial postback javascript for toogle is not loading it  will render as normal checkbox. please help me to address to issue.
![beforepostback](https://cloud.githubusercontent.com/assets/17855675/13802683/3d3ff312-eb64-11e5-87c1-dcd64e88011b.png)
![afterpostback](https://cloud.githubusercontent.com/assets/17855675/13802684/3d428cee-eb64-11e5-9136-7a654eca9e9f.png)

**Comment by dgrubelic** [comment]
I think that this is a question for StackOverflow...

But, i'm going to answer it afterall... You have to register that component with componentHandler after postback is completed since Asp.net (web forms) internally replaced that DOM element with another one. Look for page postback event that occurs after postback. This actually is a common problem with Asp.net since it is a tech made waaay before these new technologies. I suggest you switch to something modern instead, it will save you time and nerves, trust me on this one - i had to fight problems like this one for 3 years! :S

**Comment by varaprashanth** [comment]
Thanx for the reply buddy 
i used  componentHandler.upgradeAllRegistered(); it worked perfectly.
