### ISSUE TITLE
Convert media queries to EM units

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#4211]
In light of some recent testing, [em units are the way to go](http://zellwk.com/blog/media-query-units/) for media queries. This is due to bugs in Safari's handling of both pixel **and** rem units.

**Comment by sgomes** [comment]
This ties back into our discussion on relative (e.g. `em`) vs absolute (e.g. `px`) units. We need to review the spec and make sure we're doing the right thing in all places.

After consulting with some colleagues from the Android side of things, it seems to me that the important distinction is between what's called [`sp` and `dp` in the spec](https://www.google.com/design/spec/layout/units-measurements.html); `sp` would be relative, and `dp` absolute. As such, things like [breakpoints](https://www.google.com/design/spec/layout/responsive-ui.html) would have to remain absolute in order to follow spec, even if behaviour is different across browsers (that's a browser bug, sadly).

In any case, we need to make a lot of changes across the board, in MDL. I'm trying to set up a chat with the Material folks internally, to see if we can get some advice beyond what's in the spec. I'll update this thread and / or rescope this bug once I find more!

**Comment by Garbee** [comment]
Well, this is *specifically* the media queries. `em` is actually the only unit to use for cross-browser consistency. Rules within the queries can still use `px`, `em`, or `rem` as is seen fit.

So long as we still break at the given areas using `16px` (default) font-size then we should be good to go.

**Comment by sgomes** [comment]
Right, but we should do an overhaul to make sure we use absolute and relative units in the right places. Breakpoints are one of the areas where it looks to me like we should be sticking with absolute units, despite browser bugs. I'll be sure to bring them up specifically when talking to the Material folks.

**Comment by AliMD** [comment]
After reading the article
I think we do not need this method
I think we don't want to change layout when user change the default browser font size.

**Comment by sgomes** [comment]
Forgot to update this discussion.

After discussing with some MD folks at Google, the conclusion seems to be that we should use `rem` for what the Material Design spec considers "scaling pixels" or `sp`. These are meant to scale with default text size, so `rem` is the right choice.

For everything that is marked `dp` or "device pixels" in the Material Design spec, we should use CSS pixels. These only scale with display density, as intended.

As such, even though it's handled incorrectly in Safari, we should keep on using CSS pixels for the media queries, as they're defined as `dp` in the spec: https://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-breakpoints
Changing this to `rem` would make breakpoints scale with default text size, which is not the expected behaviour according to the spec.

**Comment by Garbee** [comment]
/me sighs.

So we really need to get on Safari about this behavior so they can hopefully fix it ASAP. Thanks @sgomes. I'll close this up since it isn't something we are going to work towards.
