### ISSUE TITLE
mdl-layout--no-desktop-drawer-button is inconsistent

### ISSUE THREAD

**Issue by mfonville** [google/material-design-lite#4217]
If using `mdl-layout--no-desktop-drawer-button` the limit to show the button is set to a 'maximum' of 1024px.
So if trying to combine this element with other elements that *should NOT* appear on mobile and tablet but *should* using `mdl-cell--hide-phone mdl-cell--hide-tablet` it is set to a 'maximum' limit of 840px.
This does mean that for the widths of 840 up to 1024px both are true, and there is no graceful MDL-way to handle this situation.
Either `mdl-layout--no-desktop-drawer-button` should adhere to the 840px limit, or we would need an extra class for more fine-grained control for these widths for the drawer-button.

ADDENDUM:
I did find that `mdl-layout--large-screen-only` and `mdl-layout--small-screen-only` allow the switching at the 1024px, so they *do* match. If the behaviour is intended to act at the 1024px point, the name of the class is deceiving and should e.g. be `mdl-layout--no-large-screen-button` instead.

**Comment by Garbee** [comment]
This is a weird problem that appeared since the components were developed in isolation. This isn't something the core team is going to work on since we are currently working on a complete rewrite of the system for V2, which will be more tightly integrated with breakpoints and such between components.

Closing this out as no action will be taken here. Adding in more classes to the already convoluted layout setup isn't going to end up helping developers too much. If you hit these cases then working around them within your own code is fairly trivial.

Thank you.
