### ISSUE TITLE
RTL Support for v2

### ISSUE THREAD

**Issue by AliMD** [google/material-design-lite#4223]
Dear MDL lovers
I think it's time to think about RTL again (after 9 months from first request)
And I'm working on it for v2 (https://github.com/webrtl)
Could you please allow us / advise us to make it fully RTL Support as  a perfect way
I think CSS auto mirroring is wrong way and we must customize CSS for every components
As I said earlier I'm RTL native with many experience and I love to contribute in this lovely project.
Thank you in advance.

**Comment by AliMD** [comment]
#783 
#1518

**Comment by AliMD** [comment]
Could you please share your plan for RTL in v2.

**Comment by AliMD** [comment]
@addyosmani @surma @gauntface 

Could you please share your plan for RTL in v2.

**Comment by Garbee** [comment]
Closing this as a duplicate of #783.

We will announce information as we have it available. Currently we haven't discussed RTL support since we have been focusing on re-engineering the underlying architecture. Once we've discussed how to handle this, we will respond on the original issue.

Thank you.
