### ISSUE TITLE
[feature-request] Sub-menu in list item

### ISSUE THREAD

**Issue by shmshd12** [google/material-design-lite#4235]
I propose Mdl team to add sub-menu in list item like Polymer does here : https://goo.gl/hPZtCu 
or
On the click of a list, another list items open next to it. that way.
This will be useful for many mdl users.

**Comment by Garbee** [comment]
Submenu's aren't defined by the Material Design spec like this, therefore we won't be taking any action here.

Thank you.

**Comment by shmshd12** [comment]
@Garbee Submenu's are defined by the specs. 
Check out [this example](http://imgur.com/a/HCI5I) shown at https://material.google.com/components/menus.html#menus-usage

**Comment by Garbee** [comment]
Submenus to actual menus are a part of #4475, that is cascading and not a collapse as shown in Polymer (which is not defined anywhere.)

Submenus for the navigation drawer, are a part of #4476 and we will implement one type of them internally since doing all 3 of those is insanity.

We won't be re-opening this as it simply makes more issues to track when we already have this covered in our new plans for the initial V2 components.

Thank you.
