### ISSUE TITLE
Dose not mobilize of phones or tablets. But Desktop yes...?

### ISSUE THREAD

**Issue by Jakeh9777** [google/material-design-lite#4237]
I made a website using Google material design Lite. I did everything right and it works fine on the computer even when the Browser is shrunken down to a phone or tablet size. It mobilizes the site on there when the Browser is shrunked but not phones or tablets. I really need help fixing the issues with the site not reading the phone or tablet as smaller screens. Can anyone help?

**Comment by hebbet** [comment]
for support question please use stackoverflow or similar. that here is for tracking real bugs.

**Comment by Jakeh9777** [comment]
Moved to http://stackoverflow.com/questions/36294430/website-dose-not-mobilize-of-phones-or-tablets-but-desktop-yes

**Comment by tayiorbeii** [comment]
The solution to @Jakeh9777 's problem sounds like it would be fixed by this line:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

For the record, I had submitted a PR to include a note about this in the MDL docs, but it was denied.

https://github.com/google/material-design-lite/pull/1714

**Comment by Jakeh9777** [comment]
thanks
