### ISSUE TITLE
scss problems generating messy css

### ISSUE THREAD

**Issue by salc** [google/material-design-lite#4244]
i found this mess inside material.css v1.1.3:

.mdl-button--primary.mdl-button--primary { ... }
.mdl-button--accent.mdl-button--accent { ... }
.mdl-button[disabled][disabled], ...
.mdl-button--fab[disabled][disabled], ...
etc

please check scss.

**Comment by Garbee** [comment]
This is intended to increase the specificity of these items so they work when mixed with other components (since some bits get overridden.)

In 2.x we are looking into reducing our Sass usage and making things more modular to make sure things like this aren't needed anymore. We understand it is confusing to people at first, but it is a necessary evil until the big refactor for 2.
