### ISSUE TITLE
When mdl-layout__header is wrapper insider a div the menu icon and drawer is not showing properly

### ISSUE THREAD

**Issue by joshuajazleung** [google/material-design-lite#4261]
When mdl-layout__header is NOT wrapped inside another div, the drawer icon is showing properly 
```
<header class="mdl-layout__header">
...
</header>

<main class="mdl-layout__content">
....
</main>
```

However, when mdl-layout__header IS wrapped inside another div, the icon is gone
```
<div>
  <header class="mdl-layout__header">
    ...
  </header>
</div>

<main class="mdl-layout__content">
....
</main>
```

Since I am using anuglarjs for the front-end app, when create a directive where the header section is in, the icon and drawer does not function properly. However could I solve this problem?

```
<navigation></navigation>

<main class="mdl-layout__content">
....
</main>
```

When angularjs complied the template, the result is: 

```
<navigation>
  <header class="mdl-layout__header">
      ...
    </header>
</navigation>

<main class="mdl-layout__content">
....
</main>
```

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

We provide the specific markup needed to make layout function properly. It is quite complex and due to achieving IE9 support for that necessary in 1.x. If your tool can't produce that markup, then you need to find a workaround in your tooling to provide it.

Thank you.
