### ISSUE TITLE
What does mdl-card--expand do?

### ISSUE THREAD

**Issue by DanTup** [google/material-design-lite#4311]
Many of the [sample cards](https://getmdl.io/components/index.html#cards-section) have `mdl-card--expand` on the title, but I can't find any explanation of what it does - it's not listed in the classes at the bottom and I can't find anything obvious searching through the code.

**Comment by Garbee** [comment]
It is an old modifier that shouldn't exist since it has no clear reason to exist per the specification. As far as I can tell it was made for templates since they had a purpose for it in building, but it doesn't necessarily translate to usage in everyday applications since it is flex-dependent.

V2 won't include it, so consider it deprecated.

**Comment by gaurav9372** [comment]
`.mdl-card--expand {
    flex-grow: 1; 
   -webkit-flex-grow: 1;
   -ms-flex-positive: 1;
}`
