### ISSUE TITLE
mdl-layout__drawer-button

### ISSUE THREAD

**Issue by neechange** [google/material-design-lite#4312]
button位置偏上？
line-height:50px
? 56px
 48px||56px||64px

margin:10px 12px;
48+10+10=68  header 64px
margin:10px ?
8px

**Comment by neechange** [comment]
@media screen and (min-width: 1025px){
            .mdl-layout__header .mdl-layout__drawer-button {
                line-height:56px;
                margin-top: 8px;margin-bottom:8px;
            }
        }
        .mdl-layout__drawer-button{
            line-height:56px;
        }

**Comment by Garbee** [comment]
Can you please explain what this issue exists for?

**Comment by rejhgadellaa** [comment]
Is he referring to the same issue as described in #2017 ?

I think he's saying (with only calculations :P) that the height of the 'mdl-layout__drawer-button' is exceeding that of the toolbar (64px) because top/bottom margins is 10 instead of 8:

Right now it's 
`margin: 10px 12px 10px 12px;`
`width:48px; height:48px;`

10px + 48px + 10px = 68px height

It should be:
`margin: 8px 12px 8px 12px;`
`width:48px; height:48px;`

8px + 48px + 8px = 64px height - which it should be.

BUT, and that's where the above mentioned issue comes into play, this will cause the menu icon to move up and be misaligned. This happens on mobile size (`margin:4px;`, so on all sides). 

On a side note: the 'mdl-layout__drawer-button' (or its icon) also misses :hover and :active highlights like the (mdl-button) action icons do. It's a button so it should behave like one, right?

Short story: the 'mdl-layout__drawer-button' is a bit messed up and needs fixing :)

**Comment by Garbee** [comment]
No details from the original poster on this for a while. Closing it out.
