### ISSUE TITLE
How to animate the entrance of a dialog element?

### ISSUE THREAD

**Issue by felquis** [google/material-design-lite#4324]
Sorry if this question is out of context. But I wanted to animate the entrance and there's no documentation about it yet.

**Comment by Garbee** [comment]
As far as specifically helping you program the animation that is out of context here. We don't do integration/customization support here since that isn't related to the code we provide.

However, we can look into getting guidance from the MD team on if dialogs should be animated somehow when created. Overall this can be a fairly tricky thing to implement in a way that is universally usable which is why it wasn't landed with the initial component.

**Comment by Garbee** [comment]
This is superseded by issue #4486. We'll take a look at this when doing dialogs for V2.

Thank you.

**Comment by felquis** [comment]
Thank you @Garbee
