### ISSUE TITLE
Option to remove validation (is-invalid independent on form validity)

### ISSUE THREAD

**Issue by fstanis** [google/material-design-lite#4330]
Hello,

I started using a framework that has its own validation mechanism and realized this does not bode well with MDL - I've made it so that `is-invalid` is added when validation fails, but MDL removes this class automatically due to the form being valid.

As per [#1463](https://github.com/google/material-design-lite/issues/1463) and [#1780](https://github.com/google/material-design-lite/pull/1780) I've made sure the form has both the `novalidate` attribute and that the text element starts with `is-invalid`, to no avail. The solution I'm currently using is to duplicate all the CSS related to `is-invalid`, change it to a different class name and use this class name instead for my own validator, which is clunky at best.

**Comment by Garbee** [comment]
Can you please provide a reproduction sample on [codepen](http://codepen.io). The unit test for this is passing so it should be correct.

**Comment by fstanis** [comment]
Hi Garbee, of course, sorry for not providing one initially.

[Here's a sample](http://codepen.io/anon/pen/WwPPXQ) - notice the input becomes valid (`is-invalid` class is removed by MDL) as you start typing, but turns invalid when the element loses focus (when jQuery's `change` event triggers and adds the `is-invalid` class back). After pressing the *Stop validation* button, this effect is lost (the `is-invalid` class starts persisting), showing that the form validation function is the cause of the odd behaviour.

**Comment by Garbee** [comment]
Here is what I'm doing:

1. Focus input
2. Leave input
3. See it is still invalid (as it should be)
4. Focus again
5. Type `Hello World`
6. Leave input
7. See it is now valid state (as it should be)
8. Focus again
9. Remove `World` to make invalid
10. Leave input
11. See it is now invalid (as it should be.)

All is working as expected. Please provide exact steps to reproduce to diagnose the problem. So far everything appears to be working here.

**Comment by fstanis** [comment]
I recommend you open developer tools (or equivalent) to monitor the class changes as they happen.

1. Focus input
2. Type anything other than "Hello World" and keep the component focused
3. Notice the `is-invalid` class is gone at this point (this manifests itself with the error message disappearing) - this shouldn't happen, as the input is **still** invalid at this point
4. Leave input - the change event triggers and the class is back `is-invalid` - but, since the text at no point contained "Hello World", the input should never have lost the class in the first place

If you press the *Stop validation* button, you'll see that the class `is-invalid` always remains, unless the text becomes "Hello World".

To make the problem more "impactful", change the `.change` part to `.keyup`. If you do this, typing anything will make the error start flashing, as the class is constantly being removed and added back by jQuery and MDL.

**Comment by Garbee** [comment]
I'm not understanding this sample fully. Looking at it more closely, you are telling our validity system to not work at all and implementing your own check.

Please provide a reproducable sample using *no custom validation*. Our validation works around the standard [Constraint Validation API](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation). If you are trying to use anything other than this, it may not work as expected since our component system was not designed for anything else.

**Comment by fstanis** [comment]
That's correct - my problem with the current implementation is that it forces HTML5 constraint validation as the only method of validation and doesn't allow other forms of validation to work (either at all or just not properly, as in the keyup example where the error keeps flickering). The reason why I think it's wrong to force only this type of validation is twofold:

1. There are cases where validation cannot be done using HTML5 constraint validation (a simple example would be credit card numbers or anything that relies on a checksum). MDL would prevent such validation from working properly.

2. The [novalidate](https://www.w3.org/TR/html5/forms.html#attr-fs-novalidate) attribute should indicate that the form is not to be validated when submitted. However, MDL will apparently validate the form and display an error even with this attribute present ([codepen here](http://codepen.io/anon/pen/dMrXJb)), which I believe can be considered a bug.

**Comment by Garbee** [comment]
There is no problem using Constraint Validation, it is completely customizable to whatever you need. The MDN docs even include [an example of complex custom validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Complex_constraints_using_HTML5_Constraint_API).

The novalidate attribute only applies to submission, not to validity state checking. This can be seen in [this codepen](http://codepen.io/Garbee/pen/WwmGOa). While the form is set to `novalidate`, the invalid style is still triggered since the input *is invalid*.

I'm not seeing any bugs or issues  to be fixed here. What we offer is in alignment with how the native web platform works.
