### ISSUE TITLE
Slow Load

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#4352]
First, thanks for sharing.  I really like MDL and this template is beautiful and obviously is well tested across devices.

Just wanted to let you guys know that on my initial page load of https://getmdl.io/templates/portfolio/index.html it tool the page about 2 minutes to fully download and displayed broken image icons and the menu icon was not displayed (condensed view) until the page fully loaded.  It also appears that the top pink circle image is not caching and is slow to load.

...Just trying to help.  Not nit picking.

4g LTE connection
Samsung-SM-G935A (s7-edge)
Android v 6.0.1

**Comment by Garbee** [comment]
The templates aren't meant to be production-ready usage. They are just mockups of different styles that can be achieved using MDL.

On the load time you saw, it very much depends on the exact network conditions when dealing with mobile networks. As well as the CPU of the device in question and what all it is doing. Emulating just the connection point in DevTools yields about a 1 second page load (no cache) which is acceptable. Down to 2G (Good) was a roughly 8 second page load with no cache.

Yes, layout is problematic for loading (and major pain for developers in general) as well as some of the techniques we use to enhance things for legacy browser support. In V2 this is all going away since we are dropping most legacy browsers that are causing headaches.

Overall, I'm not seeing anything feasible to be done here. Load time seems good in DevTools (biased yes, but it is at least consistent for testing.) So, it seems the exact issues you saw were due to the physical device and network conditions it was experiencing at that time. As such, I'm closing this out now since it isn't actionable. If there are any specific recommendations as to how things can be improved then it can be re-opened and addressed accordingly.
