### ISSUE TITLE
Height not correctly calculated, resulting in second scrollbar appearing

### ISSUE THREAD

**Issue by maiakaat** [google/material-design-lite#4378]
The following code when using Angular 2 inside Material-Design-Lite with CSS class mdl-layout_container causes an incorrect height to be computed, resulting in a second scrollbar on the container with the class mdl_layout_container.

Removing this CSS class fixes the issue, this maybe due to the way Material-Design-Lite interacts with Angular 2.

Outer code causing the issue with angular directives visible

`          

    <div class="mdl-layout__container">
       <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header mdl-layout__header--transparent">
            <page_header></page_header>
        </header>
        <main class="mdl-layout__content--transparent ">
            <page_main></page_main>
        </main>
        <footer class="mdl-mega-footer--transparent">
            <page_footer></page_footer>
        </footer>
    </div>
</div>
`

Browser is Chrome Version 50.0.2661.102
MDL is 1.1.3

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by maiakaat** [comment]
Surely this is possibly a bug if it's getting the computed height wrong and it's not an implementation issue?

I've attached a file of the template - it happens with and without mdl-layout__container using static content (no angular) - rendered from a server without mdl-layout__container the issue is fixed

[example.txt](https://github.com/google/material-design-lite/files/281848/example.txt)

I didn't really want to post the template free for anyone to copy but here it is with sensitive stuff taken out

**Comment by maiakaat** [comment]
What is the point of the forum if you close any post that mentions another framework - even if the problem may be MDL code?

**Comment by Garbee** [comment]
> What is the point of the issue forum if you close any post that mentions another framework - even if the problem may be MDL code?

Unless the problem is specifically within MDL code, issues are closed until a case can be shown where it is reproducible with *only* MDL to debug. Anything else we simply don't have the capability to handle support within the issue tracker. It creates a bunch of noise and is difficult for others to search with the same problem. StackOverflow is *far* better suited to this. So you can ask for help on StackOverflow, then if the issue is determined to be internal to MDL an issue can be opened here that we can look into.

> If it breaks as soon as you add HTML or CSS content, rejecting possible issues to close tickets as fast as possible is going to make it useless.

So far, this hasn't been shown. If you go check StackOverflow this has come up a few times, the [most recent was today](https://stackoverflow.com/questions/37427956/footer-height-is-too-small-in-chrome).

We appreciate issues but we simply can't handle support through the issue tracker. It creates too much noise of everyone going back and forth which distracts from work on actual internal bugs.

We also understand that the documentation is not exactly clear in some areas. This is being worked on in 2.x with restructuring the component documentation. Until then though, for some of this "not so clear" points searching existing questions is the best way to figure those bits out sadly.
