### ISSUE TITLE
Material icons don't work in Safari, Edge

### ISSUE THREAD

**Issue by coolroom** [google/material-design-lite#4382]
![11](https://cloud.githubusercontent.com/assets/16744898/15583931/0ab02a7c-2389-11e6-9620-e23a1c8ca3e7.png)
![12](https://cloud.githubusercontent.com/assets/16744898/15583940/1229ae40-2389-11e6-9906-0c8a18e01b4e.png)
Surely, code is the same on both pictures. Moreover, buttons like add do not work.
Totally: chrome, Mozilla, stock android browser = working pretty well
safari and edge - not working.

Thanks.

**Comment by Garbee** [comment]
Can you please provide a working demonstration of this problem? In something like [codepen](http://codepen.io) or a self-hosted demo.

The template we provide works fine in Edge at least, I can't test Safari since I don't have access to it. However, since Edge is working as you stated it wasn't it seems to me like there is a subtle code problem going on.

Thank you.

**Comment by coolroom** [comment]
Good evening,
Thanks for the answer.

Here is address of my server(might be slow, sorry)
mybeer.info
Cause it's russian used there, here are some credentials to bypass registration stage.

Login: test@mdl.io
Pass: 123

Anyway, this could be by my own silly error, but it seems strange to me that somewhere it works, and somewhere not. 

Please note me the reason.
Thanks in advance.

Vyacheslav

**Comment by Garbee** [comment]
You're font include isn't complete. You are only including the `woff2` format which is [not supported by IE/Edge (current) and Safari](http://caniuse.com/#feat=woff2). Update the font to include the complete font family definitions as upstream.

No MDL issue here.
