### ISSUE TITLE
Card actions not aligned to the bottom of card in an mdl-grid

### ISSUE THREAD

**Issue by ArnaudWeyts** [google/material-design-lite#4390]
![image](https://cloud.githubusercontent.com/assets/10011712/15679464/4248af8c-2752-11e6-84d8-0a5c5d50f871.png)

When the cards are auto-resized in an mdl-grid, the actions are not aligned to the bottom of the card if the text is longer on one card. Shouldn't actions always be aligned to the bottom? I've searched around and haven't really found a clean solution for this.

**Comment by Zodiase** [comment]
A codepen would be more valuable than a screen shot.

Have you put `mdl-card--expand` on those `<div class="mdl-card__supporting-text">`s?

**Comment by Garbee** [comment]
Please provide a functioning reproduction on something like [codepen](http://codepen.io). As the cards are set to work, they function as expected. You mention trying to mix a grid with them somehow, so that can confuse things. As it is, there isn't enough information here to determine whether there is a problem we need to look into internally or if this is something developers will need to handle in their own code.

Thank you.

**Comment by ArnaudWeyts** [comment]
O god i'm retarded. Adding mdl-card--expand to the supporting text totally fixed my problem.
Sorry for wasting your time.

**Comment by Garbee** [comment]
FTR `mdl-card--expand` should not even work here unless you're making the card itself into a grid which isn't directly supported. Cards go within grids but shouldn't necessarily become them.

**Comment by ArnaudWeyts** [comment]
Well i didn't have mdl-card--expand set on any of the items above the mdl-card__actions.
[Here's](http://codepen.io/ArnaudWeyts/pen/pbvgmE) a pen to demonstrate what happened.

**Comment by Garbee** [comment]
And I just realized we do have cards as flex display by default... whoops. I'll fix that in V2, it is leftovers from where I was doing some horizontal card work. Cards don't explicitly need to be flex display, which is why this issue happened.
