### ISSUE TITLE
Floating label drops down for invalid number Textfield

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#4393]
Same as #1200. Seems like the issue was closed but not resolved.

CodePen: http://codepen.io/Zodiase/pen/qNExgw

![image](https://cloud.githubusercontent.com/assets/1815174/15716752/7163a6b8-27e9-11e6-883c-d66df3f70871.png)

Reproducible in Chrome 51.0.2704.63, Safari 9.1.1 (11601.6.17) and Firefox 46.0.1 on OSX El Capitan.

**Comment by Garbee** [comment]
Are double decimals technically a number?

This is failing because the value is `""` during the dirty check since it fails. We equate an empty value to "not dirty" by default.

This seems like and edge-case due to the looseness of the implementation in browsers (as they need to be.) Can be fixed by using a pattern system to validate the actual structure of a number as well.

**Comment by Garbee** [comment]
Just verified with some Chromium engineers in IRC. `1.2.3` is absolutely not a valid floating point number which the number type requires. So the parser is kicking out and going to `""` for the value which triggers the dirty state here.

Recommended solution is to use a pattern on top of the number type to ensure only valid floating point numbers can be entered. This way the browser will enforce valid input on its own that won't equate to an empty string for the value.

**Comment by Zodiase** [comment]
Since `""` is considered valid for a number input, `input.type === "number" && input.value === "" && !input.validity.valid` should be enough to tell if the actual value user typed in is not empty and thus mark the input as dirty.

Also why should the floating label drop for invalid fields? I couldn't find anything on [this MD spec page](https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors) that suggests invalid non-dirty floating label textfields should have dropped labels.

Well I could just use something like `<input type="text" pattern="[-+]?[0-9]*\.?[0-9]+">` in place of number textfields but I still think, given that you've already done something to support number type (#889), why not make the support a little bit better. The whole number type could be an edge-case if you wanted it to be.

**Comment by Garbee** [comment]
It shouldn't drop for invalid fields. It is dropped because the dirty state check fails due to an edge-case in input structure and input causing the value length check to return 0 when it shouldn't. However, it is accurate by the specification since the input to the number type is *not a valid floating point number*. Nor is it a text field, so a standard length check fails.

IMO this is an edge-case that developers need to be aware of and deal with. Fixing it in your markup also provides a better user experience all around since the browser enforces proper input. Therefore, I don't see a good enough reason for us to hack around this edge-case internally.

**Comment by Zodiase** [comment]
> It shouldn't drop for invalid fields.

**It just did.** Even though the dirty check is not working properly, the validity check is fine. In the codepen above, after making the input invalid (see the red color?), the textfield is both **non-dirty and invalid** while having a dropped floating label!

**Comment by Garbee** [comment]
*non-dirty* being the keyword. Dirty state affects the label, not validity.

**Comment by Garbee** [comment]
FTR `<input required>` within our markup is "invalid" by default and shows the non-floating label. Because that is right.

Dirty state is what affects the floating label since it should only be raised *if* the input has content. Since your input is outright invalid for that type, the browser engines collapse and simply set the value to `""` to compensate. Which causes the length check to fail which causes it to be stated as non-dirty even though it is in fact dirty on-screen.

A proper pattern type in this case helps not only your UX but also your users from making invalid input. No reason for it to be fixed internally.
