### ISSUE TITLE
Add/include support for snippet

### ISSUE THREAD

**Issue by oldergod** [google/material-design-lite#4404]
### Feature

Copy the snippet content by clicking on it, as used for the snippets in the [components page](https://getmdl.io/components/)

![image](https://cloud.githubusercontent.com/assets/1767669/15797855/7b0ea52c-2a60-11e6-87e9-3123ed485826.png)

Since there the [code already exists](https://getmdl.io/assets/snippets.js), I though it would be a good thing to (1) add it as a component on the component page and to (2) add the snippet code to the main [material.js](https://code.getmdl.io/1.1.3/material.js).

**Comment by Garbee** [comment]
This is something custom to the microsite and is even being removed. It won't be added as a component since this is not Material Design related but instead a custom addition.

Not everything that is a component should be provided. Many sites have different needs and they should handle things in their own way.
