### ISSUE TITLE
Proposal: MDL V2 Architecture POC

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4447]
Hey all,

I've just pushed my [experimental/v2-architecture-poc branch](https://github.com/google/material-design-lite/tree/experimental/v2-architecture-poc) up to the repo. It contains all of my work done for coming up with a modular and flexible architecture for MDL v2 which satisfies all of our goals. 

I couldn't open a PR for it since I created an orphan branch for this work, so I'm opening up this issue where we can discuss what's there and how we want to proceed. 

The design doc for the architecture is in the README. There are two POCs which show how this model can be easily integrated into wrapper components in both React and Angular2.

**Comment by traviskaufman** [comment]
cc @rfru @Garbee @sgomes

**Comment by sgomes** [comment]
Thank you for the awesome POC, @traviskaufman! It overall looks great, and I think this is a good path forward. There is no code problem that isn't solved by adding another layer of abstraction, and that's exactly what we're doing here ;)

I have a few questions regarding some of the specific choices in your implementation. I'll make my comments in separate replies, to try to keep some visual sanity on the discussion :)

**Comment by sgomes** [comment]
### Property change hooks

As far as I can tell, in `installPropertyChangeHooks` you're overriding some properties on the native checkbox JS object, in order to capture programmatic changes to the native element's property. This is a really clever idea, and a good way of getting around the usual restriction of needing to go through the component API to make changes to it (because otherwise the library code is unaware of them), enabling easy integration with JS libraries that manipulate these property values.

That said, It does worry me on a few levels:
- Browser compatibility. I believe that in some browsers (at least until recently) native elements tended to be low-level native constructs with a thin layer of JS on top. Do all of the browsers we're targeting support this sort of manipulation? I suppose that the fact that it's happening at the instance level rather than the prototype level makes it a lot more likely that they do.
- Interaction with libraries/frameworks. Some of the libraries and frameworks out there (including some that we're hoping to support through these changes) are known to liberally override methods on the DOM and in DOM elements. Would our hooks interfere with the overrides those frameworks make, e.g. through race conditions on who gets to apply their changes first?
- Enhancement vs requirement. My gut feeling is not having this as the only, required path for checking and unchecking an MD checkbox, but rather as an alternative. The recommended path would instead be a `checked` property on the MD checkbox JS instance itself, which would call the correct methods to make sure all the magic happens (similar to how it's currently being done in `master`). That way, user scripts can still interact with it even if for some reason the hooks don't work, plus we enable "opaque" manipulation of the checkbox, where the user script doesn't have to know about its internal DOM structure (although I suppose it could do `checkbox.getNativeCheckbox().checked = value;`).
My suggestion would cause some duplication, though, so I'm not sure it's the best approach. WDYT?

**Comment by sgomes** [comment]
### getNativeCheckbox

This is a nitpick. Does the mixin model work with properties? If so, I would suggest changing this to a getter (`get nativeCheckbox()`), to make the API cleaner (since this method wouldn't just be used internally, but by user scripts as well). So they could do:

```js
checkbox.nativeCheckbox.foo = bar;
```

rather than:

```js
checkbox.getNativeCheckbox().foo = bar
```

We could also consider renaming it to `getNativeElement` (or `getNativeInput` if we feel this is only relevant for input elements), since it may be useful to call it without knowing exactly which type of component we're dealing with (e.g. for programmatically disabling a bunch of elements on a form).

**Comment by sgomes** [comment]
### WebPack

WebPack is *fast*. I'm very impressed with it on that regard, and how gracefully it handles things like incremental compilation and change watching.

How active is the plugin scene for it? Would it in any way compromise our choice of tools (e.g. Babel vs Closure compiler or SASS vs PostCSS), or are all those well-supported?

Also, how easy is it to switch between different tool options, compared to e.g. gulp? Even if it's difficult, it wouldn't be a dealbreaker, but it may affect our roadmap in terms of which changes we commit to the repo first (e.g. whether we first decide on a transpiler or the build system).

**Comment by sgomes** [comment]
### Theme files

While I generally agree with the approach, I think the implementation needs to be discussed further.

#### Maintainability

One aspect is maintainability. How do we determine which properties should live in the base file or the theme file? Should we e.g. move all colour properties to the theme file? How about size properties? Also, is this something we do manually, or through some tool?

#### Customising the primary and the accent

I suspect that the simplest level of customisation that users will want to do is simply to change the primary and accent colours for their site. This actually translates into a few more colours, but we can select those automatically:
- A contrast colour for text on top of the primary colour. This is either 66% black or 100% white, and can be calculated with a colour contrast formula.
- A contrast colour for text on top of the accent colour. This is either 66% black or 100% white, and can be calculated with a colour contrast formula.
- A "dark primary" colour, used in certain places. This is a darker version of the primary colour, and can also be calculated by e.g. using the 700 colour of the primary palette (assuming a Material colour), or simply by blending a certain amount of black into the primary.
- A contrast colour for text on top of the "dark primary" colour. Same as the other contrast colours.

Our current [customizer](https://getmdl.io/customize/index.html) allows for downloading a custom CSS file with the entire set of MDL styles, using a particular set of colours. The theme file approach would allow us to instead provide add-on theme files instead, which would override the default colours.

However, how would this play with the modularisation effort? Would we have:
- A single theme file that overrides the colours for every component, regardless of which components you're actually using? May cause some size concerns.
- A theme file per component? Would require extra effort from developers simply to override the defaults, and the number of individual files we need to keep on our CDN (and potentially the number of npm packages we maintain) would massively increase.

#### Deep integration with frameworks and end-user code

The final aspect we need to consider is how we can have deep theming integration both with npm and with the frameworks we expect to use our code as a base:
- How could we make it easy to choose a theme through npm, if the user is using the plain compiled CSS?
- How could we make it easy to choose a theme through npm, if the user is running our sources through the preprocessor (SASS or PostCSS, depending on what we end up choosing)? This one seems easier to me, as it should simply be a case of overriding a few variables.
- How could we allow a framework that uses CSS variables to easily style component instances individually (with e.g. `--primary-color`, `--accent-color`, etc.)?

None of these questions need to be answered on this PR, but they're interesting topics to have on the back of our minds; it may help to have some sense of the direction we're going to take early on, since it could translate into constraints on tool and architecture decisions.

**Comment by traviskaufman** [comment]
@sgomes going to try to respond to all the comments here, except for Themes, which has a lot of items and probably requires its own answer, maybe even its own issue(?)

## Property change hooks ([issuecomment-228015815](https://github.com/google/material-design-lite/issues/4447#issuecomment-228015815))

### Browser Compatibility

The issue would hinge on whether or not `Object.defineProperty` works correctly on host objects. This would fail if either DOM objects were not supported, or properties on DOM objects were set with `configurable: false`. Looking at the [ES5 compatibility table](http://kangax.github.io/compat-table/es5/#test-Object_static_methods_Object.defineProperty), `Object.defineProperty` seems to be supported for all major browsers that we'd be targeting. There is a footnote saying that it doesn't work correctly for DOM objects in some versions of Safari 5, but idt we'll be supporting Safari 5. 

However, testing manually on the latest versions of each browser, here's what I found

| Browser | Version | Works? |
| --- | --- | --- |
| Chrome | 51 | Yes |
| Firefox | 47 | Yes |
| Safari | 9 | **No** - `checked` is non-configurable. [Fixed in TP](https://bugs.webkit.org/show_bug.cgi?id=49739) |
| Opera | 38 | Yes |
| IE | 11 | Yes |
| Edge | 13 | Yes |
| Mobile Safari / WKWebView | latest | **No** - See above for desktop safari (probably the same issue) |
| Chrome on Android | 51 | Yes |

So Safari is the only outlier here. However, it's easy to work around to simply feature-detect whether or not `HTMLInputElement.prototype.checked` is configurable and includes default getters/setters.

### Interaction with Libraries/Frameworks

I actually don't seeing this being a big issue, because we do call whatever the original setter was before applying our own custom functionality. That's a good point though about race conditions. Hopefully by the time our initialization method is invoked, they've already done whatever bootstrapping is needed. However, we could make it a bit more configurable through the adapter, e.g. `shouldAutomaticallyInstallPropertyHooks(): boolean` or something that's named a bit nicer 😄 

### Enhancement vs. Requirement

I like the approach you've outlined here. We could also expose adapter methods like `registerPropertySetter(property, setter)` which frameworks could override if they wanted. WDYT?

## getNativeCheckbox ([issuecomment-228018296](https://github.com/google/material-design-lite/issues/4447#issuecomment-228018296))

Using getters sounds good to me. The reason why I didn't go down this route actually was I thought that having an adapter define a property may be more ambiguous than explicitly invoking a method. But honestly that's more just personal preference than anything else.

## Webpack ([issuecomment-228047246](https://github.com/google/material-design-lite/issues/4447#issuecomment-228047246))

> How active is the plugin scene for it? Would it in any way compromise our choice of tools (e.g. Babel vs Closure compiler or SASS vs PostCSS), or are all those well-supported?

In webpack there is a notion of [loaders](https://webpack.github.io/docs/loaders.html) which are separate from [plugins](https://webpack.github.io/docs/plugins.html), so I'm going to assume we're talking about loaders since those are primarily used for source code transformations. 

The loader/plugin scene for webpack is IMO very active. Webpack's [list of loaders](https://webpack.github.io/docs/list-of-loaders.html) contains loaders for pretty much every type of asset I can think of, and there's >700 loaders [on npm](https://www.npmjs.com/search?q=webpack%20loader). Same goes for plugins with many listed both [on webpack's site](http://webpack.github.io/docs/list-of-plugins.html) as well as [on npm](https://www.npmjs.com/search?q=webpack%20plugin).

In terms of the specific technologies you mentioned:

* [babel-loader](https://www.npmjs.com/package/babel-loader) vs. [webpack-closure-compiler](https://www.npmjs.com/package/webpack-closure-compiler) vs. [webpack-traceur-loader](https://www.npmjs.com/package/webpack-traceur-loader) (for good measure)
* [sass-loader](https://www.npmjs.com/package/sass-loader) vs. [postcss-loader](https://www.npmjs.com/package/postcss-loader) (which is actually used in conjunction with sass-loader in this POC) vs. [less-loader](https://www.npmjs.com/package/less-loader) vs. [stylus-loader](https://www.npmjs.com/package/stylus-loader)

So I think unless we chose something extremely new or unfamiliar it probably wouldn't preclude us from switching source languages.

> Also, how easy is it to switch between different tool options, compared to e.g. gulp?

I think it's a lot easier than it is with gulp. Say we're currently using sass and we want to switch to pure postCSS + [cssnext](http://cssnext.io/).

We'd take our current config file (simplified for brevity):

```javascript
module.exports = {
  // ...
  module: {
    loaders: [ 
        {
          test: /\.scss$/,
          loader: 'sass'
        }
    ]
  }
};
```

and simply configure the correct loader for css:

```javascript
module.exports = {
  // ...
  module: {
    loaders: [ 
        {
          test: /\.scss$/,
          loader: 'sass'
        },
        {
          test: /\.css$/,
          loader: 'postcss'
        }
    ]
  },
  postcss: function() {
    return [
      require('postcss-cssnext')
    ];
  }
};
```

Then we can incrementally migrate stuff over, and everything still works fine. Once we've migrated everything, we simply remove the sass entry:

```javascript
module.exports = {
  // ...
  module: {
    loaders: [ 
        {
          test: /\.css$/,
          loader: 'postcss'
        }
    ]
  },
  postcss: function() {
    return [
      require('postcss-cssnext')
    ];
  }
};
```

and voilà!

> where does it serve the files from?

Webpack-dev-server serves the files from [memory](http://webpack.github.io/docs/webpack-dev-server.html#content-base). When you run `webpack` to build the bundle, it writes the bundle to disk.

**Comment by traviskaufman** [comment]
@sgomes 

## Theming

Yeah, so, theming is a large and complicated discussion :). I'll address what I can below but maybe worth moving into a separate larger issue?

### Maintainability

> How do we determine which properties should live in the base file or the theme file?

I think it depends on what aspects of the component are deemed "them-able". For example, in the case of a button, we'd apply all stylistic treatments that distinguish it as a "raised button" within the base css. Then, in the theme css, we would perform color applications.

```scss
// _variables.scss
$mdl-button-raised-bg-color: white !default;
$mdl-button-raised-text-color: $mdl-typography-text-color-dark !default; // imported from mdl-typography

// mdl-button.scss
.mdl-button {
  // omitting typography stuff...
  border-radius: 2px;
  cursor: pointer;
}

.mdl-button--raised {
  box-shadow: /* .... */;
}

// mdl-button-theme.scss
.mdl-button--raised {
  background-color: $mdl-button-raised-bg-color;
  color: $mdl-button-raised-text-color;
}
```

Then if you wanted to override this in sass:

```scss
$mdl-button-raised-bg-color: $google-blue-500;
$mdl-button-raised-text-color: white;

@import 'mdl-button/mdl-button-theme';
```

Or in plain css:

```css
/* Button CSS is loaded, but no theme css. */
.mdl-button--raised {
  background-color: #2196f3;
  color: white;
}
```

I imagine this would be manual, and I imagine it would primarily deal with colors. A lot of preceding implementations have taken the route of actually exposing too _much_ as theme-able. While end users are free to alter and modify and override as they see fit, there are only certain things - mostly having to do with color - that the spec facilitates theming by default. This includes element dimensions. A button, for example, has a certain size that according to the spec should _not_ change. However, if someone wants to make a gigantic CTA button for their site, they can simply attach an additional class and make the necessary overrides.

### Customizing Primary + Accent Colors

I think you're right in that this serves as the basis for a theme. Here's what I've been thinking for this, which we can discuss further:

* We create a sass library called `mdl-theme`. `mdl-theme` is the only package in all of MDL that has any notion of "primary" and "accent" colors. It has no dependent packages.
* `mdl-theme` has _implicit_ knowledge of all of the sass variables throughout MDL that deal with components' themes. For example, even though it doesn't depend on `mdl-button`, it knows about `$mdl-button-bg-color`. 
* `mdl-theme` exposes a mixin, `@include mdl-theme($primary-color, $accent-color, $is-dark)`, that, when invoked, overrides all `!default` theme properties with the correctly calibrated props based on the `$primary-color` and `$accent-color` given.
* A client can invoke `mdl-theme` before importing all of the theme files for components.

Example:

```scss
// mdl-theme/_mixins.scss
@mixin mdl-theme($primary-color, $accent-color) {
  // override all component-specific theme vars.
  $mdl-button-raised-bg-color: correct-bg-color($primary-color) !global;
  $mdl-button-raised-text-color: $primary-color !global;
  $mdl-checkbox-bg-color: $primary-color !global;
  // ...
}

// file-using-mdl-theme.scss

@import 'mdl-colors/variables';
@import 'mdl-theme/mixins';

// Sets up all of the correct theme variables.
@include mdl-theme($mdl-color-indigo-500, $mdl-color-pink-a200);

@include 'mdl-button/mdl-button-theme';
@include 'mdl-checkbox/mdl-checkbox-theme';
// ....
```

This would then override the default variables within the theme file and output the proper CSS.

[This Gist](https://gist.github.com/traviskaufman/df00db3850cea89f7f7653af69cfcc84) demonstrates a very simple example of how this might work. 

* **Pros**:
  * Theming from the sass side is super simple
  * The approach is non-invasive.
  * It's modular enough to be used as part of the MDL mega-library or can be included by 3rd party users and used with components a la carte.
* **Cons**:
  * Requires sass buy-in
  * ???

I actually have to take off for the day but I'll address the last part of this first thing monday.

In short:

* That's a really interesting use case about installing a theme via npm. I never really thought about it from that perspective, but it seems like a really cool idea to be able to just pull in pre-built css theme files. Perhaps we could build out some tooling to do so? 
* For CSS variables, we could try using `@supports()`, the idea being:
  * We create a mixin that uses either a hard-coded sass value or a css property if it's supported
  * In addition to having sass variables, we can export them as CSS variables

```scss
@mixin css-var-prop($property-name, $css-var, $fallback-value) {
    @supports (--css-variables: 1) {
        & {
          #{$property-name}: $css-var;
        }
    }
    #{$property-name}: $fallback-value;
}
```

[Simple example gist](https://gist.github.com/traviskaufman/6d5d290ffa33470af3a91c74db5de5d4)

**Comment by sgomes** [comment]
Thanks for all the comments, Travis :)

I'm happy with all the explanations and modifications you suggested regarding all the topics in your first reply.

As for theming, I agree we'll need a lot of thinking and experimentation around the topic. Let's leave it in the back of our minds but deal with later, as a separate proposal; I'm confident we can retrofit any necessary changes relatively easily.

**Comment by traviskaufman** [comment]
You got it! I'm going to open up another issue to discuss theming.
