### ISSUE TITLE
Implement Tabs v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4481]
Spec reference: https://www.google.com/design/spec/components/tabs.html

**Comment by vitalets** [comment]
jfyi: angular material seems already implemented it
https://material.angularjs.org/latest/demo/tabs

**Comment by dsl101** [comment]
I've been experimenting with Polymer and Vuejs / MDL, and to be honest I much prefer the ecosystem of Vuejs and MDL. It just seems simpler to achieve what I'm after, with one notable exception - Tabs. In the [past](https://github.com/google/material-design-lite/issues/1165), it's been suggested that MDL is aiming for static sites rather than dynamic - is that still the case for Tabs v2? I would love better support for dynamic tabs, changing the active tab in code, etc. It would be good to know the direction before I go too far down this line...

**Comment by traviskaufman** [comment]
> In the past, it's been suggested that MDL is aiming for static sites rather than dynamic - is that still the case for Tabs v2?

Nope! As we mentioned in our developer docs, **MDL V2 strives to seamlessly incorporate into [a wide] range of usage contexts, from simple static websites to complex, Javascript-heavy applications to hybrid client/server rendering systems.** To that end, our tabs component will be fully-customizable and easy to both drive programmatically and listen to programmatically. 

To that end, we probably won't be writing any explicit logic to associate a given tab with a content panel, because our goal is to focus mainly on the UX around the tabs and provide an interface for developers to do that themselves. However, I can see this as something a framework library wrapping our UI components might do.

**Comment by dsl101** [comment]
That is indeed great news. And, are those docs publicly available yet? I couldn't find much at all about V2 via the main site, and that text it looks like you quoted only returned [this](https://github.com/google/material-design-lite/issues/4163) from a google search.

If it's at the stage of needing testers yet, I'd be keen to be involved. We're building simple apps, but they are all experiments so tolerant of beta libraries. I'd also be integrating with Vue / vue-mdl, which might or might not be useful at this stage.

Tx.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/37
