### ISSUE TITLE
Snackbar is missing in 1.1.3 when downloaded from Bower

### ISSUE THREAD

**Issue by ammuench** [google/material-design-lite#4517]
Snackbar code isn't in the material.js or material.min.js files if the source is downloaded from Bower.

**Comment by Garbee** [comment]
If this is the case we can't re-release packages as far as I am aware. Please provide a reproducible sample to have the issue re-opened for investigation if it is still affecting the 1.2 release so we can look into it with our next patch. Otherwise there isn't anything we can do here as we are focusing on building V2.

Thank you.
