### ISSUE TITLE
MDL is Verbose

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#4520]
Why?  The Google HTML/CSS Style Guide indicates [terseness is a virtue](https://google.github.io/styleguide/htmlcssguide.xml?showone=Optional_Tags#Optional_Tags).

So, instead of relying on classes (long one's in my opinion), why not simply select the tag itself?  for example a button, why not simply say:

```
<button>
  Click Me
</button>
```

rather than:

```
<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
  Click Me
</button>
```

**Comment by Garbee** [comment]
Because we shouldn't directly style elements. That will cause massive conflicts with other things developers may use in their software. MDL is *not* a framework, it is a library of components meant to be used as-needed within an application. So, doing raw targets for major style changes is inappropriate.

If developers want this, they can handle it on their own using a preprocessor and handling the targets and styling (via `@extends` etc.) on their own. Everything we provide should be "opt-in" not forced.

We also don't follow the Google HTML/CSS Style Guide, we only try to follow the JS guide as much as possible.

**Comment by rhroyston** [comment]
Why not style elements by tag name?  In what scenario would there be any
conflict?

On Mon, Jul 4, 2016 at 6:39 AM, Jonathan Garbee <notifications@github.com>
wrote:

> Because we shouldn't directly style elements. That will cause massive
> conflicts with other things developers may use in their software. MDL is
> *not* a framework, it is a library of components meant to be used
> as-needed within an application. So, doing raw targets for major style
> changes is inappropriate.
>
> If developers want this, they can handle it on their own using a
> preprocessor and handling the targets and styling (via @extends etc.) on
> their own. Everything we provide should be "opt-in" not forced.
>
> We also don't follow the Google HTML/CSS Style Guide, we only try to
> follow the JS guide as much as possible.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/material-design-lite/issues/4520#issuecomment-230271155>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMKS-27cpyrVy7s06rxkCDpMiUl_7D8kks5qSPDogaJpZM4JEBCH>
> .
>



-- 
- Ron Royston
  (504) 722-8412

**Comment by Garbee** [comment]
It would collide with any existing targets to `button` in CSS that would make our CSS behave differently. Or any other targets a developer pulls in later for another component/library/framework to operate.

It is best-practice that any code provided by libraries be scoped internally as much as possible using classes in order to reduce the chance of colliding with other things.

**Comment by rhroyston** [comment]
A single UI library is used, not multiple.  Like using <i> for icons, hold
your nose and dive into a solid win for simplicity.  You're Google, you can
do it!

On Mon, Jul 4, 2016 at 11:25 AM, Jonathan Garbee <notifications@github.com>
wrote:

> It would collide with any existing targets to button in CSS that would
> make our CSS behave differently. Or any other targets a developer pulls in
> later for another component/library/framework to operate.
>
> It is best-practice that any code provided by libraries be scoped
> internally as much as possible using classes in order to reduce the chance
> of colliding with other things.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/material-design-lite/issues/4520#issuecomment-230323224>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMKS--N0M1TY4za1oaomX_s1fg1V3K5mks5qSTQCgaJpZM4JEBCH>
> .
>



-- 
- Ron Royston
  (504) 722-8412

**Comment by Garbee** [comment]
No we won't. This is bad practice for package maintainers. We appreciate the input, but it doesn't align with the end-goal of what we should provide. Handling styling to this extent is upon developers integrating MDL into their applications.

**Comment by nj3ma** [comment]
+1 What Jonathan said.

On 7/4/16, Jonathan Garbee <notifications@github.com> wrote:
> No we won't. This is bad practice for package maintainers. We appreciate the
> input, but it doesn't align with the end-goal of what we should provide.
> Handling styling to this extent is upon developers integrating MDL into
> their applications.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/material-design-lite/issues/4520#issuecomment-230325848


-- 
Mwaoshe Njemah
Lead,
Teke Teke
www.teketeke.co.ke
moshe@teketeke.co.ke
0722 99 19 18 | 0733 66 55 77

**Comment by YamiOdymel** [comment]
At least make the class name much easier to read, for example:

```
<button class="mdl fab ripple button">
  Click Me
</button>
```

instead of 

```
<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
  Click Me
</button>
```

**Comment by toddmbloom** [comment]
I won't use a library that doesn't use namespaced classes, tbh. It's bad practice to assume your library is the only thing that matters.

**Comment by Garbee** [comment]
So, 4 classes there, `mdl`, then `fab`, then `ripple`, and finally `button`. Two are extremely common, another possibly-colliding, and the `mdl` highly unlikely. Still, 4 separate classes to achieve a unified look, which if you want to override, you'd then need to handle verifying your specificity is higher than all 4 combined.

We are reducing components down more so they are more insular with V2. That will alleviate quite a few problems. However, undoing the BEM scheme is not happening, it is too useful as project maintainers. Even for users, it is extremely useful whether you realize it or not.

**Comment by YamiOdymel** [comment]
@toddmbloom You should use the **components** instead of the _normal_ HTML already
(_since MDL is more like an **Application Framework**_),

with components you can **`scope`** your styles, and there will be no conflicts,

and let your framework (_**Vue**, **React**.._) handle those `$('.mdl-button.mdl-js-button')` things,

BEM-style is not so _human-friendly_, it's more like something that might be generated by the  compilers,

just look how Semantic UI handle this

```
<button class="ui button"></button>
<button class="ui icon button">
    <i class="smile icon"></i>
</button>
```

vs MDL

```
<button class="mdl-button mdl-js-button"></button>
<button class="mdl-button mdl-js-button mdl-button--icon">
    <i class="material-icons"></i>
</button>
```

**Comment by Garbee** [comment]
MDL is *not* a framework of any kind. It is meant to be a library of material design components to implement within your apps. Yes, we messed some bits up in 1.x and made global state affect things when it shouldn't have. That is being addressed in 2.x.

BEM is plenty human-friendly, it all comes down to your *opinion* as to whether you like it. As project maintainers it allows us to have a clear naming convention for components and their functionality. Which is very useful for developers implementing to have consistency in what they are looking at so they know where they are in the system.

BEM naming is going nowhere. The verbosity is extremely beneficial as a project. If you would like something else, your Sass pipeline can handle making the classes you'd rather use.

**Comment by sgomes** [comment]
Locking this issue as we've elaborated on all the design choices and why there important, and provided a mechanism for customising things in your project if our defaults don't fit your needs.

**Comment by Garbee** [comment]
The feedback here is very useful. It means that in the documentation for 2.x we need to cover why we use BEM and how it is beneficial to projects. The issue is locked specifically because any more discussion here isn't useful to the project and people contributing to it. The naming is a foundational piece of architecture for us to provide the most maintainable and usable codebase possible.

We really do appreciate feedback from developers. In this case though the discussion is more opinion than anything else. Discussions like this aren't actionable without then upsetting another group of developers. Best we leave this discussion as it is and get on with all of our work, as I'm sure we all have big queues of work that need doing to worry about this aspect of the project.

Thank you.
