### ISSUE TITLE
I have a feature request , item selection , adapter to make an item selectable 

### ISSUE THREAD

**Issue by appunnicer13** [google/material-design-lite#4522]
Please review mdl guidelines on this , this is a feature request for v2 , https://material.google.com/patterns/selection.html  .  this is so that any one can build a selection process in native mdl theme ,

**Comment by Garbee** [comment]
Most of this is handled by native platforms, not web applications. Can you please be more specific about what you'd like to see implemented? The only thing here applicable to us directly is checkboxes which are already covered.

**Comment by appunnicer13** [comment]
but native web platform doesn't listen for long clicks , just like that if you go through the pattern you will understand that selection is not done natively. it should incorporate adapters for user gestures and click patters like long click etc

**Comment by Garbee** [comment]
Please file individual issues for the patterns you'd like to see added with use-cases for why they are necessary. As it is, "Add more gesture support" is overly-broad and not reasonably actionable.

Closing this out since it is overly-broad. Individual issues per-need are much better for discussion and if needed implementation action.
