### ISSUE TITLE
Not Working In Mobile UC Web Browser

### ISSUE THREAD

**Issue by akashbijwe** [google/material-design-lite#4524]
Hey,
Material Design Lits is not properly rendering on Mobile Uc Browser.
The Header is not rendering in my site.
Floating is not working.
Can u please help me out this.
Thanks.

**Comment by Garbee** [comment]
What is the "Mobile UC Browser"?

Our official [browser support](https://github.com/google/material-design-lite#browser-support-in-v1) does not cover this browser it seems. So any issues in it would be on developers to work on fixing in their own projects.

**Comment by akashbijwe** [comment]
Ok..
I mean the "UC Browser" for mobile is not rendering the css properly. 
u can download the "UC Browser" here http://www.ucweb.com/ucbrowser/download/ .
Thanks.

**Comment by Garbee** [comment]
That isn't a currently supported browser. I'm not finding any information on the engine it uses to help pin-point things. Looking around though, it appears they tend to use a proxy as well to compress things which can cause issues as well.

Closing out since this is on developers to deal with in their own applications.

**Comment by Rohit-shopasky** [comment]
Yes i have faced same issue. UC browser does not support materializecss. UC browser are mostly used in India and china, but we website have to develop websites which should run almost all the browsers.

**Comment by suyash-purwar** [comment]
My website also breaks when i open it on UC Browsers. What should i do now ?
