### ISSUE TITLE
Strange css class selectors

### ISSUE THREAD

**Issue by sstativa** [google/material-design-lite#4533]
Hi there, 
Going through css file I noticed some selectors use the same class name twice. Is there any reasonable explanation for this? It's either a "bug" or I some tweak that unknown to me.

Look for example `_button.scss`, there are selectors like this

`.mdl-button--primary.mdl-button--primary`
`.mdl-button--accent.mdl-button--accent`
`.mdl-button--disabled.mdl-button--disabled`

Other files:
**_data-table.scss**
`.mdl-data-table__cell--non-numeric.mdl-data-table__cell--non-numeric`

**_layout.scss**
`.mdl-layout__content.mdl-layout__content`
`.mdl-layout__header--transparent.mdl-layout__header--transparent`

**_slider.scss**
`.mdl-slider.mdl-slider.is-upgraded`

**_textfield.scss**
`.mdl-textfield.is-disabled.is-disabled`

**Comment by Garbee** [comment]
These are all done on purpose. Due to the way 1.x was setup and we didn't catch it to restructure, we opted for [doubling classes to increase the specificity](http://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/) so those classes would actually take effect. In V2 we are going to aim for specificity limits to keep work-arounds like this from being needed.
