### ISSUE TITLE
Custom input validation

### ISSUE THREAD

**Issue by 620hun** [google/material-design-lite#4537]
Hey,

Is there any way make sure inputs turn into invalid after I `setCustomValidity()`? I'm fairly certain this is not possible and if so it'd be highly appreciated if you could make it happen.

Steps: have an input form, say with email type. While it is validated by the browser, if I set my custom validity, MDL doesn't react to the change, except if I do a keydown on the input. However, this is not very user/developer-friendly. See my issue in details [here](http://stackoverflow.com/questions/38292607/custom-validation-in-mdl).

If this is possible can you please point me in the right direction?

Cheers!

**Comment by Garbee** [comment]
MDL isn't programmed to directly handle custom validity states. As it is, this affects 1.x which is currently only getting critical bug attention from the core team. If a community member wants to contribute a patch for this if there isn't a simple work-around then the `mdl-1.x` branch is open for pull requests.

As this is more of a support question rather than something outright broken in MDL, this issue tracker isn't the proper place for discussion. Hopefully someone on StackOverflow can help you find a way to make custom validity work.

Thank you.
