### ISSUE TITLE
Lists showed wrongly in Safari while rightly in Chrome

### ISSUE THREAD

**Issue by skkytest** [google/material-design-lite#4584]
In Chrome:
![image](https://cloud.githubusercontent.com/assets/12192283/17078395/c683b5d4-5124-11e6-8433-424cd8397d3c.png)
But in Safari:
![image](https://cloud.githubusercontent.com/assets/12192283/17078428/8a811788-5125-11e6-9e26-5dbf45bcc4ad.png)
And if I change css we can find the text move to right:
![image](https://cloud.githubusercontent.com/assets/12192283/17078407/021e9000-5125-11e6-81be-a2909a6c5d08.png)
I am not sure what happened, considering I almost copy the tutorial in the page:https://getmdl.io/components/index.html#lists-section
Here is my html:
![image](https://cloud.githubusercontent.com/assets/12192283/17078418/373b0340-5125-11e6-9526-e10bd8172a58.png)
And css:
![image](https://cloud.githubusercontent.com/assets/12192283/17078422/50cb3fd2-5125-11e6-9029-95f51e5e1411.png)

It's MDL version 1.1.3 I downloaded.
Any ideas what happened? Thank you!

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Since this problem relies on your custom code implementation (as the demos are fine it seems) support for this is out-of-scope of our issue tracker.

Thank you.
