### ISSUE TITLE
Incorrect size of icons in the app bar

### ISSUE THREAD

**Issue by osechet** [google/material-design-lite#4587]
Size of touch targets in the header bar (what material design specification calls app bar) is incorrect. According to the [specification](https://material.google.com/layout/metrics-keylines.html#metrics-keylines-touch-target-size), touch targets should be at least 48 x 48px. In MDL, the app bar icons (except the drawer icon) are only 32 x 32px. The problem can be seen in this [codepen](https://codepen.io/osechet/pen/GqdBrm): app bar icons are too close.

After modifying the css (https://codepen.io/osechet/pen/AXagdG), we get something that looks as expected.

BTW, right padding of `mdl-layout__header-row` on large screens is too big. It's 40px when it should be 24px.

MDL version: 1.1.3
Tested in Firefox 47.0.1 and Chrome 51.0.2704.106
OS: Ubuntu 14.04 and Windows 7

**Comment by Garbee** [comment]
This is an artifact of how the V1 layout system was implemented. Unfortunately, there isn't anything we can do to address this in V1 due to backwards compatibility with existing sites. This is absolutely getting fixed in the V2 rewrite however it is up to developers to fix within their own applications to get the proper touch target size if they need it.

Thanks for the report and the attention to detail, but for 1.x this is sadly stuck. :frowning:
