### ISSUE TITLE
Header title flickers

### ISSUE THREAD

**Issue by van-nguyen** [google/material-design-lite#4601]
#### What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.1.3

#### What browser(s) is this bug affecting (including version)? 
Chrome Version 51.0.2704.106 (64-bit)

#### What OS (and version) are you using?
OS X 10.11.6

#### What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Load a page with drawer fixed header

#### What is the expected behavior?
Header content does not flicker

#### What is the actual behavior?
Header content flickers

#### Any other information you believe would be useful?
When I disable javascript, the h2.mdl-layout-title hides off the screen, meaning some javascript magic is re-aligning the element causing it to flicker on page load.
<img width="1020" alt="screen shot 2016-07-28 at 1 23 21 am" src="https://cloud.githubusercontent.com/assets/1149825/17181112/3e45b4e2-5462-11e6-93fb-75fd7bf610ee.png">

A possible fix is to style the CSS correctly so it does not rely on javascript to position it. Here is screenshot with javascript turned back on.
<img width="1020" alt="screen shot 2016-07-28 at 1 23 54 am" src="https://cloud.githubusercontent.com/assets/1149825/17181132/50fb44bc-5462-11e6-997a-4c6d92d8ad5b.png">

**Comment by Garbee** [comment]
Thanks for the report. This is a known issue with how the V1 layout was implemented in order to achieve our required browser support.

Due to semantic versioning, there is nothing we are able to do here to address this since people are already depending on this working how it currently does and any changes to it may affect their projects.

We are already working on V2 currently and layout is being broken down and completely re-coded to be far less problematic.

For now however, there is no action that can be taken here internally.

Thank you.
