### ISSUE TITLE
question about table component

### ISSUE THREAD

**Issue by collapsarzhang** [google/material-design-lite#4617]
Hi everyone, I am just wondering how I could take advantage of the data-* attribute when using the mdl table.
`data-mdl-data-table-selectable-name="materials[]" data-mdl-data-table-selectable-value="acrylic"`

how could I listen for the `select` event and retrieve the selected rows?

**Comment by traviskaufman** [comment]
This question is better suited for [StackOverflow](http://stackoverflow.com/questions/tagged/material-design-lite); please ask it there 😄 Thanks!

**Comment by Garbee** [comment]
Actually, this is an internal problem. Since we haven't pushed 1.2 yet the docs still aren't updated.

Don't use the data table JS at all. It is deprecated. Follow [these instructions](https://github.com/google/material-design-lite/wiki/Deprecations#automatic-selection-checkboxes) on replacing it which will allow you to set the name and values for the checkboxes.

**Comment by collapsarzhang** [comment]
@Garbee thanks so much for the instruction. it's great help
