### ISSUE TITLE
Add lightweight magic following line implementation for tabs.

### ISSUE THREAD

**Issue by FranzSkuffka** [google/material-design-lite#4627]
I once created a CSS-only following line Codepen that works with an arbitrary number of items:
http://codepen.io/franzskuffka/pen/GDExL

I think the tabs component would look even cooler with it with minimal source code modifications.

Should I create a PR?

**Comment by Garbee** [comment]
V1 probably shouldn't change. The code is quite complicated and we don't have the capacity to do a full review on a big change like this since we are working on V2.

With V2 we are redoing everything about the components. Once we announce Alpha and start asking for feedback on things if you'd like to take a look at tabs when it comes around and see if it can improve then by all means we'd love that.

Keep an eye on Issue #4481 for when the v2 tabs are in place.

Thank you.
