### ISSUE TITLE
When will next update officially be released?

### ISSUE THREAD

**Issue by shmshd12** [google/material-design-lite#4632]
Hey,

When will next update 1.1.4 be released officially?

also when will v2 be released?

**Comment by Garbee** [comment]
The next update will be 1.2 and should be released as soon as @sgomes has the time to tag and release.

V2, nothing to announce there. We are working very hard to get to an alpha point to start getting developer feedback on the system. But things are still very early and many moving parts are coming into play where we are going to end up eventually rethinking a few concepts.

Since there isn't any technical problem, I'm going to go ahead and close this issue out as there isn't anything the team can work on here. The next v1 release is just awaiting Sergio to have the time to handle carrying out the release.
