### ISSUE TITLE
Search icon misaligned in dashboard template demo

### ISSUE THREAD

**Issue by vwahj** [google/material-design-lite#4674]
Hi guys, I found this CSS bug:
![image](https://cloud.githubusercontent.com/assets/21029158/17653600/630edfb0-62db-11e6-96c3-13006b375273.png)
>> [https://getmdl.io/templates/dashboard/index.html](url)

I believe this is the cause of the bug:
![image](https://cloud.githubusercontent.com/assets/21029158/17653638/f2b23036-62db-11e6-8c91-c8d474a9b76d.png)

If I remove that property, the icon is aligned perfectly.

It also affects another browse such as Opera.

I am using:
MDL v1.2.0
Chrome Canary 54.0.2826.0
Windows 10 Build 14393

**Comment by Garbee** [comment]
Since this is a template-only issue it isn't something we are going to work on internally as we are focused on V2. It is probably related to an alignment fix I made so the drawer icon should always align by default properly.

If someone from the community wants to address this, `mdl-1.x` is open for PRs.

Thank you.
