### ISSUE TITLE
Dialog component not working on Firefox (plunk below)

### ISSUE THREAD

**Issue by CarlosAmaral** [google/material-design-lite#4687]
## Bugs

Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

1.1.3

> What browser(s) is this bug affecting (including version)? 

Firefox 48.0.1

> What OS (and version) are you using?

El Capitan 10.11.6

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

https://plnkr.co/eziXa08SK9c7G7D5YKCM

> What is the expected behavior?

Same as in Chrome, the dialog windows to open when triggered.
> What is the actual behavior?

Throws an error: `TypeError: dialog.showModal is not a function`

> Any other information you believe would be useful?

No and thanks

**Comment by vipentti** [comment]
Two things that are causing this not to work on Firefox properly (due to the polyfill):

1. Register the elements using dialogPolyfill.registerDialog(), passing it one node at a time. This polyfill won't replace native support.
	```html
	var dialog = document.querySelector('#my-dialog-selector');
	dialogPolyfill.registerDialog(dialog);
	```

2. Dialogs have limitations. They should be a child of `<body>` or have parents without layout (aka, no position absolute or relative elements)

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
