### ISSUE TITLE
Do you mind if I ask a question?

### ISSUE THREAD

**Issue by the1900** [google/material-design-lite#4688]
I wonder how does it works that detect outer of components witch need toggle such as *menu, a drawer in layout*. I've seen source codes of my curiosity but I couldn't find where except binding click event on components.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Since this is just a general question on how things work and there isn't a specific problem to be acted upon, you should go to more general support places for help. We simply don't have the people-power to handle support within the issue tracker itself.

Thank you.

**Comment by airtonix** [comment]
>  We simply don't have the people-power to handle support within the issue tracker itself.
- every google ticket ever
