### ISSUE TITLE
Information is cutting on mobile (iPhone 6). https://getmdl.io/components/index.html#buttons-section

### ISSUE THREAD

**Issue by luizfilipe** [google/material-design-lite#4689]
Hi guys to simulate this, just enter with a Google Developer Tools on this link on subject and activate the toggle device tools, select iPhone 6 to see the responsiviness, roll the scroll to bottom, there you will see that information is cutting.

Follow a picture:

![captura de tela 2016-08-21 as 13 28 42](https://cloud.githubusercontent.com/assets/560897/17838398/3f6795a8-67a3-11e6-96b7-885b5f104eb7.png)

**Comment by Garbee** [comment]
I'm not sure exactly what the "cutting" is referring to. If you are talking about the page overflow to the right, then yes that is expected since that is how tables work (which are used for the CSS class list.)

If that isn't what you are referring to, then please make what is happening and what you expect clearer so this issue can be assessed for re-opening.

Overall this doesn't seem like a critical issue therefore the team won't be taking any action as it stands since we are working on v2 heavily.

Thank you.

**Comment by luizfilipe** [comment]
Have you saw the bottom of the page?
There is information that is cutted.

**Comment by Garbee** [comment]
I'm unable to reproduce this here. Verify this happens without any extensions running. Also remember to refresh after enabling device mode so the meta viewport is taken into account by the engine.

Viewing the docs on mobile is not exactly a high-priority thing to address either. So, no internal action here will still be taken unless something provided by MDL is shown to cause this in other scenarios as well. As it is this is an edge-case within our docs only which aren't a critical priority given the circumstances.
