### ISSUE TITLE
Textfield Expandable Misaligned

### ISSUE THREAD

**Issue by juangl** [google/material-design-lite#4690]
Hello everyone.

I think that I found a bug in textfiled expandable. I saw it in [this template](https://getmdl.io/templates/dashboard/index.html). Also the same when I buld 1.x branch. 

 
![screenshot from 2016-08-21 20-04-41](https://cloud.githubusercontent.com/assets/1887029/17841090/8d0b06be-67da-11e6-8134-2da403fed271.png)

![screenshot from 2016-08-21 19-58-23](https://cloud.githubusercontent.com/assets/1887029/17841035/b2c0f0fe-67d9-11e6-894f-31b97042bac6.png)

- Browser: Google Chrome 52.0.2743.116
- OS: Archlinux

😘

**Comment by Garbee** [comment]
This is probably a regression from where I'm working on fixing another issue with the appbar height. However, it is a template-only piece of a non-specified piece of Material Design, therefore it is a non-critical issue. Due to that and the team focusing on v2, we won't be taking any action on this internally.

If someone from the community wants to debug and patch this, `mdl-1.x` is open for PRs.

Thank you.
