### ISSUE TITLE
Fire event when componentHandler is available

### ISSUE THREAD

**Issue by devilbags** [google/material-design-lite#4702]
I'm deferring the material.js file like this
```
<script defer src="https://code.getmdl.io/1.2.0/material.min.js"></script>
```
The problem is there is no way to find out when `componentHandler` is available. So when I try to dynamically add mdl component using `componentHandler`, it always results in error
 ```
componentHanlder is not defined
```
is it possible to add a event listener to be notified when componentHandler is available?

**Comment by Garbee** [comment]
Instead of the defer attribute you can simply move the script to the bottom of the page to resolve this problem.

The core team is focusing on V2 work fully and won't be addressing V1 problems going forward unless they are critical. As this is a feature addition it is non-critical.

If someone from the community wants to submit a patch for this, `mdl-1.x` is open for PRs.

Thank you.
