### ISSUE TITLE
FAB Animations and Transitions

### ISSUE THREAD

**Issue by VamosErik88** [google/material-design-lite#4704]
After closely reading Material Design guidelines regarding FABs [behavior](https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior) I noted that MDL is missing all FAB's animations and transitions both onLoad ("The floating action button animates onto the screen as an expanding piece of material, by default.) and on Tabs switch ("A floating action button that spans multiple lateral screens (such as tabbed screens) should briefly disappear, then reappear if its action changes.").
Do you plan on including these in MDL v2 release?
In the meantime I created those by myself and immediately used them in all my MDL related projects. You can check them at this [fiddle](https://jsfiddle.net/VamosErik88/yc2kcktp/)

**Comment by Garbee** [comment]
We know that we digress from the specification, however we will not be providing these entrance animations. The web does not allow developers to animate a node being created currently. So we would need to inject it as hidden in some way and then animate it showing.  Further, any interactions with the FAB are on developers to manage in their own way.

With v2 we will be providing the "FAB to bottom sheet" type of handling, so in that case we will provide the animation since it is what we are supporting by default.

Thank you.
