### ISSUE TITLE
Add a list of transition classes with Cubic Bezier provide by MD Doc

### ISSUE THREAD

**Issue by matheusdsm** [google/material-design-lite#4713]
For example, the class 'mdl-transition--standard-curve' should have a 'transition: 2s cubic-bezier(0.4, 0.0, 0.2, 1);' in desktops.

With cubic-bezier's provides by Google in Material Design document.

And responsive them, for example, in mobile all mdl-transition have a .3s duration.

Document especification for beziers: http://goo.gl/8qWw4X

**Comment by traviskaufman** [comment]
This is coming in V2. Check out our [mdl-animation package on master](https://github.com/google/material-design-lite/tree/master/packages/mdl-animation). However, we most likely won't be porting it back to v1, since the core team is fully-focused on moving forward with our next version of the library. 

Also note that not all transitions in mobile are of a certain duration; a transition's duration varies based on its properties, as per the spec:

> Rather than using a single duration for all animations, adjust each duration to accommodate the distance travelled, an element's velocity, and surface changes.
