### ISSUE TITLE
Reasons why I pulled the plug on MDL 1.x

### ISSUE THREAD

**Issue by Jossnaz** [google/material-design-lite#4715]
I will address this:

"we are a small team that's hyper-focused on delivering the best Material Design Library possible for the web"

well I will quickly list the 3 reasons that I came across in my _tiny_ project for why I had to pull the plug for any future websites for MDL. Don't get me wrong, I like mdl.. 

The main reason i pulled the plug on mdl is, it did not provide out of the box the very basic things one needs.

the 3 examples:

1. no styled select. Not even basic css styling. just nothing? wow ok, well i had to search myself for a solution. First disappointment. Then the solution i found didnt work well, i used something else, just plain css. Time wasted clearly.

2. no nested grid. Like really? again, i had to google, i had to search for it myself. There exists an easy solution http://codepen.io/tadashi1105/pen/MwPOJx , but why do I have to do the dirty work again myself? include the styles again myself? for each project? just the same like for the select.

3. I want to hide this complete element for phones. Oh there is no class I can put to hide it? well i can abuse `mdl-cell--hide-phone` and the like, but read the class definition. It is meant to be put on a cell. If i want to hide anything else than a cell, what do I use? that is so basic

now I started a new project and again was deciding between bootstrap and mdl. I generally like the work you guys did. But you know, I would for sure have to solve the same 3 hurdles again for no obvious reason.

**Comment by HriBB** [comment]
Yeah the "missing" select field was a WOW-moment for me as well :)
V1 is what it is. But I'm sure V2 will be awesome! Unfortunately we'll have to wait for it ...

**Comment by Sungodragon** [comment]
MDL v1 is  our primary front end library. Baring few things its great.
Currently we are using native select. But we are considering <paper-dropdown-menu-light>
https://github.com/PolymerElements/paper-dropdown-menu
But i have no idea how easy it will be to integrate.
Which select element is easy to integrate with mdl. ?

**Comment by Jossnaz** [comment]
> Baring few things its great.

well yes, but it's just plain stupid no nested elements, no select, no class to hide elements. What is this, mickey mouse?
> Which select element is easy to integrate with mdl. ?

it uses an input element under the covers:
https://github.com/CreativeIT/getmdl-select

**Comment by Sungodragon** [comment]
@Jossnaz 
Thank you for pointing it out.
I have been following MDL from day one and here was previous discussion which I am sure you must have gone through https://github.com/google/material-design-lite/issues/854

V2 already covers this which is great. 
It was mentioned that currently we should look for customizing it ourselves and thus I had not altered the native element. I want it to be friendly for Mobile, since that's where business is heading.
 
All the best guys.

**Comment by traviskaufman** [comment]
Hey @Jossnaz 

I'm sorry you've had an unfortunate experience using MDL 1.x. 

As a general response: we know that there are certain parts of MDL 1.x that are painful / hard to integrate. However, we're a team of two full-time googlers (plus one very active external contributor) working on this project. As of right now, we are actively working towards V2, which you can check out on our `master` branch. We've heard a lot of the concerns around v1 and have designed V2 to specifically address some of those issues (see #4578). Because we want to get v2 out ASAP, we really don't have that much time to make major changes to the v1 codebase. _If there are community members who would like to contribute components for v1, we are more than happy to help provide guidance and resources. Otherwise, we probably won't be making major changes to the v1 codebase except for bug fixes and documentation issues._

I encourage you to check out the v2 work we're doing on our master branch, check out our [milestones](https://github.com/google/material-design-lite/milestones), and if you're interested in seeing exactly what we plan on working on and when, check out our [public Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1664011) which shows a relatively solid timeline for v2 up to beta.

In regards to your specific points:

> no styled select

Many people have asked for this component, and we do plan on delivering it for v2 - #4475. Selects are hard, y'know? 😄 We need to think a lot about things like accessibility, reconciling expected behavior for selects for different user agents with the unified behavior of the component ourselves, as well as handling the case such as whether or not we should present a different option that actually _does_ use the native component directly, such as on Mobile Devices that implement a proper small-screen UX for their native `<select>` elements. All that aside, it'll be there before we launch alpha.

> no nested grid.

It's important to keep in mind that we are bound to the [material design spec](https://material.google.com). Our job is to take the components defined there and translate them into HTML/CSS/JS for the web platform. Unlike Bootstrap, our _core library_ tightly coupled to the components defined in this specification. Therefore, **if a component is not defined in the spec, it is very unlikely it will make its way into MDL.** We are planning on documenting this and making it an official policy for v2.

That being said, as shown with the linked codepen, it's quite easy extend MDL elements to accommodate your use cases. Our hope is that a community member creates her own library e.g. `mdl-nested-grid` that users can include which can extend the default MDL grid to make it nested. Again, we will be providing guidance on the best way to do this in v2.

> I want to [specific element] for [specific for factor(s)]

I know I sound like a broken record at this point 😉 but it's coming in v2! See #4496 . In the meantime, have you tried using the `mdl-layout--large-screen-only` and/or `mdl-layout--small-screen-only` modifier classes (see [here](https://github.com/google/material-design-lite/blob/7c7ba5c7deb736cad41a5fbcf7d8956725d0f316/src/layout/_layout.scss#L53-L57))? I know it's not exactly what you want but I figured it might help. 

I just want to re-iterate that we are working as hard and as fast as possible on v2. You can always use the resources above to track our progress, our reach out on [gitter](https://gitter.im/google/material-design-lite) if you want to have any follow-up conversations to anything mentioned.

**Comment by Garbee** [comment]
One other important thing to note is that MDL is not a framework. Our goal is not to provide every thought needed to build a site in one package. As far as the "hiding" problem, that isn't something we should be concerned with outside of the areas where it makes sense that content should be hidden.

We offer `mdl-cell--hide-phone` since it makes sense that a cell could either be needed or not on any given device factor. However, should we then provide `--hide-phone` options on every component? That will bloat the codebase up for not much gain in the way of usability. Also, a generic "helper component" where we dump these kinds of things doesn't make sense. It would quickly become overly-bloated with bad naming conventions, and be hard to document other than "kitchen sink".

Remember that everything we provide is scoped into specific components. We try to provide exactly what makes sense for any given component within that components space. Unless specifically dictated (buttons being children of dialog actions for example) we do our best to not cross the wires between components. That means we are more restricted in what we can do on developers behalf. However, that gives developers a big open field in their applications to do what is best for their needs. Without stomping on our targeting internally and fighting it.

Yes, I do realize the irony of the last paragraph given we have global resets and such that are relied upon in v1. Hence why getting V2 in a usable state is so urgent for us. We realized this mistakes but only after v1 launched and due to SemVer we could not go back and fix them without breaking things.

**Comment by Jossnaz** [comment]
@traviskaufman 

>no styled select
 yes i know selects are difficult. What people were asking for, was just that the select, that is shown when you are not even interacting / clicking the select item, is styled. Do you get what I'm saying? that's not hard to do. We are not asking for a fully fledged select that is eventually broken on some devices, but come on, the basic select styling is not difficult.

So what browsers is V2 targetted at? is it gonna work 'ok' that means that the user can use it, but it doesnt show optimal, on IE9? or is it another framework one only can use 2018+?

>it's important to keep in mind that we are bound to the material design spec. Our job is to take the components defined there and translate them into HTML/CSS/JS for the web platform.

you are talking like an intellectual. And it's a bad thing. Nested grids are so basic I want to knock my head against the table. Just pick up the phone, call the material design guys and ask them if it ever occurred to them, that there MIGHT be a section, within a section. In the terms used here, a nested grid. But just use the word 'sub section' or a 'section within a section'.  If that is not the case and you only get frowned upon by the material guys: stop working on this. Stop working on mdl v2 and quit.

@Garbee 

>One other important thing to note is that MDL is not a framework. Our goal is not to provide every thought needed to build a site in one package. As far as the "hiding" problem, that isn't something we should be concerned with outside of the areas where it makes sense that content should be hidden.

Every thought? to hide an element for smartphones is a random thought that only occurred to me? that is just intellectual egghead talk, it seems to me you worked on this, but you never actually have written a website with it. Hiding a random element that for example is part of the content of a cell, is so standard. That is not "every thought". I can't believe you are arguing against it. I honestly am disappointed. Say I have a short label for mobile phones, and a long label for desktop. Helptext for desktops. Maybe i use different components for desktop or smartphone (say, if i use my own menu). For desktop I typically show some data table-like in a grid with a row full of headers, and the table content below it.  For smartphone i hide the header row, and show the labels in each row.
Now i don't want u to support all of this, but give me the ways to hide an element without me having to write the things you were supposed to prepare for me.

The only thing you would have to do, is rename `mdl-cell--hide-phone` to `mdl-hide-phone`

but yes I understand that this does not go into your head, because it does not follow the BEM naming and thus is the same like starting a nuclear war.

you know what? i did my effort, I tried. You don't want because its against your religion? that's fine.

**Comment by Garbee** [comment]
I'm locking this issue. It is entirely condescending and unproductive to continue. Expressing your thoughts on how the project can improve is very much wanted. However, this is going into outright offensive/attack territory and that doesn't help anything.

Different projects focus on different requirements to make each maintainable to the team running them. One project may not suit your needs while another will. Thankfully there are plenty of options in open-source and you can try numerous other options, nor is anyone forced to use MDL. I hope another project suit's you needs better out-of-the-box so you don't hit the same problems you have experienced with MDL 1.x.
