### ISSUE TITLE
V2 strategy for site showcase requests

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#4734]
In V1, we had the concept of [user-submissions](https://github.com/google/material-design-lite/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20showcase) for inclusion on https://getmdl.io/showcase/index.html, but only got around to highlighting a few of the Google properties that shipped with MDL support. 

As submissions tend to be of varying quality, I might suggest that we move to just including user submissions in a wiki page that can be referenced but doesn't necessarily appear on the site. Thoughts, @sgomes?

**Comment by babywarez** [comment]
I know I'm not on the team but I think this is really important for inspiration purposes, especially when there is not an actual guideline for desktop and websites on the MD specs.

Why not have these submissions all in one place and then have them rated so you can move the best ones in one place on the official MDL website? so it's easier to find a good selection of MDL websites/webapps.

**Comment by Garbee** [comment]
Ratings can be faked and tricked. Plus that is extra infrastructure to build and maintain which is something we are trying to minimize.

One idea that has been kicked around here is we team up with the MD team on their highlights/whitepaper setup and push good Material Design sites through that system instead.

With a community wiki, anyone can create and edit any page. We will need to be careful monitoring this kind of setup as it shouldn't become a doc extension point nor anything it isn't intended to be. Otherwise, we could run into issues with the CLA being required for contributions.

**Comment by traviskaufman** [comment]
I personally like how bootstrap does this.

They have a dedicated expo site, with a [defined process](http://expo.getbootstrap.com/about/#suggestions) for taking in suggestions.

We could implement a system like this. We could do an initial screen of the site, and if we sign off on it, ferry it over to the design team. If they sign off on it, then we can add it in.

Thoughts?

**Comment by Garbee** [comment]
Yea. I'd rather if the process was a simple Google Form through into a sheet. Having the requests in the issue tracker can be quite distracting to keeping an eye on the technical work. That also gives reviewers some discretion since they don't necessarily need to respond publicly to requests. If something isn't good enough it just isn't good enough. No one's feelings get hurt with a public response to why it isn't accepted.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/18
