### ISSUE TITLE
Material icons not showing in Edge

### ISSUE THREAD

**Issue by CyberianIce** [google/material-design-lite#4774]
Hardware: Intel x86-64 (Reak McCoy, not a VM)
OS: Windows 10 Pro (x64) 1607 Build: 14.393.187
Browser: Microsoft Edge
Expected behaviour: I expected ti see nicely shaped material icons.
Actual behaviour: No material icon is shown, just tags, page loading is prolonged.

This may be related with https://github.com/google/material-design-lite/issues/1468 but with difference that this is now happening on real hardware to (not on virtual machine).

**Comment by traviskaufman** [comment]
Closing this at it seems like it's an issue with [material-design-icons](https://github.com/google/material-design-icons), rather than our library, which is for all intents and purposes a consumer of the icons. 

I would check your loading strategy for icons and ensure they're being loaded properly and the correct stylesheets are attached. 

Furthermore, if you believe that this _is_ a MDL-specific problem, please provide us with a test-case showing the icons working on IE/Edge without MDL and not working with MDL. If that's the case we'll be happy to reopen and investigate. Thanks!
