### ISSUE TITLE
Sass (and no CSS)

### ISSUE THREAD

**Issue by cekvenich** [google/material-design-lite#4795]
Why u no sass?

Even AMP shows GROW to uses Sass - and people doing this level of design have their favorite transpiler. 

So people have to modify your work.
1. And he links why http://github.com/markbirbeck/mdl-sass-mixins

2. Google: http://github.com/google/web-starter-kit/blob/master/docs/mdl-sass.md

3. etc.

If you just release Sass mixins for us to BEM.
Now, each of has to do that effort by self.

**Comment by traviskaufman** [comment]
We understand this is an issue, and have rearchitected our codebaze for v2 to make it much easier to support this use case. I encourage you to go check out the packages/ directory on the master branch, where you'll find individual pluggable sass files for every component, and whose sass dependencies are all installed via npm. We'll have more instructions on Sass integration as we get closer to alpha.

As for v1, as we mention in our issue template we will not be making any major changes to that codebase since we are actively working towards v2.

**Comment by cekvenich** [comment]
Thx Travis. We do not want components for @extend ('is a')
I mean composition ('has a') via mixins.

Even the name of this project is 'lite' and then you do heavy even in v2.

A few pages of examples of what we want:
http://google.com/#q=sass+mixin+library

Composition not inheritance. 'Has a', not 'is a'.
Right now when I do a AMP page via @extend Sass it's huge.
If you switch to mix in, it be only a few lines generated in AMP.

Anyway, that is best practice, I either go heavy or we all have to make our own mixins.

**Comment by traviskaufman** [comment]
The goal of Material Design Lite is to provide a library of components delineated in the Material Design Spec for the web platform. The goal is not to provide a sass mixin library. If you're looking for that then as you mentioned you may want to go with another solution like Bourbon or Compass.
