### ISSUE TITLE
Dialog Improvements

### ISSUE THREAD

**Issue by SayChunKim** [google/material-design-lite#4803]
Since Dialog doesn't work with few modern browsers which lack of polyfill support, i believe there'll be a need for workaround for modal dialog instead of approaching custom elements. And addition of transition/animation scripting may require for following MDesign guidelines.

**Comment by Garbee** [comment]
The polyfill is used since the `<dialog>` element is a W3C standard that provides exactly what is needed for them in an accessible manner with a clearly defined API. This reduces the amount of code we need to maintain and will help show other browsers that the dialog element is needed natively so they will implement it.

On the note of a custom dialog element, that would actually go in the opposite direction to using the dialog element polyfill. It would then require a polyfill of more intricate components and detailed setup which has less browser support than the dialog polyfill if a developer needs to support more engines. So, you'd include more and have more overhead while developing your application with fewer browsers able to use it.

Transitions and Animations are a little out-of-scope for the default dialog setup. The specification does not define how they should be animated in and in order to provide the most pleasing user experience their animation should fit with what the user interaction is that causes the appearance. Doing that internally is fairly intensive and would add a bit of weight to the codebase.

**Comment by traviskaufman** [comment]
Hey @SayChunKim 

We appreciate your input here, and will be revisiting this in #4486. In the meantime, as it says in our issue template we will not be making any major changes to our existing v1 components.

To @Garbee's point: the hope is that `<dialog>` eventually gets adopted by all browsers, and then we can remove the polyfill altogether. For that to work, dialogs would have to be robust enough to allow for the UX that Material Design mandates. We're still planning on using the dialog element for v2, but we're probably also going to wind up providing a more js-heavy fallback if people decide they cannot support it / don't want to use a polyfill.
