### ISSUE TITLE
Single-line text fields do not work with auto-filled form fields

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4827]
<img width="493" alt="screen shot 2016-10-06 at 11 43 39 am" src="https://cloud.githubusercontent.com/assets/1185269/19159362/23eb9b40-8bba-11e6-85c9-0270c7741817.png">

I tried detecting this via change events which didn't work. I also tried checking for `value` on init but that only worked for non-password inputs and was non-deterministic in terms of its timing.

Possible workarounds:
##### Style for `:autofill`

This is clearly the most elegant solution, but looks like it's [Chrome only](https://developer.mozilla.org/en-US/docs/Web/CSS/:-webkit-autofill)
##### Have elements poll to check if they're auto-filled

This will lead to the highest design fidelity, but is extremely inefficient and will incur a significant performance impact, especially on mobile browsers.
##### Tell users to set `autocomplete="off"`

This would in theory solve the problem. However, it is not only an inconvenience to the user, but it's [not guaranteed to work correctly](http://caniuse.com/#search=auto) for all types of input.
##### Tell users to only use JS-enhanced single-line inputs with form fields that won't be auto-completed

😢

**Comment by nj3ma** [comment]
Original Message                                                                                                                                                                                                                                                                                                                                                                                                                                                                     From: Travis KaufmanSent: Thursday, 6 October 2016 18:51To: google/material-design-liteReply To: google/material-design-liteSubject: [google/material-design-lite] Single-line text fields do not work with auto-filled form fields (#4827)

I tried detecting this via change events which didn't work. I also tried checking for value on init but that only worked for non-password inputs and was non-deterministic in terms of its timing.

Possible workarounds:

Style for :autofill


This is clearly the most elegant solution, but looks like it's Chrome only

Have elements poll to check if they're auto-filled

This will lead to the highest design fidelity, but is extremely inefficient and will incur a significant performance impact, especially on mobile browsers.

Tell users to set autocomplete="off"


This would in theory solve the problem. However, it is not only an inconvenience to the user, but it's not guaranteed to work correctly for all types of input.

Tell users to only use JS-enhanced single-line inputs with form fields that won't be auto-completed

😢 

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/google/material-design-lite","title":"google/material-design-lite","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/google/material-design-lite"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Single-line text fields do not work with auto-filled form fields (#4827)"}],"action":{"name":"View Issue","url":"https://github.com/google/material-design-lite/issues/4827"}}}

**Comment by mellogarrett** [comment]
I am also seeing this issue.

I'm using mdl within an Ember app, and pre-populating an 'edit' form.

Is there a way to manually initialize the form again?

**Comment by traviskaufman** [comment]
@mellogarrett are you using mdl-1.x or v2?

**Comment by traviskaufman** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/137
