### ISSUE TITLE
Best practice for search suggest/autocomplete?

### ISSUE THREAD

**Issue by benguild** [google/material-design-lite#4846]
Hi, is there a best practice or component for having a drop-down menu appear for search queries in a MDL-styled `<input>` tag, or is this not part of MDL at this time? Was just wondering, thanks. Been checking things out and this looks really cool.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

This is not provided internally at the moment. The community on SO may be able to help you put something together since I know others have already built their own solutions for this.

Thank you.

**Comment by benguild** [comment]
Will do, thanks!
