### ISSUE TITLE
Footer contrast doesn't pass WCAG AA

### ISSUE THREAD

**Issue by boyum** [google/material-design-lite#4854]
The contrast ratio between the footer's default foreground/background color (`#9E9E9E` / `#424242`) is not great enough to pass [WebAIM's Color Contrast checker](http://webaim.org/resources/contrastchecker/). A value such as `#D8D8D8` for the foreground color will make it pass both WCAG AA and AAA, with a contrast ratio of 7.05, but then again might not give the wanted impression.

In [issue #4006](https://github.com/google/material-design-lite/issues/4006), the footer color is discussed, and you might not want to use time on this matter if you are planning to do a total remake of the footer component.

I could very well file a PR for this, but as I know very little about MD's philosophies, I do not know if it is worth the time.

**Comment by Garbee** [comment]
Footer is being removed in V2 as it is not an MD specified component. For 1.x it will remain as-is since changing the color could lead to issues with other things developers have built or any visual tests that are in place.

Thanks for the report, however there won't be any action taken here internally. Change this as-needed within your own projects manually.

Thank you.
