### ISSUE TITLE
Expandable menu not suitable for navigation links?

### ISSUE THREAD

**Issue by jsenkyrik** [google/material-design-lite#4864]
Hi everyone,

I'm trying to use MDL for a modest web app that would help people learn English idioms.

www.idiomgenerator.com

My question is about the expandable menu component at the top-right corner of the page: I've noticed that it behaves rather unpredictably, with links not always taking user onto other pages upon a click.

The `<a href>`s are there and correct, and it shouldn't be hard to reproduce the behavior if you use the menu for a while (you click the link and nothing happens when it's supposed to take you to a different page).

From my testing, this happens across all modern browsers (including Firefox, Chrome and IE).

**Is the expandable menu even suitable for replacing the traditional nav items as seen on my website?**

Many thanks for your guidance!

Jakub

**Comment by Garbee** [comment]
It is probably erratic since your anchors are constrained to the text size itself. So if you click the list item and not the anchor, the menu just closes.

You probably shouldn't use the menu like that, the drawer (as you have it) is a better fit. Also, it works on mobile and the button does not.

As this isn't a problem with the core code we provide, more assistance can be provided by users on StackOverflow. This issue tracker is only for problems with the code we provide. Support and integration assistance should be handled in external community channels as the core team can't handle the load of that directly.

Thank you.

**Comment by jsenkyrik** [comment]
You are right @Garbee , I didn't realize the anchors are to be blamed and thought this was a bug in the code -- hence why I posted this question here. 

Nothing that a short CSS code wouldn't fix. It's working properly now. Thank you!
