### ISSUE TITLE
Highlight of tabs

### ISSUE THREAD

**Issue by jecisc** [google/material-design-lite#4970]
Hi,

In the layouts components, the tabs are really cool but it's not always obvious for everyone that we can click on them. 

I think it could be cool to change the color of the text when we hover on them. 

In the application I contribute to we had white tabs with black text with an alpha. We added a property on the hover to make the text pitch black. 

I think this should be part of MDL directly. What do you think?

**Comment by Garbee** [comment]
The Material Design specification frowns upon hover-only methods to do things. In fact, it generally is outright against them favoring a touch/click method of interaction since that is available everywhere.

Our tabs adhere as much as we can to the [Tab specification](https://material.google.com/components/tabs.html#tabs-specs) so unless there is something in there we can be doing better (V2 should be fully-conforming to what is required) then there is no action to take here internally.

MDL's goal is to provide the most accurate representation of the MD specification we can for the web possible. Anything not in the spec (or designed against the spec with good reason) is not something in the scope of the project.

**Comment by sgomes** [comment]
As @Garbee mentions, adding a hover state might unfortunately mean straying a bit too far from the Material Design spec as an official implementation.

That said, Material Design isn't about super-strict rules for everything, and there's definitely room for tweaking the designs to your needs, so please go ahead and add the hover aspects to your application! As a library, though, we have to be a bit more conservative in our approach.

Thanks for the suggestion, @jecisc!
