### ISSUE TITLE
Opera 12 support

### ISSUE THREAD

**Issue by Abradoks** [google/material-design-lite#4986]
Opera 12.18 is the latest version of the Presto engine. Please, test against it, as you are claiming to "gracefully degrade in older browsers".

In particular:
* https://getmdl.io/ the site menu disappears;
* https://github.com/google/material-design-lite/blob/mdl-1.x/src/radio/_radio.scss#L104 use scale() instead of scale3d().

**Comment by sgomes** [comment]
Thank you, @Abradoks! Unfortunately, we can't do any extensive testing on Opera 12, but we're happy to review any PRs. Any chance you could submit the `scale()` fix as a PR? :)

**Comment by Garbee** [comment]
I think there is a difference between "gracefully degrading" where possible and supporting an years-old engine that even the company that built it is no longer doing themselves. It's akin to asking for things to work in Netscape Navigator at this point.

The Presto engine is dead and making modifications to support that needs to be made very carefully. Any changes can't cause breaking changes for anything existing with MDL deployed. If there is even the chance of something breaking externally, we can't merge a change in.

This really comes down to being secure in knowing we can feasibly maintain and verify future patches. Let's say a merge comes in to fix something in Presto. That causes something else to break. Are we to just revert the patch and leave Presto back in a broken state? Or are we to try and find a way on our own to resolve the issue to maintain support for both? Or do we tell existing developers their things may be messed up but they're stuck having a breaking change come down because Presto needed to be supported? Either way, it is a bad situation and projects just don't have the manpower to handle supporting engines that are no longer being maintained.

I don't think there is an issue with not having Presto support baked in. If people see they have a large set of users still using that, then that is one point of assessment they should make before choosing their tools to build the application.

**Comment by Abradoks** [comment]
And I think that there is a difference between "aiming to gracefully degrade" and being lucky if some parts of the framework work.

In the first example the project's main page becomes unusable because of some z-index issue.

In the 2nd example all radio boxes on a page would appear checked, because the browser doesn't support 3D Transforms. 3D Transforms for radio boxes to work.

One might expect such issues to be prevented by the use of the frameworks, not created by them.

Unfortunately, that claim about graceful degradation and the fact that you test your framework in IE9 and IE10 (both were released before Opera 12.10) mislead me into wasting my time to bring these issues to your attention. Clearly, you just do not care.

**Comment by sgomes** [comment]
@Abradoks We definitely care about graceful degradation not happening properly, and we're happy to implement any fixes that improve the situation, provided that they work in modern browsers too, and don't break backward compatibility.

Unfortunately, we do not have the resources to research, test and implement those fixes ourselves, but again, we're happy to review any PRs.

**Comment by sgomes** [comment]
Closing this issue as the immediate concern with `scale()` vs `scale3d()` has been solved. Happy to review any other PRs that improve compat without breaking modern browsers.
