### ISSUE TITLE
Layout > Header

### ISSUE THREAD

**Issue by EduardoAC** [google/material-design-lite#4996]
The main issue I found right now using mdl-1.3.0 is related with the couple architecture between layout and header.

Right I tried to split the header from the layout in order to build a set of React components but the true is that I couldn't resolve this without extra CSS on the top of the framework because the framework is targeting child class using > operator that reduce the flexibility.

Example
```
@media screen and (min-width: 1025px)
.mdl-layout--fixed-drawer > .mdl-layout__drawer {
    transform: translateX(0);
}
```

My issue description is looking forward for future MDL version 2, the layout component are really important to build any application that means that should be about to be generic and be able to nest them a lite bit.

Problem example (Tags are classes from MDL)
```
<Layout>
  <div>
     <header>
      ....
     </header>
     <Drawer>
     ....
     </Drawer>
  </div>
</Layout>
```

I know they will be problems related with ```display``` and other CSS classes however it should be flexible enough.

What do you think?

**Comment by Garbee** [comment]
In Material Components for Web (previously MDLv2) there is no "layout" component. All components are isolated independent features.

The layout in v1 is a long-standing sore point. However, due to backwards compatibility we aren't able to go fixing it since that would break all existing sites that may have things depend upon how it is done already.

You can check out the [MDC components](https://github.com/material-components/material-components-web) and try playing around with what we currently have to see if they work for your needs. Some pieces are still not there like the application bar for the top of the page. That should be simple enough to mock up for testing though.

Thank you.
