### ISSUE TITLE
How to Fix the Tab bar at top when scrolled down

### ISSUE THREAD

**Issue by asinan007** [google/material-design-lite#5010]
I would like to know how this can be done for a tab bar created in mdl-layout__content  with mdl-tabs__tab-bar.

Any help would be appreciated :)

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this is unrelated to the features provided by MDL, it is integration assistance which requires custom code. This is out of scope since we don't have the ability to handle everyone's support requests. StackOverflow is much better for this kind of stuff since the answers are easily searchable to help others as well.

Thank you.

**Comment by asinan007** [comment]
Oh ok, thank you.
