### ISSUE TITLE
stance on CSS-only ?

### ISSUE THREAD

**Issue by Download** [google/material-design-lite#5036]
Hi guys, just wanted to ask you a question about css-only design.

Please have a look at this (demo) project:
http://mildrenben.github.io/surface/

It is built to function even without Javascript enabled. The big (imho) advantage of this is that is has the best time-to-interactive performance possible; even before the JS loads, it functions as expected.

I understand it is a pretty hefty requirement, but Surface proves there is a lot that can be achieved this way. If only the most important components (such as the drawer) would work like this, it would still give a great benefit.

Have you given this any consideration? And can you maybe share your thoughts on this?

**Comment by ZanderBrown** [comment]
That. Is. Seriously, Cool.

**Comment by rofrol** [comment]
Nice, but clicking second time in button doesn't cause ripple effect.

You can use `a:active` like here https://mladenplavsic.github.io/css-ripple-effect/ to have ripple on every click.

**Comment by Garbee** [comment]
MDL won't go CSS-only from the team as it is in community support only at this point and to refactor everything needed is an extreme task. Also considering the browser support for 1.x only using CSS for quite a few components isn't feasible to match MD guidelines.

Material Components for Web should support CSS-only as much as possible (especially in regards to forms) and enhance from there for full fidelity with JavaScript. As explained in the issue upstream.

We aren't currently planning any major revisions to MDL, which would be required with such a change being made, since the deploy process is arduous. The focus is on Material Components for Web since it has a streamlined deploy process and is moving the project to be an actual reference implementation over "just another project."

Thank you.
