### ISSUE TITLE
Dialog Default Button not setable

### ISSUE THREAD

**Issue by MentalGear** [google/material-design-lite#5046]
Is there any way to tell the dialog not to focus a button by default ?
In this example, the close button is focused which can be noticed by the higher shadow.
( click somewhere outside the button so it blurs and shows the desired state )

http://codepen.io/anon/pen/PpPOdx

**Comment by Garbee** [comment]
This isn't possible and won't be because it creates an accessibility issue. It is by the standard on how dialogs should work by trapping focus and making the first focusable item within the dialog focused. This is useful for users who use keyboard navigation to be able to work with the dialogs when they are shown.

We understand it seems visually odd to many users, but accessibility needs to come first for users.

Thank you.
