### ISSUE TITLE
I am using vueJs and when I change route , mdl components are not getting upgraded

### ISSUE THREAD

**Issue by sagarkbhatt** [google/material-design-lite#5074]
I am using vueJs and when I change route, mdl components are not getting upgraded

I have tried upgradeDom and upgradeElement but it has no effect.

**Comment by ZanderBrown** [comment]
#5073?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this is a problem with integrating MDL with 3rd party code and your application itself, this is a general support question. These are out-of-scope for the issue tracker since we only handle problems with the code distributed by MDL itself here.

Thank you.
