### ISSUE TITLE
MDL dialog browser support?

### ISSUE THREAD

**Issue by virtapoika** [google/material-design-lite#5099]
Hi! I'm planning to make a project with mdl. I'm having a question about the dialogs which are going to be an important part. Is there some graph where's the support ranges per browser?

Thanks!

**Comment by ZanderBrown** [comment]
[CanIUse](http://caniuse.com/#feat=dialog) but remember polyfills are available for `<dialog>`

**Comment by ErickRuano** [comment]
Please note that in order to work with the recommended polyfill you MUST have your dialogs be inmediate children of <body> or else it won't work properly, or at all.   If this setup doesn't work for you, which was my problem, I can share a polyfill I wrote which is not currently public at github but if you or anyone reading this wants to give it a try I would gladly make some time tu re-publish publicly.

**Comment by Garbee** [comment]
@ErickRuano AFAIK the latest version of the polyfill removes that drawback. It should work just fine now in any configuration with MDL as long as you have the latest polyfill.

Also closing this out since there isn't anything to be done internally about this.
