### ISSUE TITLE
Better Showcase of Examples

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#5136]
Several months ago I read that MDL v2 is in development. I don't think it's been released yet - and I think you're working on it.

But I wanted to comment that MDL v1 is pretty amazing in itself. I also wanted to add that the elm-mdl project has done an amazing job showcasing in-depth examples of the work that you all have done on this project.

So, regardless of whether v2 of MDL does ship, please review the polished showcase of examples of elm-mdl. I often go to look over there for examples of what I can do with MDL.

**Comment by ZanderBrown** [comment]
MDL V2 isn't happening, MDL is being replaced by Material Components for Web

**Comment by Garbee** [comment]
>MDL is being ~replaced by~ Material Components for Web

MDL has evolved into Material Components for Web. The V2 base is now the foundation for MCW.

MDL is no longer actively maintained beyond a few lagging things to be done as there is no more time allocated to it internally since MCW is taking over the goals of MDL. We won't be making any major modifications to the examples, showcase, or microsite. 

Thank you.
