### ISSUE TITLE
Drawer does not overlap header

### ISSUE THREAD

**Issue by miguelsmuller** [google/material-design-lite#5141]
I have a question, I can not find a solution.

I have to create a layout where the drawer and header are fixed and visible on the desktop. The drawer also can not overlap the header (figure 1). In Mobile the drawer starts invisible.

![captura de tela 15](https://user-images.githubusercontent.com/4589909/28591969-ebabdb20-715d-11e7-9af4-58b763857c3a.png)

On the desktop, the drawer will never be invisible. Instead I would like it to be reduced only. (Figure 2)

![google-hire](https://user-images.githubusercontent.com/4589909/28591974-f2a90a38-715d-11e7-9027-f7665a0b435c.png)

The drawer will only be invisible on the mobile.

**Comment by Garbee** [comment]
This kind of thing is not supported in MDL. Nor will it be supported here. Material Components for Web should eventually allow for this type of thing to happen.

Since this isn't something we'll be allowing for within this project, it falls as a support question. Which are best left to StackOverflow. But really, you're looking at quite a bit of manual code/overriding to handle this. You'd probably be better off if you need to stick with MDL writing your own application bar and drawer implementations.

Thank you.

**Comment by miguelsmuller** [comment]
With MDL I can not make a drawing screen and a drawing in those that in the [Material Design specification](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior)?

Navigation drawer clipped under the app bar: Apps focused on productivity that require balance across the screen
![image](https://user-images.githubusercontent.com/4589909/28598491-4e1a6a4e-717a-11e7-9137-bf94d12f471f.png)
