### ISSUE TITLE
Where is the Datepicker ???

### ISSUE THREAD

**Issue by nl20121974** [google/material-design-lite#5159]
Read every issues about it. All are closed and dated 2 years later.

What's going on ? Will we have it as proposed in material design ?
Isn't it a form's standard component ?

Regards, Nicolas

**Comment by Garbee** [comment]
Material Design Lite is no longer actively maintained. [Material Components for Web](https://github.com/material-components/material-components-web) has superseded it and will eventually have full component parity. As MCW is a true reference implementation of the components for the web.

With going into a deprecated state it was decided that including new large components like the Datepicker wasn't a good choice. Since they are certain to have issues that would need to be actively looked over for a while to make sure the components are well done for users. So, we decided against importing any new components with complex structures.

Thank you.

**Comment by gregblass** [comment]
Serious question - why has a depreciation message not been put on the material design lite webpage, front and center?

**Comment by NBurke1** [comment]
Just had this exact problem, spent 35 minutes trying to find why nobody had implemented a proper Select list yet...only a wayward comment about MDC put me on the right path.

There are still plenty new adopters for Material Design, and they are installing and using a deprecated framework and have no idea.
