### ISSUE TITLE
How to Show menu on Mouseover ?

### ISSUE THREAD

**Issue by teknosains** [google/material-design-lite#5169]
Currently it only accept onClick action to open Menu

https://getmdl.io/components/index.html#menus-section

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As the Material Design specification states to only use click/touch triggers for actions, what is provided is in alignment. Hover is not encouraged since it is a mouse-only action and is not an explicit user request for something to occur. Therefore it isn't something to be supported internally.

Thank you.
