### ISSUE TITLE
Checkbox not adding "checked" attribute to input

### ISSUE THREAD

**Issue by dedupely** [google/material-design-lite#5214]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
v1.3.0

> What browser(s) is this bug affecting (including version)? 
Chrome

> What OS (and version) are you using?
Mac OSX High Sierra

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Click on a checkbox, then look at it in inspector

> What is the expected behavior?
that "checked" attribute is added to <input when clicking on the checkbox.

> What is the actual behavior?
No "checked" attribute seen.

> Any other information you believe would be useful?
Makes the checkbox useless for serializing post data.

**Comment by Garbee** [comment]
If you put the following into your omnibar and do the same thing test, you'll see the checkbox doesn't have it's attribute updated. MDL reflects that from the browsers.

```
data:text/html,<input type=checkbox>
```

What makes you expect this behavior? Does another browser modify the attribute state? If so, that's problematic since unless they internally track changes it messes with a form reset event. Since attributes are what are used to reset the form state for the user.

**Comment by dedupely** [comment]
You're right, it doesn't show checked in realtime. My bad. Closing this.
