### ISSUE TITLE
Update specs for Cards on Components Page to match templates

### ISSUE THREAD

**Issue by santokii** [google/material-design-lite#649]
* [x] Change mdl-card__title-text font weight to 400
    * Happening in custom PR due to serverity and it being an upstream issue from demos.
* [x] Change mdl-card__supporting-text  color to: rgba(0,0,0,.54);
* [x] Change demo-card-image__filename font-size to: 14px; and   font-weight to: 500;

* [x] Top align Event card and add calendar icon:
![image](https://cloud.githubusercontent.com/assets/11649557/8498265/9dc81c62-217c-11e5-858c-ecf3a6532c51.png)

**Comment by santokii** [comment]
Changing this to a P0 because the text in the card is not to spec and should be updated before someone uses it - should have caught this earlier... my bad!

**Comment by Garbee** [comment]
> Text in card is not to spec

Is this relating to the font weight being off for all cards? (i.e. this should be added upstream in the main card classes.)

**Comment by santokii** [comment]
Yeah, apologies for not being specific... We never really use font-weight 300 / Roboto light for cards. The minimum font weight for anyhting less than 112pt should be using is 400 / Regular

**Comment by Garbee** [comment]
Ok, I'll get that fixed directly in a PR since it is global for all cards. The rest of these issues seem specific to the example which I'll live for this issue to address.

**Comment by santokii** [comment]
Perfect. Thank you!!!!!!!!

**Comment by Garbee** [comment]
PR submitted for that fix. Issue #738 for those reading email.

**Comment by Garbee** [comment]
If Surma isn't already working on it, I'll go ahead and try to fix the example issues as well real quick in a second PR since those aren't as major as the mis-alignment from the spec.

**Comment by Garbee** [comment]
@santokii Working on the other things, looks like top alignment is also an upstream fix. Should all titles be top aligned or is there something special about this case where it shouldn't be?

**Comment by santokii** [comment]
This might not be the case for cards with an image on the left, so let's make this a separate style. Thanks!

**Comment by Garbee** [comment]
So, if it may not be the case for certain kinds of cards then I'm content with addressing it in the example styling with the rest of the problems as `P1` PR. Since what we have for alignment made it up to launch, it seems to be appropriate (or maybe we all just missed something pretty major between spec & implementation.)

If there are any issues upstream, we should compile a list of issues and address them as best we can within our release cycle. I already have tons of wish-list ideas to handle more modes/configurations easily, but these ideas are for another major drop.

**Comment by Garbee** [comment]
I goofed here, sorry.

Card titles are not in alignment. They are set to center within the flex area which is wrong. Looking over the spec page again, I don't see any instance of this. I think due to things looking right in the demos before since they were simpler, I assumed it was correct when it wasn't.

We need to align to flex-start not center. Then the ones with images in the title area, they need a modifier to align to bottom.

This fix however, can cause quite a bit of breakage in our existing templates. Not sure of the best approach to solve the problem unless we implement the fix and update templates as-needed before 1.0.1. Otherwise, looks like SemVer (since it is a breaking change) would show we hack this fix in and address it in 2.0.

cc @addyosmani for opinion on attack plan.

**Comment by Garbee** [comment]
Since the patch is now far out from launch, I don't think we can do a quick under-change. Let's move forward with specifically fixing this demo as-needed and I'll make a new issue for the next major to do the BC break of title alignment.

For 1.x, we just live with the title being off if the title block has a sizable height.
