### ISSUE TITLE
Floating action buttons on cards and other block elements.

### ISSUE THREAD

**Issue by EHLOVader** [google/material-design-lite#737]
It would be nice to see the ability to add floating action buttons to footers and headers which hang outside of the elements.

Also useful on cards in multiples.

Header floating action button (demonstrates the alignment with action buttons on list items.)
![header floating action button](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsS2J0RmRySnJfZTg/patterns_actions_fab2.png)

Footer floating action buttons
![footer right aligned floating action button](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsQUxBamxwdy15Vlk/patterns_actions_fab1.png)

Centered floating action buttons
![centered floating action buttons](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsRXJZU1FpSm00WHc/patterns_actions_fab_content3.png)

Images from [Material Design spec](http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button)

**Comment by Garbee** [comment]
Set MD Alignment tag since the action aims to make implementing MD easier. While currently possible with custom code, we should be able to handle this somehow automatically within the component.

**Comment by Garbee** [comment]
Since the exact placement of the edges is going to vary based on numerous factors, this is something that should be handled in custom code.

I am not finding an elegant way to align things properly while still being high performance.

Developers will just need to use absolute positioning on their own if they want the button to sit on top of other elements.

If someone can come up with a clean solution for this, PRs welcome.
