### ISSUE TITLE
Spinner not correctly rendered 

### ISSUE THREAD

**Issue by weiway** [google/material-design-lite#771]
<div class="mdl-spinner mdl-js-spinner is-active"></div>

Spinner component not correctly rendered, only showing "Loading"

**Comment by Garbee** [comment]
What browser (and version) are you using?

**Comment by weiway** [comment]
Chrome Version 43.0.2357.130 (64-bit)

**Comment by Garbee** [comment]
That is very odd. And this is reproducing for you with the [component page](http://www.getmdl.io/components/index.html#loading-section/spinner)? Or is this in your own code?

**Comment by weiway** [comment]
In my own code

**Comment by weiway** [comment]
I'm trying to use MDL with Angular. All the CSS and Javascript files are declared in the head of index.html. The spinner in Angular partials views will only show "Loading".

**Comment by Garbee** [comment]
This issue is for general support which this tracker isn't meant for. Please use StackOverflow and use the `material-design-lite` tag (along with other applicable tags) to try and get the best support.

**Comment by gnomeontherun** [comment]
For what its worth, the problem is that Angular templates (or any library that manages templates) aren't ready when the material design lite components are setup (which happens `onload`). You could address this in Angular by calling the method to setup the components each time the view changes (approach varies on what router you use), or you really would be best by wrapping them in a directive. Ultimately, probably best to use Angular Material.

I'm toying with this and Angular 2, and I can get the loader to work like this. The important part is I call `componentHandler.upgradeAllRegistered();` after the template has been rendered (I use setTimeout to bump the call to the end of the call stack). So your directive could wrap the MDL components, and always call the upgrade method to bring the components to life.

```
    setTimeout(function() {
      componentHandler.upgradeAllRegistered();
    })
```

**Comment by weiway** [comment]
@gnomeontherun 
A very good stackoverflow discuss on this question:
http://stackoverflow.com/questions/31278781/material-design-lite-integration-with-angularjs

**Comment by kurapatijayaram** [comment]
We need to use componentHandler.
For example:
import {Component, OnInit} from '@angular/core';
declare var componentHandler: any;

@container({
//Some configuration 
})
export class ExampleComponent implements OnInti{
    ngOnInit(){
         // I am sure that upgrading all the MDL components is a bad idea.
         componentHandler.upgradeAllRegistered();
   }
}

This works fine.
Correct me if I am wrong.
Thank you.
