### ISSUE TITLE
Stylus Version?

### ISSUE THREAD

**Issue by srsgores** [google/material-design-lite#775]
Any plans for Stylus support?

**Comment by Hendrixer** [comment]
Stylus > any other pressprocessor

**Comment by surma** [comment]
Since we are still doing a lot of refactoring, adding new components and other intrusive tasks, maintaining another preprocessor is not viable at the moment. We don’t plan to support Stylus ourselves in the near future.

The SASS code of MDL is mostly targeted at MDL developers as we expect anyone else to just use the compiled, vanilla CSS we provide. So you can still use Stylus for the rest of your website of course.

**Comment by xdissent** [comment]
If you're still interested, I created a stylus port: https://github.com/xdissent/material-design-lite/tree/stylus
