### ISSUE TITLE
MDL component design pattern 404

### ISSUE THREAD

**Issue by sgentle** [google/material-design-lite#779]
I notice a few places [like ripple.js](../blob/master/src/ripple/ripple.js) reference the "MDL component design pattern". However the link it references (https://github.com/jasonmayes/mdl-component-design-pattern) is a 404.

Is there a publicly available reference somewhere for the MDL component design pattern?

**Comment by Garbee** [comment]
There is some basic reference material in the wiki at the moment.

[How the component handler works](https://github.com/google/material-design-lite/wiki/How-the-Component-Handler-works) and [Making your first JS component](https://github.com/google/material-design-lite/wiki/Making-your-first-JS-component).

These are early work and do have quite a bit not explained fully/intentionally left out due to complexity. But they should be enough to get started with understanding the system.

**Comment by surma** [comment]
@addyosmani @jasonmayes Is it fine to just set the link to <https://github.com/jasonmayes/wsk-component-design-pattern> or is that outdated?

**Comment by jasonmayes** [comment]
It was never called mdl-component-design-pattern - before we had the name I called it wsk-component-design-pattern. My guess is someone did a find replace for wsk :-) My original repo is still here: https://github.com/jasonmayes/wsk-component-design-pattern

**Comment by jasonmayes** [comment]
Update I have now claimed the new link. I shall push a copy there and redirect the old named one to the new one which makes sense.

**Comment by jasonmayes** [comment]
Update: It should now be cloned to the right location.

**Comment by surma** [comment]
@jasonmayes Thanks man! Closing this.
