### ISSUE TITLE
CDN not returning gzipped files

### ISSUE THREAD

**Issue by wanacode** [google/material-design-lite#843]
In the getting started Hosted option it says

> Just add the following link and script elements into your HTML pages (27kB gzipped)

```
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-pink.min.css">
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

I am not receiving gzipped files and is over 170kB. Is this something wrong with the CDN or something else?

**Comment by nicolasgarnier** [comment]
That's right :(

http://checkgzipcompression.com/?url=https%3A%2F%2Fstorage.googleapis.com%2Fcode.getmdl.io%2F1.0.0%2Fmaterial.indigo-pink.min.css

![image](https://cloud.githubusercontent.com/assets/3766663/8560272/6dc72cea-2516-11e5-8ba5-248a4c5c9e4c.png)

@marcacohen I remember we enabled Gzip at some point and http://getmdl.io does have gzip enabled. Since these are hosted on a different GCS bucket than the website it seem we may have overlooked it?

**Comment by nicolasgarnier** [comment]
Thanks for the report @wanacode :)

**Comment by janpieterz** [comment]
I think #850 is also related to this.

**Comment by marcacohen** [comment]
Compressed assets was already fixed in our gulpfile.js. I was able to resolve this by re-pushing the assets and they all now appear to be compressed and we're saving 85% on network bandwidth (and storage). Thanks @wanacode !
