### ISSUE TITLE
Copy/paste in docs has issues in Firefox and IE

### ISSUE THREAD

**Issue by ggrks** [google/material-design-lite#848]
I've just visted the link [Material Design Lite - buttons](http://www.getmdl.io/components/index.html#buttons-section)
~~I'm so suprised to find that the ripple animation is using a swf file since I'm using the latest version of chrome on a macbook, and the animation is too fast to be noticed.~~
~~CSS animations are supported in latest browsers (including IE10) and google chrome are planning to drop the flash support (Apple's Safari already does this), I think it would be better if use css animation instead of flash. :(~~
thanks to @mkhairi @steven-qi 's mention, the flash file is for coping the code snippet. It's a bad idea to use adobe flash in a website like this.

**Comment by innerpeace0** [comment]
I don't see any ripple, either. I have flash set to ask before running (since most of it is ads), but I get no request on that page to run flash.

**Comment by mkhairi** [comment]
i guess the swf file is  just for copy snippet option.

**Comment by steven-qi** [comment]
I think that @mkhairi is right. The flash file is for 'copy to clipboard', and cause issue on IE11 as well.

**Comment by steven-qi** [comment]
Just tried. It doesn't work on latest Firefox either... Looks like that they are only testing on Chrome.... :disappointed:

**Comment by ggrks** [comment]
@mkhairi  @steven-qi  yeah I'm wrong, the flash file is not for the animation.

**Comment by ggrks** [comment]
I think it's still a very bad idea to use flash even it's for 'copy to clipboard'.

**Comment by PaulHMason** [comment]
The FAB is broken in Firefox (appears to be the icon font).

**Comment by addyosmani** [comment]
The only way to achieve cross-browser copy/paste at the moment is to unfortunately use Flash. We hate that we have to, but the native way to achieve this isn't supported in Safari or IE :/ We'll debug what's breaking here.

**Comment by addyosmani** [comment]
@PaulHMason could you file a bug with the breakage you're seeing? We should keep each issue focused on the specific problem raised :)

**Comment by addyosmani** [comment]
Some further notes:

* @nicolasgarnier Let's spend more time evaluating each of our target browsers to double-check where clippy.swf is failing atm. As you know, despite being one of the smallest shims for this behaviour, it also isn't actively maintained (see date of [last commit](https://github.com/mojombo/clippy)). I'm hopeful the reason this isn't working is something on our end we can fix via JS, but if not we'll either need to find an alternative or drop copy/paste support. 
* I'm curious what the initialization cost of each Flash object is per page and how much this impacts some of the performance in issues we're seeing in the components page. I'll try taking a look at this independently so we at least know what the cost of using clippy is at runtime.

**Comment by nicolasgarnier** [comment]
+1
Also I am planning to start tracking how many of our users have flash enabled via a Google analytics event. This way we'll know the amount of visitors who have flash enabled. I just done it on one of my project and It seems around 75% have flash enabled. Since we have close to that of visitors using Chrome it might make sense to only support this via the native API just for Chrome users, we'll get a similar share of users with the copy-paste feature without sacrificing on performance and without scaring users with flash blockers :)

I had checked the initialization cost of flash and it was very small but since we add an element for each copy paste button and we now have a lot more snippets than when I checked initially I'm sure it started having some impact. To mitigate this and if we want to keep Flash for this we could inject the flash on the fly when the user MouseOver one of the copy paste button instead of adding them all on load...

**Comment by nicolasgarnier** [comment]
Hey guys, while we investigate could you also give us a little bit more details on what issues flash is causing on IE or how it's not working on Firefox? That would help a lot thanks!

**Comment by steven-qi** [comment]
For  IE11 on Windows 8.1, see details in #847.

For Firefox, I clicked the copy button, but nothing happened. And when I tried to paste, any previous text in clipboard is pasted, not the expected code snippet.

**Comment by nicolasgarnier** [comment]
I have a fix for FF comming up.

**Comment by nicolasgarnier** [comment]
Here: #879

**Comment by nicolasgarnier** [comment]
Fixed in #879. We'll track potential IE performance issues in #847.
