### ISSUE TITLE
Add more features to the grid

### ISSUE THREAD

**Issue by web2style** [google/material-design-lite#860]
You are using flexbox to build the grid. And flexbox gives us much more functionality. Here is an example: http://flexboxgrid.com/

Offsets, Auto Width, Nested Grids, Alignment, Distribution, Reordering, Reversing... It can be done so easily with flexbox.

We can just fork this repository, use MDL naming and... magic :)

**Comment by jgoux** [comment]
+1 to this, I love how angular-material grid (https://material.angularjs.org/latest/#/layout/grid) works, it's really awesome **and** easy to use.

**Comment by Garbee** [comment]
This is very vague. Could you please expand on specific use-cases and examples of what kind of setup can be added to the grid?

**Comment by web2style** [comment]
@Garbee Here is a specific use-case: http://prntscr.com/7q8llk

Aligning a block vertically to middle or bottom is just adding a single class. This is what flexbox created for. Why don't use it in the grid?

**Comment by surma** [comment]
We built the grid from the ground up because MD has a very unique take on break points. The most outstanding difference is that we change the number of columns with different screen sizes instead of sticking with let’s say 12 columns and resizing the individual columns.

I agree that our grid is on the minimalistic side, but so far I’ve considered that a good thing. I am hesitant to merge in other grids “just because features”, let alone the license issues that come along with that.

> Offsets, Auto Width, Nested Grids, Alignment, Distribution, Reordering, Reversing... It can be done so easily with flexbox.

As you said, we are using flexbox. So reordering and reversing come for free with the vanilla CSS flex attributes. Our grid always occupies it’s entire container, so auto width is a given. Offsets – for now – are implemented using empty containers, but #239 is talking about this. And nested grid also come for free (just add `.mdl-grid` to a `.mdl-cell`).

If you have concrete features that you feel our grid implementation lacks, please open up an issue. We really *do* want to know, how you are using this :)

**Comment by surma** [comment]
@web2style To recreate your example with our grid you would need to add a CSS attribute `align-self: flex-start` or `align-self: center` to the right element. 

I don’t see a notable benefit adding extra classes to our grid to do that for you, as you will have styling on those elements anyways and we wouldn’t even be saving you any amount typing.

**Comment by web2style** [comment]
@surma According to BEM CSS, that would be a `.l-` block (stands for layout). This is a class responsible for positioning only and not for appearance. So such classes would be a natural part of the CSS framework we are building.

**Comment by Garbee** [comment]
It would actually be, `.mdl-layout` for the full block name. We prefix everything we do to keep our styles as isolated as possible.

Ideally, we should minimize the number of classes we add to handle one rule change. While some do exist, they are very peculiar circumstances. I don't like the idea of having a bunch of one-off classes adding to everyone's overall page weight when only a handful of developers will even take advantage of a small fraction of them. It seems best to let developers custom code parts like that they need to their situation.

That being said, we really do care about how things are being used. This issue I'm tempted to close as-is since it is not directly actionable. Instead new issues should be opened with direct use-cases and actions to resolve so we can discuss the individual merit of additions and gauge them with the wider community.

**Comment by webdesignberlin** [comment]
nice work!
+1 for Grid - Push/Pull (Offset cols)

**Comment by kybarg** [comment]
+1

**Comment by Garbee** [comment]
I am now closing this specific issue due to vagueness. Please file individual issues for new additions you would like to see with an example use-case.

It is hard to plan work with unactionable and vague requests.
