### ISSUE TITLE
Configure sizes for fonts, margins, paddings, ...

### ISSUE THREAD

**Issue by haschek** [google/material-design-lite#864]
Currently the framework cannot be used with relative sizes for fonts, paddings, margins, etc without overwriting a lot of the core modules. It would be great to use sass variables for those size values, 1px values (eg for borders) probably can be ignored here.

This is not a discussion about px versus em/rem, there are good arguments for both sides.

**Comment by surma** [comment]
We do have [_variables.scss](https://github.com/google/material-design-lite/blob/0b6dd0d3fc72bb67c6816a091e0c66cec40ecb6e/src/_variables.scss) which should let you be able to tweak *a lot*. So putting your custom margins, font-sizes etc in there might yield what you are looking for.

**Comment by Garbee** [comment]
I think this is one inherent outcome of following MD so closely. It is pretty strict in each component and we carried it out directly. This means we didn't relate common lengths together, since then you could change one thing, then a bunch of other things change. This would then cause it to not adhere to MD as closely and/or end up looking horrible.

**Comment by haschek** [comment]
@surma Yes, I've have seen _variables.scss and some stuff is configured in vars there but other stuff is done directly in module imports, e.g. font sizes in _mixins.scss.

@Garbee there are configureable sizes already, so currently we have a mixed solution. I ask to make provide even the other size options in the default configuration that they can be defined by the user before. If it is necessary to change core modules to change some size values then the chances are even higher that the finished styles end up looking horrible and not justified. Styles would always look good with the default configuration, everything else is the decision of the user.

@addyosmani I just wondering if there are any project guidelines that imply hard-coded size values in pixel, or if the project is open to a fully configurated variable stack? I would commit time to do it but would like to know in advance if it has the chance to merged into this repository.

**Comment by surma** [comment]
>  I just wondering if there are any project guidelines that imply hard-coded size values in pixel

Most of these values are directly taken from the MD spec, which – in most cases – is very precise. So enabling users to changing those would definitely not be a first-class feature, but nothing is keeping you from grabbing our SASS :)

**Comment by haschek** [comment]
@surma Of course, I could fork MDL and just do it. But it is always a pain to keep the fork compatible with upcoming versions of the original project if the changes won't be have any chance to get merged back to it.

**Comment by Garbee** [comment]
I think doing so many variables was a bad idea now... In hindsight, they all weren't meant as "These can be customized to your hearts content" as much as it was saving us repetitive typing and maintenance within the codebase. Some of them certainly can be customized, but the situations in which you should get iffy. And then, when they do expand, it isn't tied to anything else (like the font size). It seems pretty trivial to me (looking at cards) as to when things change since it is based on the configuration of different card parts, not say the font size of the document.

I think switching the way things are done is going to lead to bigger issues. Sadly, we can't undo all the `!default`'s we have now, so they are kinda stuck in a public state.

If there were a quick mockup to show that we could run to see how things would be handled, at least within one or two components, then that would be useful. Trying to handle something this close to core construction is hard to deal with in an abstract. Otherwise I feel this is just handing a really powerful blade over to someone that isn't balanced and hoping they don't cut themselves to bits trying to use it.

**Comment by haschek** [comment]
Yes, there are good reasons for both: fully hard-coded layout (maybe except colors) vs. fully configurable layout. Currently a mixed version is used, that is a little bit confusing and one of the reasons I've asked about this subject.

I will go into this issue later this week, trying to find a suggestion for a useable stack of size variables and a solution for the ``!default`` "problem." What is a good revision to start a local branch, just the lastest master or v1.0.0, or is it better to wait for v1.0.1?

**Comment by Garbee** [comment]
Since this is really just mockup stuff, starting off with the current master would suffice just fine. Ideally, I'd say only look into making two, possibly three, components adaptive. Ideally cards being one of them since they are super-finicky and where I have the most worry about things blowing up quick.

**Comment by haschek** [comment]
Here is my suggestions for a config stack of sizes:

1. Put all size configurations behind a condition, I used `$use-material-design-strict` (default: true). ``!default`` would be not necessary anymore, the stack can be overwritten by setting the switch `$use-material-design-strict` to false and importing a full size configuration before loading the MDL imports. Without that switch, everything would need a ``!default``.
2. I added more size variables and used them for typography, layout and cards module. See https://github.com/eccenca/material-design-lite/tree/feature/defaultconfigstack

Second, I tested it with some mockups:

1. Changed most of the sizes variables to relative values. As test cases I've used the examples for the blog, dashboard, article and text-only templates. See https://github.com/eccenca/material-design-lite/tree/test/relativesizes
2. I used the relative size with a dynamic configuration for the font-size, related to the size of the viewport: ``html {font-size: calc(0.875em + 0.125vh + 0.125vw);}. See https://github.com/eccenca/material-design-lite/tree/test/biggersizes

**Comment by Garbee** [comment]
That actually appears fairly promising... The only thing is BC in 1.x lifecycle would be iffy. Certainly worth discussing more.

**Comment by haschek** [comment]
No problem, anytime! Just tell me how we can support you on that when you have a decision/timeline for this feature.

**Comment by Garbee** [comment]
I'm currently doing some initial mockups for V2 and am using `rem` units just about everywhere pixels get used. Once 1.1 is released and we review the V2 stuff and merge (since it could get rejected entirely) it would be great to get some eyeballs on it to see where it is failing.

I think in response to @surma's point on the spec being pretty hard-set on dimensions... As long as what the core provides by default aligns, we are good. Say by a standard 100% zoom viewport with no modifications to the base text size. If people need to increase the size of things for legibility (a11y reasons) then the page should easily flow with that, even if things get bigger than MD says they should. As long as it is uniform, we are good here. `rem` provides that uniformity in a way that doesn't seem to become a headache to maintain.

**Comment by sgomes** [comment]
As an update, we should only be using `rem` for things marked as `sp` or "scaling pixels" in the spec. Everything which is marked as `dp` or "device pixels" should stick CSS pixels.

**Comment by haschek** [comment]
1. Using `rem` as `sp` and `px` as `dp` works only in two cases: no or relative `font-size` on `html`. As `rem` is defined as a relative size based on the root element, a definition of `html {font-size: 14px;}` leads to `1rem` equal `14px`, therefore a usage of `1rem` is the same like `14px`.
2. Some combinations of `sp` and `dp` may need a re-evaluation, e.g. definitions of the `font-size` in `sp` and the `line-height` in `dp`. It may lead to broken interfaces when the scaling font size gets bigger than the non-scaling line height. A non-scaling line height should be work with a scaling font-size at least for some (3 or 4) levels of larger text size.
3. I opened that issue not especially for `rem` sizes, I opened it to request a full configuration of all options and measures ala `$font-size: 14px !default;`, so it can predefined/overwrittten by MDL users (developers). If measures are used hardcoded in statements then every change needs to be done by overwriting statements later. This is very hard to maintain and increases CSS file sizes.

**Comment by Garbee** [comment]
> a definition of `html {font-size: 14px;}` leads to `1rem` equal `14px`, therefore a usage of `1rem` is the same like `14px`.

That is going away in V2.

With V2 each component will be fully isolated with no global element targets on our part. That way they will stand alone and be able to be used within any other project without conflicts if things are sane.

Also we are re-assessing our variable situation as it is pretty crazy. More on the V2 stuff though once we have finalized the implementation details.

**Comment by haschek** [comment]
@Garbee Global configuration is not necessary, but please do not hard-code local component configurations.

Are there any docs about current state of V2 implementation details? Is there a plan for the release of V2? Anything, that can be tested yet? (v2-components-poc branch?)

If I can provide help, nudge me.

**Comment by Garbee** [comment]
We will do a blog post when we finalize the details internally and provide our implementation docs. At that point we will be looking for more community testing/feedback on the structure. Work is being done in `master` for v2, however it is still early.

The localized-component configuration is pretty much going to happen. We are scaling back our preprocessor usage heavily in order to make the codebase far more sane and understandable. Right now we have a complete mess.

**Comment by sgomes** [comment]
Not feasible to make this any more customisable in v1. As for v2, we will not facilitate this sort of overriding; that said, we'll use simpler selectors so it should be easier to override.

**Comment by akash5324** [comment]
margin, padding doesn't work with the grid layout for the mdl-cell elements.
