### ISSUE TITLE
Component upgrade requires clarification

### ISSUE THREAD

**Issue by antonmoiseev** [google/material-design-lite#871]
Hi guys, really like MDL, thank you! You released it only 2 days ago, but we are eager to try it out in our new project. However I'm a little bit confused with component upgrades:

1. Most JS application frameworks use some kind of templating to render UI, so HTML elements are dynamically added to the page. How MDL works with template engines? Does it require to individually upgrade each component as soon as a piece of markup is added to the page?
2. What components require upgrade? The ones that use `mdl-js-*` CSS classes?
3. If a component has multiple `mdl-js-*` classes do we need to upgrade the component multiple times one per class?
4. The home page highlights an example of upgrading the button component: `componentHandler.upgradeElement(button, 'MaterialButton')`. But I haven't found in the docs what names other than `MaterialButton` should be used to upgrade components. Is it documented anywhere?
5. My initial impression was that upgrade is required to give a component some behavior (like ripple effect, etc.). However I noticed some components are not properly rendered if they are not upgraded (e.g. layout component lacks the bottom border and the shadow). Is it a bug or components are not expected to be usable without a proper upgrade?

**Comment by Garbee** [comment]
1. How it works with template engines... Depends on the engine and how things are setup. We didn't worry about that in development since there are way too many to worry about. I don't see why things shouldn't work in most setups as long as logic is handled in the right order.
2. Anything registered to the component handler needs an upgrade. `mdl-js` are how you can identify provided components yes, however custom components may not use the same pattern (and shouldn't use the mdl prefix!)
3. The component handler will handle upgrading everything if you just call it with [no parameters](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js#L62-66). We do need to improve the story for upgrading a subset of the DOM, I either have this working and forgot or it still has some work to be done.
4. You can check all the components JS files. At the end is registration, but you can also just pull the object's name directly and use that since we follow that pattern.
5. Layout requires JS and therefore the upgrade. No JS works without the component handler, that is how we delegate everything internally.

**Comment by jh3y** [comment]
@antonmoiseev, out of curiosity, which JS framework are you looking to use MDL with?

As @Garbee references, use of `componentHandler.upgradeDom` can work in cases.

For example; upgrading menus to work,
```javascript
componentHandler.upgradeDom('MaterialMenu', 'mdl-menu');
```

@jh3y

**Comment by Garbee** [comment]
Something I was working on, too lazy/busy right now to check the source, was a method for handing a NodeList or array into a function to just loop over that area and handle all upgrades. Can't remember right now if it is in the current source or if I pulled it in a time-crunch.

Once that lands (or if it already exists), then you just can pass the list in and target upgrades nicely. I thought of this exact kind of situation and was trying to prepare for it. Thankfully, it can be added in 1.x since it won't break BC at all. :smile:

**Comment by jh3y** [comment]
Yeah the NodeList/Array approach seems most appropriate :smile: 

For now, `upgradeDom` approach is a pretty fine work around for any application breaking states(menu not opening etc.)

**Comment by yan-foto** [comment]
If I got it right (from [the source code](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js)) `componentHandler.upgradeDom` and `componentHandler.upgradeElement` do virtually the same thing, where the former accepts a css class and finds all corresponding elements and the latter accepts a specific DOM element. However, I don't quite understand when elements are registered with the `componentHandler`. I constantly get `Unable to find a registered component for the given class.`.

I am trying to use the [`tabs`](https://github.com/google/material-design-lite/tree/master/src/tabs) element on a DOM element rendered by [React](https://facebook.github.io/react/) by calling `componentHandler.upgradeElement(domElement, 'mdl-tabs')` after React renders `domElement` into DOM.

**Comment by Garbee** [comment]
@yan-foto Sorry, the variable naming can be confusing at first...

`componentHandler.upgradeElement(domElement, 'MaterialTabs')` is what should work there. `jsClass` is the class as string registered with the component.

> However, I don't quite understand when elements are registered with the componentHandler.

They are registered at [this point](https://github.com/google/material-design-lite/blob/master/src/tabs/tabs.js#L148). Whenever this runs is when they are added to the registry. Then things are upgraded by default on document load.

**Comment by yan-foto** [comment]
Now I understand it. So for every element which is not present upon [`window.load`](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js#L261), it is required to initialize the component manually using `componentHandler.upgradeElement`. That makes sense! Thanks :dancer:

**Comment by Garbee** [comment]
@yan-foto Or you could just `upgradeDom` without any params. It will go over everything, but it skips things already upgraded and for most sites shouldn't lead to a big perf deficit. Of course, test to be sure!

**Comment by yan-foto** [comment]
OK just for the reference If anyone else uses the method [mentioned on getmdl.io](http://www.getmdl.io/started/index.html) to fetch their `material.js` from `https://storage.googleapis.com/code.getmdl.io/1.0.0/material.js` or even used bower (`bower install material-design-lite`):

calling `componentHandler.upgradeElement` with no second parameter (`jsClass`) does not work in that version and is only applicable to the code on `master` branch (or tag [`v1.0.0-rc.1`](https://github.com/google/material-design-lite/tree/v1.0.0-rc.1)) of this repository. :confused:

**Comment by Garbee** [comment]
Um, the optional second parameter has yet to be updated on the main site as far as I can tell. Where are you seeing it exactly?

And that functionality is still under development, so yes master only at the moment. The RC.1 tag is mostly just for testing right now, we have other things that need to land before that tag is stable.

**Comment by Garbee** [comment]
And looking at the rc.1 tag, it doesn't work in there either. That is the RC tag for version 1.0.0 itself, not 1.0.1 RC. Right now, the updated method only works from the master branch since the functionality is still experimental and shouldn't be used in production.

**Comment by yan-foto** [comment]
@Garbee I am seeing it only on the master branch of this repository. After our previous discussion, I thought it might be included in the dist. Thanks for the clarification.

So I would say for now I have to use the good ol' way of upgrading elements one by one or just use `componentHandler.upgradeDom()` to upgrade the whole DOM.

**Comment by yan-foto** [comment]
@Garbee shall I make a pull request and add a summary of what I have published about MDL's `componentHandler` [here](http://quaintous.com/2015/07/09/react-components-with-mdl/)?

**Comment by antonmoiseev** [comment]
@Garbee thank you for the clarification.

@jh3y we are trying it out together with Angular 1, and experimenting with Angular 2. With A1 our POC example works just fine, with A2 we had issues until we discovered this `componentHandler.upgrade` thing.

**Comment by Garbee** [comment]
@yan-foto Right now we have no story for that kind of content on the microsite. It is something we need to look into since I also have some content in the wiki here that needs to be improved and moved in. I'm not sure what a PR would end up doing so I'm hesitant to ask for one at the moment. We are trying to keep an eye on our top-nav links and keep the number down. Then the Getting Started doesn't seem like a good fit for such detailed content.
