### ISSUE TITLE
Showcase of websites using MDL

### ISSUE THREAD

**Issue by hkminegod** [google/material-design-lite#892]
A showcase on the website for websites using this framework.

**Comment by Garbee** [comment]
Right now we show off some Google projects through the FAQ. Considering it was only released a few days ago though, I'm not sure many are using it yet well enough to justify a new place for it already.

Maybe in a few months time after developers have built some stunning sites...

**Comment by addyosmani** [comment]
I wonder if it's worth creating a wiki page for others to add in the sites they've created using MDL. We could later use it as a seed for whatever showcase we create in the future.

**Comment by surma** [comment]
Wiki page won’t hurt. Why not

**Comment by addyosmani** [comment]
https://github.com/google/material-design-lite/wiki/Sites-using-Material-Design-Lite has been setup.

**Comment by addyosmani** [comment]
Note: we currently have the wiki setup so that it can only be edited by users with push access. Should we change this or ask folks to submit an issue with the three pieces of data needed and we'll get it added to the wiki for them?

**Comment by Garbee** [comment]
Is it a requirement being under Google that the wiki be that way? I'd
recommend opening it up and see how it goes. We can always restrict it
later and change policy if the openness gets abused.

**Comment by surma** [comment]
@Garbee That would make me feel kinda uncomfortable. If anybody can just add any site, we might end up looking like we endorse things that we shouldn’t. But I’ll let @addyosmani make the call on this one.

**Comment by Garbee** [comment]
The page should be clear that we aren't endorsing anything shown. They are provided purely as examples of sites produced using the project.

Opening up the wiki also allows for anyone to help expand the content already there for understanding the system. For example, helping improve the "Understanding the Component Handler" content if they so desire. That is where keeping an eye on it is needed though, since if it does get abused in any way it would need to be locked back down and a system put in place for getting contributions in.

Right now most of it is sitting half-baked waiting for me to get the time to go over it. :smile:

**Comment by Garbee** [comment]
Hold up, can't open up the wiki. :frowning: 

We need a signed CLA for any contributions. No way to verify that with an open wiki.

So yea, let me make a quick issue template for new site recommendations.

**Comment by Garbee** [comment]
Ok, updated the wiki page with an issue link. Also moved the content on that to the bottom so the primary purpose of the page is gotten to faster by viewers.

**Comment by addyosmani** [comment]
Thanks @Garbee!
