### ISSUE TITLE
[Component Request] CSS Class for Button Action Floating

### ISSUE THREAD

**Issue by urbanvikingr** [google/material-design-lite#901]
* Description
I would like to request additional CSS class to button to create the floating action button. It is seen on most new Google apps.

* Material Design Spec link
http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

For your convenience, I have provided an example for desktop

.mdl-button--floating-action {
  position: fixed;
  right: 24px;
  bottom: 24px;
  padding-top: 24px;
  margin-bottom: 0;
  z-index: 998;
}

**Comment by Garbee** [comment]
Is this request for the button itself (which we currently have) or a way to position it somewhere precisely on the page?

**Comment by urbanvikingr** [comment]
@Garbee Correct material  designed buttons exist, but I didn't see the action floating properties anywhere. I was thinking adding CSS class named something like ```.mdl-button--floating-action``` that would place the button in lower left corner (24dp margin on desktop/tablet and 16dp margin on phone).

**Comment by urbanvikingr** [comment]
@Garbee I included the Material Design specification in my request.

**Comment by Garbee** [comment]
That's the problem though, positioning. We'd need multiple positions since the button *can* be placed anywhere really. Plus, depending on design and placement of items, people will need them at different places even where we do support. 

Looking over our classnames... ugh. I'm not sure BEM allows double-modifiers. We'd need to either make Fab's a new element level item so modifiers can be applied or leave this to custom code until 2.0.

Also `--floating-action` isn't a sound modifier imo, `--fab` exists which is the semantic acronym for the same thing, could get confusing.

So, any suggestions for how to implement this in a BC way?

P.S. Yea, I saw the spec sheet, it only raises more doubts in my mind on implementing it well. But I could also just be insane right now.

**Comment by urbanvikingr** [comment]
Thanks for adding it to the wish list. I have a few others that I will create tickets for as I implement. I will create a ticket for each with reference to MD documentation and suggested implementation. Thanks again.

**Comment by urbanvikingr** [comment]
Just wanted to add link to [materializecss] (http://materializecss.com/buttons.html) who has implemented this button behaviour.

**Comment by Garbee** [comment]
Pulling from their example though...

```html
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>
```

Note the very first line, how they are applying absolute positioning manually. That is what you can do right now with our setup. Your request is for classes to handle this automatically, which can be done but is a bit more complicated to handle well (partly due to our naming convention being slightly off.)

**Comment by urbanvikingr** [comment]
@Garbee Thank you for pointing this out. Perhaps this is just an update to documentation.

I need to add this css to get a floating action button with MDL.

```
.mdl-button--floating-action {
bottom:45px;
margin-bottom:100px;
padding-top:24px;  
position:fixed;
right:24px;  
z-index:998;
}

**Comment by Garbee** [comment]
That is general CSS. Not something we should directly document without a
very compelling reason.

**Comment by urbanvikingr** [comment]
The "floating action button" is well-documented in Material Design guidelines (own section) and used across all new Google apps e.g. Inbox.
Isn't this reason enough to have an example on how to implement a "floating action button" with MDL?
Would you like me to do a pull request on update to MDL documentation?

**Comment by Garbee** [comment]
Closing this on out.

We can't directly handle classes to position since:
* It doesn't directly have defined locations.
* Dynamically figuring it out is intensive when abstracted to the degree we would need to.

Perhaps in V2 docs we can have some example usage sections to show custom things like this. However, it is low-priority since positioning is a basic concept of CSS that developer should know when implementing a design like this.

**Comment by CelticParser** [comment]
This should be reopened: Inline style rules is a NO-NO. The designer can over-ride just like all the other modules here.

**Comment by Garbee** [comment]
@CelticParser Where do inline styles come in? That is one choice a developer may make when implementing their own styling to move things around. However it is still completely valid (and what I assumed) that developers make their own classes to do these things.

**Comment by xenoterracide** [comment]
this really should be implemented as part of the "library" and not something the developer is required to implement

**Comment by Garbee** [comment]
I just brought this up yesterday for V2 and we will make it explicit in V2 that developers are to implement this on their own. The placement is not defined and it depends upon the application's UX where exactly it should go. Therefore, it is best left to developers.

This is fairly trivial absolute positioning, no real reason for us to include some form by default.

**Comment by makhnovskiy** [comment]
Agree with the benefits of this, using material after my time with bootstrap, and love the css class "pull-right". Missing all the small assistant styles... The more options the a developer has (even though its a few lines of CSS), the happier they are using a full pledged system with all the bells and whistles. Of course, this adds the complexities, documentation and weight to a (almost) weightless system.

**Comment by Garbee** [comment]
We are *not* a full framework. We are specifically providing Material Design components to use within your application. Doing everything for you to just have classes to build things is not the intent of the project.

Placing a FAB absolutely is non-trivial. It's proper placement depends upon your sites design. There isn't a feasible way we can include this type of placement modifier in the core.

**Comment by joaopluigi** [comment]
You can probably copy the 'view-source' button style as shown in https://getmdl.io/templates/index.html examples

```html
<style>
    #view-source {
        position: fixed;
        display: block;
        right: 0;
        bottom: 0;
        margin-right: 40px;
        margin-bottom: 40px;
        z-index: 900;
    }
</style>
```

**Comment by xenoterracide** [comment]
I just moved on to a more mature framework.
