### ISSUE TITLE
Add Content-Security-Policy to all example pages

### ISSUE THREAD

**Issue by salamanders** [google/material-design-lite#911]
Given that people are going to be copy-pasting the examples like http://www.getmdl.io/templates/dashboard/index.html
It would be a nice security best practice to include an optimized Content-Security-Policy for each example.

My NOT optimized policy:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' https://fonts.gstatic.com; 
	script-src 'self' https://storage.googleapis.com; 
	style-src 'self' 'unsafe-inline' https://storage.googleapis.com https://fonts.gstatic.com https://fonts.googleapis.com;">
```

**Comment by Garbee** [comment]
I'm not sure adding strict headers to templates are exactly a "best practice". Especially since this should be explicitly defined by the developer in their project so they understand what is going on. That means they acknowledge the responsibilities that come along with it.

i.e. Someone copies this, then any script hosted from `storage.googleapis.com` is open, even if it is hosted by a malicious user on the storage service in order to attack people in just this way.

Security is something we need to encourage developers to take on themselves (and doing what we can within our components to handle it by default.) But, this seems to take things a bit further then I would like.

**Comment by salamanders** [comment]
I disagree but I may be in the minority.

Most people don't use content security policy at all. Some security is
better than none. I wanted to try it, but got annoyed because I keep having
to add domains. A starter set that allowed the example to run would have
sped things up.

"since this should be explicitly defined by the developer in their project
so they understand what is going on"

That would be great - but is a future state. Better now to get people at
least aware!

**Comment by Garbee** [comment]
I'd rather we not make people aware by having things break unexpectedly on
them. Best more widespread evangelism is done and tooling get updated to
help with this (I know the latter is being worked on.)

**Comment by sgomes** [comment]
Out of scope for our examples.
