### ISSUE TITLE
Can't use all icon

### ISSUE THREAD

**Issue by hassi2k7** [google/material-design-lite#967]
Hello,

if i try to use some different icons from the icon sheet shown at https://materialdesignicons.com/ I get some errors.

Examples: 
<i class="material-icons">book-open</i>
This will show the book-open icon but with a very big margin that ruins my layout

<i class="material-icons">message-video</i>
The same problem here. The icon is displayed correct, but with a extrem width

<i class="material-icons">trophy</i>
This icon will not be displayed

Best regards,
Daniel

**Comment by Garbee** [comment]
[reproduction codepen](http://codepen.io/anon/pen/KpRrxN). Not sure if this is a problem in MDL or upstream...

**Comment by surma** [comment]
I think that may be the same problem Roman Nurik ran into. This is not our icon font, though, this is: http://google.github.io/material-design-icons/

**Comment by surma** [comment]
Nvm, just saw that you *are* in fact using our font.

**Comment by Garbee** [comment]
So, trophy is not an issue. That is not a Google-provided icon. Please reference the link Surma provided for the official icon list.

**Comment by Garbee** [comment]
Just thought to see if it is MDL or not. Using [this example](http://codepen.io/anon/pen/BNxMaJ) shows it isn't an MDL issue since the problem persists with *only* pulling in the material icons. You should file a bug with the [icon repository](https://github.com/Google/material-design-icons) so they can take a look.

**Comment by Garbee** [comment]
Actually, don't file upstream. The problem is the words. [This example](http://codepen.io/anon/pen/BNxMaJ) (may have overwritten the previous example...) shows them working just fine. Because "book" is the icon, not "book-open" or "book_open". So "book" triggered the icon while -open was still taking text space, but not having an associated icon.

[This is the list](https://www.google.com/design/icons/) of all provided icons and the associated ligatures. Please use them instead of a 3rd party resource that also mixes in non-provided icons and that may or may not be modifying names.
