### ISSUE TITLE
Dynamic rows in selectable data table does not have checkbox [v1.0.0]

### ISSUE THREAD

**Issue by yan-foto** [google/material-design-lite#984]
The data table creates checkboxes for each row upon [initation](https://github.com/google/material-design-lite/blob/v1.0.0/material.js#L3507). So if rows are added dynamically afterwards, the checkboxes are not shows.

A solution would have been to use `componentHandler.upgradeElement` or `componentHandler.upgradeDom`, but since the `table` has already been upgraded, those two calls are [simply ignored](https://github.com/google/material-design-lite/blob/v1.0.0/material.js#L92). Moreover since the data table doesn't provide a downgrade method, there is no other way (that I know of) to add checkboxes to dynamically added rows.

An example (implemented with React) can be found [here](http://codepen.io/yan-foto/pen/aOGMZy?editors=101).

**Comment by Programming4life** [comment]
+1

**Comment by atstek** [comment]
+1 Man, I really need this component! I'm trying to build SPA using MDL + [Marionette](http://marionettejs.com/).

**Comment by koddsson** [comment]
+1

**Comment by Garbee** [comment]
We don't need +1's on anything. If you wish to get updates please use the subscribe button for the issue in the right sidebar for the issue.

**Comment by italoacasas** [comment]
someone find a solution for this bug in react?

**Comment by kdar** [comment]
I don't use react, but in mithril what I do is attach to the event handler that executes when the DOM is completely loaded/rendered, and I call componentHandler.upgradeAllRegistered();. I'm sure react has a similar event.

**Comment by yan-foto** [comment]
@italoacasas I had a similar discussion with another dev [here](http://quaintous.com/2015/07/09/react-components-with-mdl/#comment-2131255770) and created a naive solution on [codepen](http://codepen.io/yan-foto/pen/yNjwaO?editors=101): I add a random key to my `table` every time I add a row and force react to rerender it. The caveat here is that by each rerender the checked state get lost, but that is not that complicated to save before rerender.

**Comment by italoacasas** [comment]
thanks guys.

**Comment by wlekin** [comment]
Remove 'data-upgraded' attr from table, and upgradeDom again should did the trick.

**Comment by Garbee** [comment]
@wlekin That is not a good solution. It will lead to memory leaks by having multiple copies of the table node in the component handler's registry of upgraded nodes.

**Comment by liddellj** [comment]
I implemented the workaround detailed in the CodePen provided by @yan-foto and it works. Many thanks.

**Comment by RiCoTeRoX** [comment]
"hack" with marionettejs: on onShow()  call componentHandler.upgradeAllRegistered().

please solve this if is am issue

**Comment by Garbee** [comment]
We are officially [deprecating the automatic checkbox generation](https://github.com/google/material-design-lite/wiki/Deprecations#automatic-selection-checkboxes) for data tables. Please see the wiki page for instructions on how this should be replaced in your current code. The new method allows developers more control over the checkboxes in every way, as well as more intuitive removing and adding new rows.

Due to this deprecation we will not be adding this or any other new functionality for this component's JS.

**Comment by itamaro** [comment]
> We are officially deprecating the automatic checkbox generation for data tables.

This is a reasonable decision, but it would be fair to at least have the [official docs on tables](https://getmdl.io/components/index.html#tables-section) not use `mdl-data-table--selectable`, don't you think?

**Comment by Garbee** [comment]
V1 is on community support at this point other than critical issues.

It isn't ideal, but the docs in this case aren't worth updating since `--selectable` is still working as expected in V1. V2 will be when the removal happens (as it has already happened in our working code.) We'd instead have to get UX designs done for deprecation warnings and integrate them back into the V1 site and push. That is actually quite a bit of work for something that is working as intended.

**Comment by itamaro** [comment]
gotcha

**Comment by codechippy** [comment]
See here for example code on how to use this and be able to check for checkbox state

https://github.com/codechippy/MDL-Dynamic-Tables

**Comment by tomasdev** [comment]
v2 is coming... when?
